#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# run-py-2g: Summarize Python Borusyak quality DiD outputs
# ============================================================
#
# Purpose:
#   Summarize Python Borusyak quality DiD outputs generated by
#   run-py-2f-did-borusyak-quality.sh.
# Inputs:
#   repo_python/did_final/quality_did_borusyak/borusyak_quality_static_effects_<variant>.csv
#   repo_python/did_final/quality_did_borusyak/borusyak_quality_dynamic_effects_<variant>.csv
#   repo_python/did_final/quality_did_borusyak/borusyak_quality_panel_checks_<variant>.csv
#   repo_python/did_final/quality_did_borusyak/borusyak_quality_input_summary_<variant>.csv
#   repo_python/did_final/quality_did_borusyak/borusyak_quality_errors_<variant>.csv
#
# Supported variants:
#   flexible
#   strict
#
# Outputs:
#   repo_python/did_final/quality_did_borusyak/summary/
#     - borusyak_quality_static_effects_paper_ready.csv
#     - borusyak_quality_static_effects_wide.csv
#     - borusyak_quality_main_panel_table.csv
#     - borusyak_quality_main_panel_table.md
#     - borusyak_quality_dynamic_effects_percent.csv
#     - borusyak_quality_dynamic_effects_plot_ready.csv
#     - borusyak_quality_summary_notes.txt
#
# Usage:
#   MAIN_PANEL=strict bash run-py-2g-summarize-borusyak-quality.sh
#   MAIN_PANEL=flexible bash run-py-2g-summarize-borusyak-quality.sh
# ============================================================

LOG_DIR="${LOG_DIR:-logs}"
RUN_TS="${RUN_TS:-$(date +%Y%m%d-%H%M%S)}"
LOG_FILE="${LOG_FILE:-${LOG_DIR}/run-py-2g_summarize_borusyak_quality_${RUN_TS}.log}"

INPUT_DIR="${INPUT_DIR:-repo_python/did_final/quality_did_borusyak}"
OUTPUT_DIR="${OUTPUT_DIR:-${INPUT_DIR}/summary}"
PY_SCRIPT="${PY_SCRIPT:-proc_scripts/summarize_borusyak_quality_outputs_python.py}"

MAIN_PANEL="${MAIN_PANEL:-strict}"
PANEL_VARIANTS="${PANEL_VARIANTS:-flexible strict}"

mkdir -p "${LOG_DIR}" "${OUTPUT_DIR}"

{
  echo "============================================================"
  echo "run-py-2g: summarize Python Borusyak quality DiD outputs"
  echo "Started:        $(date)"
  echo "Python script:  ${PY_SCRIPT}"
  echo "Input dir:      ${INPUT_DIR}"
  echo "Output dir:     ${OUTPUT_DIR}"
  echo "Main panel:     ${MAIN_PANEL}"
  echo "Panel variants: ${PANEL_VARIANTS}"
  echo "Log file:       ${LOG_FILE}"
  echo "============================================================"
  echo

  if [[ ! -f "${PY_SCRIPT}" ]]; then
    echo "ERROR: Python script not found: ${PY_SCRIPT}"
    exit 1
  fi

  if [[ ! -d "${INPUT_DIR}" ]]; then
    echo "ERROR: Input directory not found: ${INPUT_DIR}"
    exit 1
  fi

  case "${MAIN_PANEL}" in
    flexible|strict)
      ;;
    *)
      echo "ERROR: MAIN_PANEL must be flexible or strict. Got: ${MAIN_PANEL}"
      exit 1
      ;;
  esac

  python -m py_compile "${PY_SCRIPT}"

  echo "** Build combined Python quality outputs"
  echo "------------------------------------------------------------"

  variant_args=()
  for variant in ${PANEL_VARIANTS}; do
    variant_args+=("${variant}")
  done

  python - "${INPUT_DIR}" "${variant_args[@]}" <<'PY'
import sys
from pathlib import Path

import pandas as pd

input_dir = Path(sys.argv[1])
variants = sys.argv[2:]

if not variants:
    raise SystemExit("ERROR: no panel variants provided.")

specs = [
    ("static_effects", True),
    ("dynamic_effects", True),
    ("panel_checks", False),
    ("input_summary", False),
    ("errors", False),
]

for stem, required in specs:
    frames = []

    for variant in variants:
        path = input_dir / f"borusyak_quality_{stem}_{variant}.csv"
        if not path.exists():
            print(f"Missing optional input: {path}")
            continue

        df = pd.read_csv(path)

        if "panel" not in df.columns:
            df.insert(0, "panel", variant)
        else:
            df["panel"] = df["panel"].fillna(variant)
            df.loc[df["panel"].astype(str).str.strip().eq(""), "panel"] = variant

        frames.append(df)
        print(f"Loaded {variant}: {path} rows={len(df)}")

    out_path = input_dir / f"borusyak_quality_{stem}_all.csv"

    if frames:
        combined = pd.concat(frames, ignore_index=True)
        combined.to_csv(out_path, index=False)
        print(f"Saved combined file: {out_path} rows={len(combined)}")
    elif required:
        raise SystemExit(f"ERROR: required combined input could not be built for {stem}")
    else:
        empty = pd.DataFrame(columns=["panel"])
        empty.to_csv(out_path, index=False)
        print(f"Saved empty optional combined file: {out_path}")
PY

  echo
  echo "** Summarize Python quality DiD outputs"
  echo "------------------------------------------------------------"

  python "${PY_SCRIPT}" \
    --input-dir "${INPUT_DIR}" \
    --output-dir "${OUTPUT_DIR}" \
    --main-panel "${MAIN_PANEL}"

  echo
  echo "============================================================"
  echo "run-py-2g completed successfully."
  echo "Completed:   $(date)"
  echo "Output dir:  ${OUTPUT_DIR}"
  echo "Log file:    ${LOG_FILE}"
  echo "============================================================"

} 2>&1 | tee "${LOG_FILE}"

echo "Saved log to ${LOG_FILE}"
#
# Reused logic:
#   This wrapper follows the structure of run9g_summarize_borusyak_quality.sh,
#   but it uses Python-specific paths, labels, and panel variants.
#
