#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# run-py-2b: Run SonarQube scan for Python repo-month inputs
# ============================================================
#
# Purpose:
#   Run SonarQube scans for Python treatment/control repo-month
#   input files generated by run-py-2a-create-sonarqube-input.sh.
#
# Inputs:
#   repo_python/run-py-2a/<variant>/<target>/data/ts_repos_monthly.csv
#
# Target:
#   TARGET=treatment
#   TARGET=control
#
# Main output:
#   repo_python/run-py-2b/<variant>/<target>/ts_repos_monthly_scanned.csv
#
# Reuse:
#   Copy a previously verified scanned CSV to the main output path,
#   then run with SKIP_SCAN=true to validate and reuse it.
#
# Usage:
#   Smoke or full depends on the input generated by run-py-2a.
#
#   PANEL_VARIANT=strict   TARGET=treatment NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
#   PANEL_VARIANT=strict   TARGET=control   NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
#   PANEL_VARIANT=flexible TARGET=treatment NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
#   PANEL_VARIANT=flexible TARGET=control   NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
# 
#   SKIP_SCAN=true PANEL_VARIANT=strict   TARGET=treatment NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
#   SKIP_SCAN=true PANEL_VARIANT=strict   TARGET=control   NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
#   SKIP_SCAN=true PANEL_VARIANT=flexible TARGET=treatment NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
#   SKIP_SCAN=true PANEL_VARIANT=flexible TARGET=control   NUM_PROCESSES=1 bash run-py-2b-sonarqube-scan.sh
# ============================================================

TARGET="${TARGET:-treatment}"
PANEL_VARIANT="${PANEL_VARIANT:-flexible}"
LANGUAGE_PROFILE="${LANGUAGE_PROFILE:-python}"
PROJECT_KEY_PREFIX="${PROJECT_KEY_PREFIX:-}"
OUTPUT_SUFFIX="${OUTPUT_SUFFIX:-}"
SKIP_SCAN="${SKIP_SCAN:-false}"

SCRIPT_NAME="$(basename "$0")"
if [[ "${SCRIPT_NAME}" =~ ^(run-py-[^-]+)- ]]; then
  RUN_PREFIX="${BASH_REMATCH[1]}"
else
  echo "ERROR: unable to extract run prefix from script name: ${SCRIPT_NAME}" >&2
  exit 1
fi

if [[ "${TARGET}" != "treatment" && "${TARGET}" != "control" ]]; then
  echo "ERROR: TARGET must be either 'treatment' or 'control'. Got: ${TARGET}"
  exit 1
fi

if [[ "${PANEL_VARIANT}" != "flexible" && "${PANEL_VARIANT}" != "strict" ]]; then
  echo "ERROR: PANEL_VARIANT must be either 'flexible' or 'strict'. Got: ${PANEL_VARIANT}"
  exit 1
fi

if [[ "${SKIP_SCAN}" != "true" && "${SKIP_SCAN}" != "false" ]]; then
  echo "ERROR: SKIP_SCAN must be true or false. Got: ${SKIP_SCAN}"
  exit 1
fi

LOG_DIR="${LOG_DIR:-logs}"
RUN_TS="${RUN_TS:-$(date +%Y%m%d-%H%M%S)}"
LOG_FILE="${LOG_FILE:-${LOG_DIR}/${RUN_PREFIX}_sonarqube_${PANEL_VARIANT}_${TARGET}_${RUN_TS}.log}"

PY_SCRIPT="${PY_SCRIPT:-proc_scripts/run_sonarqube_v2.py}"

OUTPUT_BASE_DIR="${OUTPUT_BASE_DIR:-repo_python}"
INPUT_ROOT="${INPUT_ROOT:-${OUTPUT_BASE_DIR}/run-py-2a/${PANEL_VARIANT}}"
MAIN_OUTPUT_DIR="${MAIN_OUTPUT_DIR:-${OUTPUT_BASE_DIR}/${RUN_PREFIX}/${PANEL_VARIANT}/${TARGET}}"

NUM_PROCESSES="${NUM_PROCESSES:-1}"
AGGREGATION="${AGGREGATION:-month}"

INPUT_FILE="${INPUT_FILE:-${INPUT_ROOT}/${TARGET}/data/ts_repos_monthly.csv}"

if [[ -n "${OUTPUT_SUFFIX}" ]]; then
  OUTPUT_FILE="${OUTPUT_FILE:-${MAIN_OUTPUT_DIR}/ts_repos_monthly_scanned_${OUTPUT_SUFFIX}.csv}"
else
  OUTPUT_FILE="${OUTPUT_FILE:-${MAIN_OUTPUT_DIR}/ts_repos_monthly_scanned.csv}"
fi

if [[ "${TARGET}" == "treatment" ]]; then
  CLONE_DIR="${CLONE_DIR:-../treatment-repos}"
else
  CLONE_DIR="${CLONE_DIR:-../control-repos}"
fi

mkdir -p "${LOG_DIR}" "${MAIN_OUTPUT_DIR}"

{
  echo "============================================================"
  echo "${RUN_PREFIX}: Python SonarQube scan"
  echo "Started:         $(date)"
  echo "Script name:     ${SCRIPT_NAME}"
  echo "Run prefix:      ${RUN_PREFIX}"
  echo "Panel variant:   ${PANEL_VARIANT}"
  echo "Target:          ${TARGET}"
  echo "Python script:   ${PY_SCRIPT}"
  echo "Aggregation:     ${AGGREGATION}"
  echo "Input root:      ${INPUT_ROOT}"
  echo "Input file:      ${INPUT_FILE}"
  echo "Main output dir: ${MAIN_OUTPUT_DIR}"
  echo "Output file:     ${OUTPUT_FILE}"
  echo "Clone dir:       ${CLONE_DIR}"
  echo "Language:        ${LANGUAGE_PROFILE}"
  echo "Project prefix:  ${PROJECT_KEY_PREFIX}"
  echo "Output suffix:   ${OUTPUT_SUFFIX}"
  echo "Skip scan:       ${SKIP_SCAN}"
  echo "Num processes:   ${NUM_PROCESSES}"
  echo "Log file:        ${LOG_FILE}"
  echo "============================================================"
  echo

  if [[ ! -f "${PY_SCRIPT}" ]]; then
    echo "ERROR: Python script not found: ${PY_SCRIPT}"
    exit 1
  fi

  if [[ ! -f "${INPUT_FILE}" ]]; then
    echo "ERROR: input file not found: ${INPUT_FILE}"
    exit 1
  fi

  if [[ ! -d "${CLONE_DIR}" ]]; then
    echo "ERROR: clone dir not found: ${CLONE_DIR}"
    exit 1
  fi

  echo "** Compile Python script"
  echo "------------------------------------------------------------"
  python -m py_compile "${PY_SCRIPT}"
  echo

  echo "** Input summary before scan"
  echo "------------------------------------------------------------"
  python - <<PY
import pandas as pd
from pathlib import Path

path = Path("${INPUT_FILE}")
df = pd.read_csv(path)

required = {"repo_name", "month", "latest_commit"}
missing = required - set(df.columns)
if missing:
    raise SystemExit(f"ERROR: missing required columns: {sorted(missing)}")

print("file:", path)
print("rows:", len(df))
print("repos:", df["repo_name"].nunique())
print("months:", df["month"].min(), "to", df["month"].max())
print("missing latest_commit:", df["latest_commit"].isna().sum())
print("duplicate repo-month rows:", df.duplicated(["repo_name", "month"]).sum())
PY

  echo
  if [[ "${SKIP_SCAN}" == "true" ]]; then
    echo "** Validate and reuse existing scanned output"
    echo "------------------------------------------------------------"

    if [[ ! -f "${OUTPUT_FILE}" ]]; then
      echo "ERROR: SKIP_SCAN=true but output file not found: ${OUTPUT_FILE}"
      exit 1
    fi

    python - <<PY
import pandas as pd
from pathlib import Path

input_path = Path("${INPUT_FILE}")
output_path = Path("${OUTPUT_FILE}")

input_df = pd.read_csv(input_path)
output_df = pd.read_csv(output_path)

key_cols = ["repo_name", "month"]
required_input = set(key_cols + ["latest_commit"])
missing_input_cols = required_input - set(input_df.columns)
if missing_input_cols:
    raise SystemExit(
        f"ERROR: input missing required columns: {sorted(missing_input_cols)}"
    )

missing_output_cols = set(key_cols) - set(output_df.columns)
if missing_output_cols:
    raise SystemExit(
        f"ERROR: reused output missing key columns: {sorted(missing_output_cols)}"
    )

metric_candidates = {
    "ncloc",
    "bugs",
    "vulnerabilities",
    "code_smells",
    "duplicated_lines_density",
    "comment_lines_density",
    "cognitive_complexity",
    "technical_debt",
    "software_quality_maintainability_remediation_effort",
}

if not metric_candidates.intersection(output_df.columns):
    raise SystemExit("ERROR: reused output contains no SonarQube metric columns.")

input_keys = input_df[key_cols].drop_duplicates()
output_keys = output_df[key_cols].drop_duplicates()

missing_keys = (
    input_keys.merge(output_keys, on=key_cols, how="left", indicator=True)
    .query("_merge == 'left_only'")
)
extra_keys = (
    output_keys.merge(input_keys, on=key_cols, how="left", indicator=True)
    .query("_merge == 'left_only'")
)

duplicate_output_keys = int(output_df.duplicated(key_cols).sum())

print("Input rows:", len(input_df))
print("Output rows:", len(output_df))
print("Input unique repo-month keys:", len(input_keys))
print("Output unique repo-month keys:", len(output_keys))
print("Missing input keys in output:", len(missing_keys))
print("Extra output keys:", len(extra_keys))
print("Duplicate output repo-month rows:", duplicate_output_keys)

if len(missing_keys) > 0 or len(extra_keys) > 0 or duplicate_output_keys > 0:
    raise SystemExit(
        "ERROR: reused output does not exactly match the current scan input."
    )

print("Existing scanned output is complete for the current input.")
PY

  else
    # Load SonarQube configuration only when an actual scan/API run is needed.
    if [[ -f ".env" ]]; then
      set -a
      source ".env"
      set +a
    fi

    if [[ -z "${SONAR_PATH:-}" && -n "${SONAR_SCANNER_PATH:-}" ]]; then
      export SONAR_PATH="${SONAR_SCANNER_PATH}"
    fi

    if [[ -n "${SONAR_PATH:-}" && -d "${SONAR_PATH}" && -x "${SONAR_PATH}/bin/sonar-scanner" ]]; then
      export SONAR_PATH="${SONAR_PATH}/bin/sonar-scanner"
    fi

    if [[ -z "${SONAR_PATH:-}" ]]; then
      echo "ERROR: SONAR_PATH is not set."
      exit 1
    fi

    if [[ -z "${SONAR_TOKEN:-}" ]]; then
      echo "ERROR: SONAR_TOKEN is not set."
      exit 1
    fi

    if [[ ! -x "${SONAR_PATH}" ]]; then
      echo "ERROR: SONAR_PATH is not executable: ${SONAR_PATH}"
      exit 1
    fi

    export SONAR_PATH
    export SONAR_SCANNER_PATH="${SONAR_PATH}"

    echo "Sonar scanner: ${SONAR_PATH}"
    echo "Sonar token:   set"
    echo
    echo "** Running SonarQube scanner"
    echo "------------------------------------------------------------"

    CMD=(
      python "${PY_SCRIPT}"
      --aggregation "${AGGREGATION}"
      --input-file "${INPUT_FILE}"
      --output-file "${OUTPUT_FILE}"
      --clone-dir "${CLONE_DIR}"
      --num-processes "${NUM_PROCESSES}"
      --language-profile "${LANGUAGE_PROFILE}"
      --project-key-prefix "${PROJECT_KEY_PREFIX}"
      --incremental-save
    )

    echo "${CMD[*]}"
    echo
    "${CMD[@]}"
  fi

  echo
  echo "** Output metric coverage"
  echo "------------------------------------------------------------"
  python - <<PY
import pandas as pd
from pathlib import Path

path = Path("${OUTPUT_FILE}")
if not path.exists():
    raise SystemExit(f"Missing output file: {path}")

df = pd.read_csv(path)

metric_cols = [
    "ncloc",
    "bugs",
    "vulnerabilities",
    "code_smells",
    "duplicated_lines_density",
    "comment_lines_density",
    "cognitive_complexity",
    "technical_debt",
]

print("file:", path)
print("rows:", len(df))
print("repos:", df["repo_name"].nunique())
print("months:", df["month"].min(), "to", df["month"].max())
print("missing latest_commit:", df["latest_commit"].isna().sum())
print("duplicate repo-month rows:", df.duplicated(["repo_name", "month"]).sum())
print()

for col in metric_cols:
    if col in df.columns:
        print(f"{col}: {df[col].notna().sum()} / {len(df)} non-null")
    else:
        print(f"{col}: MISSING")
PY

  echo
  echo "============================================================"
  echo "${RUN_PREFIX} completed successfully."
  echo "Completed:       $(date)"
  echo "Panel variant:   ${PANEL_VARIANT}"
  echo "Target:          ${TARGET}"
  echo "Skip scan:       ${SKIP_SCAN}"
  echo "Output file:     ${OUTPUT_FILE}"
  echo "Main output dir: ${MAIN_OUTPUT_DIR}"
  echo "Log file:        ${LOG_FILE}"
  echo "============================================================"

} 2>&1 | tee "${LOG_FILE}"
#
# This wrapper is adapted from the logic of run9b-sonarqube-jsts.sh,
# but it does NOT call the existing JS/TS shell wrapper.