#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# run-py-2c: Merge Python SonarQube metrics into matched DiD panels
# ============================================================
#
# Purpose:
#   Merge treatment/control SonarQube metrics generated by run-py-2b
#   into the final Python matched event panels generated by run-py-1l.
#
# Inputs:
#   repo_python/run-py-1l/panel_event_matched_<variant>.csv
#   repo_python/run-py-2b/<variant>/treatment/ts_repos_monthly_scanned.csv
#   repo_python/run-py-2b/<variant>/control/ts_repos_monthly_scanned.csv
#
# Main output:
#   repo_python/run-py-2c/<variant>/panel_event_matched_<variant>_with_sonarqube.csv
#
# Extra QC output:
#   repo_python/tmp/run-py-2c/<variant>/panel_event_matched_<variant>_with_sonarqube_qc.csv
#
# Usage:
#   PANEL_VARIANT=strict bash run-py-2c-merge-sonarqube-panel.sh
#   PANEL_VARIANT=flexible bash run-py-2c-merge-sonarqube-panel.sh
# ============================================================

SCRIPT_NAME="$(basename "$0")"
if [[ "${SCRIPT_NAME}" =~ ^(run-py-[^-]+)- ]]; then
  RUN_PREFIX="${BASH_REMATCH[1]}"
else
  echo "ERROR: unable to extract run prefix from script name: ${SCRIPT_NAME}" >&2
  exit 1
fi

LOG_DIR="${LOG_DIR:-logs}"
RUN_TS="${RUN_TS:-$(date +%Y%m%d-%H%M%S)}"

PANEL_VARIANT="${PANEL_VARIANT:-strict}"

if [[ "${PANEL_VARIANT}" != "flexible" && "${PANEL_VARIANT}" != "strict" ]]; then
  echo "ERROR: PANEL_VARIANT must be either flexible or strict. Got: ${PANEL_VARIANT}"
  exit 1
fi

LOG_FILE="${LOG_FILE:-${LOG_DIR}/${RUN_PREFIX}_merge_sonarqube_panel_${PANEL_VARIANT}_${RUN_TS}.log}"

PY_SCRIPT="${PY_SCRIPT:-proc_scripts/merge_sonarqube_panel_v2.py}"

OUTPUT_BASE_DIR="${OUTPUT_BASE_DIR:-repo_python}"
PANEL_INPUT_DIR="${PANEL_INPUT_DIR:-${OUTPUT_BASE_DIR}/run-py-1l}"
SONAR_ROOT="${SONAR_ROOT:-${OUTPUT_BASE_DIR}/run-py-2b/${PANEL_VARIANT}}"
MAIN_OUTPUT_DIR="${MAIN_OUTPUT_DIR:-${OUTPUT_BASE_DIR}/${RUN_PREFIX}/${PANEL_VARIANT}}"
TMP_DIR="${TMP_DIR:-${OUTPUT_BASE_DIR}/tmp/${RUN_PREFIX}/${PANEL_VARIANT}}"

PANEL_FILE="${PANEL_FILE:-${PANEL_INPUT_DIR}/panel_event_matched_${PANEL_VARIANT}.csv}"

TREATMENT_METRICS="${TREATMENT_METRICS:-${SONAR_ROOT}/treatment/ts_repos_monthly_scanned.csv}"
CONTROL_METRICS="${CONTROL_METRICS:-${SONAR_ROOT}/control/ts_repos_monthly_scanned.csv}"

OUTPUT_FILE="${OUTPUT_FILE:-${MAIN_OUTPUT_DIR}/panel_event_matched_${PANEL_VARIANT}_with_sonarqube.csv}"
QC_OUTPUT_FILE="${QC_OUTPUT_FILE:-${TMP_DIR}/panel_event_matched_${PANEL_VARIANT}_with_sonarqube_qc.csv}"

mkdir -p "${LOG_DIR}" "${MAIN_OUTPUT_DIR}" "${TMP_DIR}"

{
  echo "============================================================"
  echo "${RUN_PREFIX}: merge Python SonarQube metrics into matched panel"
  echo "Started:           $(date)"
  echo "Script name:       ${SCRIPT_NAME}"
  echo "Run prefix:        ${RUN_PREFIX}"
  echo "Panel variant:     ${PANEL_VARIANT}"
  echo "Python script:     ${PY_SCRIPT}"
  echo "Panel input dir:   ${PANEL_INPUT_DIR}"
  echo "Sonar root:        ${SONAR_ROOT}"
  echo "Main output dir:   ${MAIN_OUTPUT_DIR}"
  echo "Extra QC dir:      ${TMP_DIR}"
  echo "Panel file:        ${PANEL_FILE}"
  echo "Treatment metrics: ${TREATMENT_METRICS}"
  echo "Control metrics:   ${CONTROL_METRICS}"
  echo "Output file:       ${OUTPUT_FILE}"
  echo "QC output file:    ${QC_OUTPUT_FILE}"
  echo "Log file:          ${LOG_FILE}"
  echo "============================================================"
  echo

  for f in "${PY_SCRIPT}" "${PANEL_FILE}" "${TREATMENT_METRICS}" "${CONTROL_METRICS}"; do
    if [[ ! -f "${f}" ]]; then
      echo "ERROR: required file not found: ${f}"
      echo
      echo "Make sure run-py-1l and both run-py-2b scans are complete"
      echo "for PANEL_VARIANT=${PANEL_VARIANT}."
      exit 1
    fi
  done

  echo "** Compile Python script"
  echo "------------------------------------------------------------"
  python -m py_compile "${PY_SCRIPT}"
  echo

  echo "** Input file summary before merge"
  echo "------------------------------------------------------------"
  python - <<PY
import pandas as pd
from pathlib import Path

panel_path = Path("${PANEL_FILE}")
treat_path = Path("${TREATMENT_METRICS}")
control_path = Path("${CONTROL_METRICS}")

panel = pd.read_csv(panel_path)
treat = pd.read_csv(treat_path)
control = pd.read_csv(control_path)

print("Panel:", panel_path)
print("  rows:", len(panel))
print("  repos:", panel["repo_name"].nunique())
print("  sources:")
print(panel["dataset_source"].value_counts(dropna=False).to_string())
print()

for label, df, path in [
    ("treatment_metrics", treat, treat_path),
    ("control_metrics", control, control_path),
]:
    print(label + ":", path)
    print("  rows:", len(df))
    print("  repos:", df["repo_name"].nunique())
    print("  months:", df["month"].min(), "to", df["month"].max())
    print("  missing latest_commit:", df["latest_commit"].isna().sum())
    print("  duplicate repo-month rows:", df.duplicated(["repo_name", "month"]).sum())
    print()
PY

  echo "** Merge SonarQube metrics"
  echo "------------------------------------------------------------"
  python "${PY_SCRIPT}" \
    --panel "${PANEL_FILE}" \
    --treatment-metrics "${TREATMENT_METRICS}" \
    --control-metrics "${CONTROL_METRICS}" \
    --output "${OUTPUT_FILE}" \
    --qc-output "${QC_OUTPUT_FILE}"

  echo
  echo "** Add Python run-py-2c QC flags"
  echo "------------------------------------------------------------"

  python - <<PY
import pandas as pd
from pathlib import Path

output = Path("${OUTPUT_FILE}")
qc_output = Path("${QC_OUTPUT_FILE}")
panel_variant = "${PANEL_VARIANT}"

df = pd.read_csv(output)

raw_metric_cols = [
    "ncloc_raw",
    "bugs_raw",
    "vulnerabilities_raw",
    "code_smells_raw",
    "duplicated_lines_density_raw",
    "comment_lines_density_raw",
    "cognitive_complexity_raw",
    "technical_debt_raw",
]

required = {"repo_name", "time", "dataset_source"} | set(raw_metric_cols)
missing = required - set(df.columns)
if missing:
    raise SystemExit(f"Missing required columns in merged output: {sorted(missing)}")

df["sonarqube_all_raw_metrics_missing"] = df[raw_metric_cols].isna().all(axis=1).astype(int)

df["sonarqube_ncloc_zero"] = (
    df["ncloc_raw"].notna() & (df["ncloc_raw"] == 0)
).astype(int)

df["sonarqube_static_warnings_missing"] = (
    df[["bugs_raw", "vulnerabilities_raw", "code_smells_raw"]].isna().any(axis=1)
).astype(int)

df["sonarqube_duplicate_density_missing"] = df["duplicated_lines_density_raw"].isna().astype(int)
df["sonarqube_cognitive_complexity_missing"] = df["cognitive_complexity_raw"].isna().astype(int)

df["sonarqube_quality_outcomes_complete"] = (
    (df["sonarqube_static_warnings_missing"] == 0)
    & (df["sonarqube_duplicate_density_missing"] == 0)
    & (df["sonarqube_cognitive_complexity_missing"] == 0)
).astype(int)

df.to_csv(output, index=False)

qc = pd.read_csv(qc_output)

new_checks = pd.DataFrame([
    {"check": "run_py_2c_panel_variant", "value": panel_variant},
    {"check": "run_py_2c_rows", "value": len(df)},
    {"check": "run_py_2c_repos", "value": df["repo_name"].nunique()},
    {"check": "run_py_2c_treatment_rows", "value": int((df["dataset_source"] == "treatment").sum())},
    {"check": "run_py_2c_control_rows", "value": int((df["dataset_source"] == "control").sum())},
    {"check": "run_py_2c_treatment_repos", "value": df.loc[df["dataset_source"] == "treatment", "repo_name"].nunique()},
    {"check": "run_py_2c_control_repos", "value": df.loc[df["dataset_source"] == "control", "repo_name"].nunique()},
    {"check": "run_py_2c_sonarqube_all_raw_metrics_missing_rows", "value": int(df["sonarqube_all_raw_metrics_missing"].sum())},
    {"check": "run_py_2c_sonarqube_ncloc_zero_rows", "value": int(df["sonarqube_ncloc_zero"].sum())},
    {"check": "run_py_2c_static_warnings_missing_rows", "value": int(df["sonarqube_static_warnings_missing"].sum())},
    {"check": "run_py_2c_duplicate_density_missing_rows", "value": int(df["sonarqube_duplicate_density_missing"].sum())},
    {"check": "run_py_2c_cognitive_complexity_missing_rows", "value": int(df["sonarqube_cognitive_complexity_missing"].sum())},
    {"check": "run_py_2c_quality_outcomes_complete_rows", "value": int(df["sonarqube_quality_outcomes_complete"].sum())},
])

qc = qc[~qc["check"].isin(new_checks["check"])]
qc = pd.concat([qc, new_checks], ignore_index=True)
qc.to_csv(qc_output, index=False)

print("Updated output:", output)
print("Updated QC:", qc_output)
print()
print(new_checks.to_string(index=False))
PY

  echo
  echo "============================================================"
  echo "${RUN_PREFIX} completed successfully."
  echo "Completed:       $(date)"
  echo "Panel variant:   ${PANEL_VARIANT}"
  echo "Output file:     ${OUTPUT_FILE}"
  echo "QC output file:  ${QC_OUTPUT_FILE}"
  echo "Main output dir: ${MAIN_OUTPUT_DIR}"
  echo "Extra QC dir:    ${TMP_DIR}"
  echo "Log file:        ${LOG_FILE}"
  echo "============================================================"

} 2>&1 | tee "${LOG_FILE}"
#
# This wrapper is adapted from the logic of run9c-merge-sonarqube-panel.sh,
# but it does NOT call the existing JS/TS shell wrapper.