#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# run-py-1m: Summarize final Python matched DiD panels
# ============================================================
#
# Purpose:
#   Summarize the final Python matched DiD panels generated by run-py-1l.
#
# Current naming convention:
#   1. flexible
#      - Keeps treatments with 2 or 3 final controls.
#      - Uses observed repo-month rows only.
#
#   2. strict
#      - Keeps only treatments with exactly 3 final controls.
#      - Uses observed repo-month rows only.
#
#   3. flexible_window_driven
#      - Uses the flexible matched sample.
#      - Completes the Jan 2024-Aug 2025 window.
#
#   4. strict_window_driven
#      - Uses the strict matched sample.
#      - Completes the Jan 2024-Aug 2025 window.
#
# Primary focus:
#   repo_python/did_final/panel_event_matched_flexible.csv
#   repo_python/did_final/panel_event_matched_strict.csv
#
# Diagnostic / downstream focus:
#   repo_python/did_final/panel_event_matched_flexible_window_driven.csv
#   repo_python/did_final/panel_event_matched_strict_window_driven.csv
#
# Outputs:
#   repo_python/did_final/panel_qc_summary.csv
#   repo_python/did_final/panel_qc_by_source.csv
#   repo_python/did_final/panel_qc_paper_comparison.csv
#   repo_python/did_final/panel_qc_attrition_summary.csv
#   repo_python/did_final/panel_qc_dropped_by_strict.csv
#   repo_python/did_final/panel_qc_notes.md
# ============================================================

LOG_DIR="${LOG_DIR:-logs}"
RUN_TS="${RUN_TS:-$(date +%Y%m%d-%H%M%S)}"
LOG_FILE="${LOG_FILE:-${LOG_DIR}/run-py-1m_summarize_matched_panels_${RUN_TS}.log}"

PY_SCRIPT="${PY_SCRIPT:-proc_scripts/summarize_matched_panels.py}"

DID_DIR="${DID_DIR:-repo_python/did_final}"

FLEXIBLE_PANEL="${FLEXIBLE_PANEL:-${DID_DIR}/panel_event_matched_flexible.csv}"
STRICT_PANEL="${STRICT_PANEL:-${DID_DIR}/panel_event_matched_strict.csv}"
FLEXIBLE_WINDOW_DRIVEN_PANEL="${FLEXIBLE_WINDOW_DRIVEN_PANEL:-${DID_DIR}/panel_event_matched_flexible_window_driven.csv}"
STRICT_WINDOW_DRIVEN_PANEL="${STRICT_WINDOW_DRIVEN_PANEL:-${DID_DIR}/panel_event_matched_strict_window_driven.csv}"

OUTPUT_SUMMARY="${OUTPUT_SUMMARY:-${DID_DIR}/panel_qc_summary.csv}"
OUTPUT_BY_SOURCE="${OUTPUT_BY_SOURCE:-${DID_DIR}/panel_qc_by_source.csv}"
OUTPUT_PAPER_COMPARISON="${OUTPUT_PAPER_COMPARISON:-${DID_DIR}/panel_qc_paper_comparison.csv}"
OUTPUT_ATTRITION="${OUTPUT_ATTRITION:-${DID_DIR}/panel_qc_attrition_summary.csv}"
OUTPUT_DROPPED_BY_STRICT="${OUTPUT_DROPPED_BY_STRICT:-${DID_DIR}/panel_qc_dropped_by_strict.csv}"
OUTPUT_NOTES="${OUTPUT_NOTES:-${DID_DIR}/panel_qc_notes.md}"

TREATMENT_SAMPLE="${TREATMENT_SAMPLE:-repo_python/treatment_sample_main.csv}"
TREATMENT_MISSING_MATCHING="${TREATMENT_MISSING_MATCHING:-repo_python/treatment_missing_matching_main.csv}"
FINAL_COVERAGE="${FINAL_COVERAGE:-repo_python/control_pair_coverage_main_final_clean.csv}"
STRICT_COVERAGE="${STRICT_COVERAGE:-repo_python/control_pair_coverage_main_final_clean_1to3_only.csv}"
FINAL_CONTROLS="${FINAL_CONTROLS:-repo_python/control_clone_usable_repos_main_final_clean.csv}"

PAPER_TREATMENT_REPOS="${PAPER_TREATMENT_REPOS:-121}"
PAPER_CONTROL_REPOS="${PAPER_CONTROL_REPOS:-127}"
PAPER_TOTAL_OBSERVATIONS="${PAPER_TOTAL_OBSERVATIONS:-2461}"
PAPER_POST_TREATMENT_OBSERVATIONS="${PAPER_POST_TREATMENT_OBSERVATIONS:-582}"

mkdir -p "${LOG_DIR}" "${DID_DIR}"

echo "============================================================" | tee "${LOG_FILE}"
echo "run-py-1m: summarize final Python matched DiD panels" | tee -a "${LOG_FILE}"
echo "Timestamp:                         ${RUN_TS}" | tee -a "${LOG_FILE}"
echo "Python script:                     ${PY_SCRIPT}" | tee -a "${LOG_FILE}"
echo "DID dir:                           ${DID_DIR}" | tee -a "${LOG_FILE}"
echo "Flexible panel:                    ${FLEXIBLE_PANEL}" | tee -a "${LOG_FILE}"
echo "Strict panel:                      ${STRICT_PANEL}" | tee -a "${LOG_FILE}"
echo "Flexible window-driven panel:      ${FLEXIBLE_WINDOW_DRIVEN_PANEL}" | tee -a "${LOG_FILE}"
echo "Strict window-driven panel:        ${STRICT_WINDOW_DRIVEN_PANEL}" | tee -a "${LOG_FILE}"
echo "Output summary:                    ${OUTPUT_SUMMARY}" | tee -a "${LOG_FILE}"
echo "Output by-source:                  ${OUTPUT_BY_SOURCE}" | tee -a "${LOG_FILE}"
echo "Output paper comparison:           ${OUTPUT_PAPER_COMPARISON}" | tee -a "${LOG_FILE}"
echo "Output attrition:                  ${OUTPUT_ATTRITION}" | tee -a "${LOG_FILE}"
echo "Output dropped by strict:          ${OUTPUT_DROPPED_BY_STRICT}" | tee -a "${LOG_FILE}"
echo "Output notes:                      ${OUTPUT_NOTES}" | tee -a "${LOG_FILE}"
echo "Paper treatment repos:             ${PAPER_TREATMENT_REPOS}" | tee -a "${LOG_FILE}"
echo "Paper control repos:               ${PAPER_CONTROL_REPOS}" | tee -a "${LOG_FILE}"
echo "Paper total observations:          ${PAPER_TOTAL_OBSERVATIONS}" | tee -a "${LOG_FILE}"
echo "Paper post-treatment observations: ${PAPER_POST_TREATMENT_OBSERVATIONS}" | tee -a "${LOG_FILE}"
echo "Log file:                          ${LOG_FILE}" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
echo | tee -a "${LOG_FILE}"

for f in \
  "${PY_SCRIPT}" \
  "${FLEXIBLE_PANEL}" \
  "${STRICT_PANEL}" \
  "${FLEXIBLE_WINDOW_DRIVEN_PANEL}" \
  "${STRICT_WINDOW_DRIVEN_PANEL}" \
  "${TREATMENT_SAMPLE}" \
  "${FINAL_COVERAGE}" \
  "${STRICT_COVERAGE}" \
  "${FINAL_CONTROLS}"
do
  if [[ ! -f "${f}" ]]; then
    echo "ERROR: required file not found: ${f}" | tee -a "${LOG_FILE}"
    exit 1
  fi
done

echo "** Compile Python script" | tee -a "${LOG_FILE}"
echo "------------------------------------------------------------" | tee -a "${LOG_FILE}"
python -m py_compile "${PY_SCRIPT}" 2>&1 | tee -a "${LOG_FILE}"

echo | tee -a "${LOG_FILE}"
echo "** Run panel summarizer" | tee -a "${LOG_FILE}"
echo "------------------------------------------------------------" | tee -a "${LOG_FILE}"

CMD=(
  python "${PY_SCRIPT}"
  --flexible-panel "${FLEXIBLE_PANEL}"
  --strict-panel "${STRICT_PANEL}"
  --flexible-window-driven-panel "${FLEXIBLE_WINDOW_DRIVEN_PANEL}"
  --strict-window-driven-panel "${STRICT_WINDOW_DRIVEN_PANEL}"
  --output-summary "${OUTPUT_SUMMARY}"
  --output-by-source "${OUTPUT_BY_SOURCE}"
  --output-paper-comparison "${OUTPUT_PAPER_COMPARISON}"
  --output-attrition "${OUTPUT_ATTRITION}"
  --output-dropped-by-strict "${OUTPUT_DROPPED_BY_STRICT}"
  --output-notes "${OUTPUT_NOTES}"
  --treatment-sample "${TREATMENT_SAMPLE}"
  --treatment-missing-matching "${TREATMENT_MISSING_MATCHING}"
  --final-coverage "${FINAL_COVERAGE}"
  --strict-coverage "${STRICT_COVERAGE}"
  --final-controls "${FINAL_CONTROLS}"
  --paper-treatment-repos "${PAPER_TREATMENT_REPOS}"
  --paper-control-repos "${PAPER_CONTROL_REPOS}"
  --paper-total-observations "${PAPER_TOTAL_OBSERVATIONS}"
  --paper-post-treatment-observations "${PAPER_POST_TREATMENT_OBSERVATIONS}"
)

echo "${CMD[*]}" | tee -a "${LOG_FILE}"
echo | tee -a "${LOG_FILE}"

"${CMD[@]}" 2>&1 | tee -a "${LOG_FILE}"

echo | tee -a "${LOG_FILE}"
echo "** Output file check" | tee -a "${LOG_FILE}"
echo "------------------------------------------------------------" | tee -a "${LOG_FILE}"

for f in \
  "${OUTPUT_SUMMARY}" \
  "${OUTPUT_BY_SOURCE}" \
  "${OUTPUT_PAPER_COMPARISON}" \
  "${OUTPUT_ATTRITION}" \
  "${OUTPUT_DROPPED_BY_STRICT}" \
  "${OUTPUT_NOTES}"
do
  if [[ -f "${f}" ]]; then
    echo "Command: wc -l ${f}" | tee -a "${LOG_FILE}"
    wc -l "${f}" | tee -a "${LOG_FILE}"
  else
    echo "MISSING: ${f}" | tee -a "${LOG_FILE}"
  fi
done

echo | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
echo "run-py-1m completed successfully." | tee -a "${LOG_FILE}"
echo "Summary file:          ${OUTPUT_SUMMARY}" | tee -a "${LOG_FILE}"
echo "Paper comparison file: ${OUTPUT_PAPER_COMPARISON}" | tee -a "${LOG_FILE}"
echo "Notes file:            ${OUTPUT_NOTES}" | tee -a "${LOG_FILE}"
echo "Log file:              ${LOG_FILE}" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
#
# This wrapper is adapted from the logic of run8e2-summarize-jsts-panels.sh,
# but it does NOT call the existing JS/TS shell wrapper.
