#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# run8e2: Summarize final JS/TS matched DiD panels
# ============================================================
# This wrapper summarizes the four panel outputs generated by run8e:
#   1. main unbalanced
#   2. main window-completed
#   3. strict 1:3 unbalanced
#   4. strict 1:3 window-completed
# ============================================================

LOG_DIR="${LOG_DIR:-logs}"
RUN_TS="${RUN_TS:-$(date +%Y%m%d-%H%M%S)}"
LOG_FILE="${LOG_FILE:-${LOG_DIR}/run8e2_summarize_jsts_panels_${RUN_TS}.log}"

PY_SCRIPT="${PY_SCRIPT:-proc_scripts/summarize_jsts_panels.py}"
OUTPUT_FILE="${OUTPUT_FILE:-tmp_jsts_test/data/jsts_did_final/panel_qc_summary.csv}"

mkdir -p "${LOG_DIR}" "$(dirname "${OUTPUT_FILE}")"

echo "============================================================" | tee "${LOG_FILE}"
echo "run8e2: summarize final JS/TS matched DiD panels" | tee -a "${LOG_FILE}"
echo "Timestamp:     ${RUN_TS}" | tee -a "${LOG_FILE}"
echo "Python script: ${PY_SCRIPT}" | tee -a "${LOG_FILE}"
echo "Output file:   ${OUTPUT_FILE}" | tee -a "${LOG_FILE}"
echo "Log file:      ${LOG_FILE}" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
echo | tee -a "${LOG_FILE}"

if [[ ! -f "${PY_SCRIPT}" ]]; then
  echo "ERROR: Python script not found: ${PY_SCRIPT}" | tee -a "${LOG_FILE}"
  exit 1
fi

python "${PY_SCRIPT}" \
  --output "${OUTPUT_FILE}" \
  2>&1 | tee -a "${LOG_FILE}"

echo | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
echo "run8e2 completed successfully." | tee -a "${LOG_FILE}"
echo "Log file: ${LOG_FILE}" | tee -a "${LOG_FILE}"
echo "Output file: ${OUTPUT_FILE}" | tee -a "${LOG_FILE}"
echo "============================================================" | tee -a "${LOG_FILE}"
