#!/usr/bin/env python3
"""
Diagnose SonarQube rule/config/analyzer differences using the strongest matched subset.

This script reads the run-py-2b6 exact-commit row classification output and focuses on
rows where:
  1. paper and our pyv2 scan used the exact same commit hash, and
  2. paper and our pyv2 scan produced identical ncloc.

If warning-related metrics still differ in this subset, the remaining likely explanation
is SonarQube rule set, quality profile, analyzer/plugin version, or scanner configuration,
rather than commit selection or source-scope differences.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

ALL_METRICS = [
    "ncloc",
    "bugs",
    "vulnerabilities",
    "code_smells",
    "duplicated_lines_density",
    "comment_lines_density",
    "cognitive_complexity",
    "technical_debt",
    "static_analysis_warnings",
]

WARNING_METRICS = [
    "bugs",
    "vulnerabilities",
    "code_smells",
    "technical_debt",
    "static_analysis_warnings",
]

KEY_COLUMNS = [
    "source_group",
    "repo_name",
    "time",
    "commit_match_status",
    "paper_latest_commit",
    "our_latest_commit",
    "ncloc_scope_status",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Diagnose warning metric differences for exact-commit and ncloc-identical rows."
    )
    parser.add_argument(
        "--exact-commit-classification",
        required=True,
        help="CSV generated by run-py-2b6: sonarqube_exact_commit_row_classification.csv.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory for diagnostic outputs.",
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=1e-9,
        help="Numeric tolerance used to treat metric differences as identical.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=500,
        help="Number of largest-difference rows to save for detailed files.",
    )
    return parser.parse_args()


def read_csv_checked(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise SystemExit(f"ERROR: input file not found: {path}")

    df = pd.read_csv(path, low_memory=False)
    required = {"repo_name", "time", "ncloc_scope_status"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise SystemExit(f"ERROR: input file is missing required columns: {missing}")

    return df


def clean_key_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["repo_name"] = out["repo_name"].astype(str).str.strip()
    out["time"] = out["time"].astype(str).str.strip().str[:7]

    if "source_group" not in out.columns:
        out["source_group"] = "unknown"
    out["source_group"] = out["source_group"].astype(str).str.strip()

    if "commit_match_status" not in out.columns:
        out["commit_match_status"] = "exact_match"
    out["commit_match_status"] = out["commit_match_status"].astype(str).str.strip()

    out["ncloc_scope_status"] = out["ncloc_scope_status"].astype(str).str.strip()
    return out


def available_metrics(df: pd.DataFrame, metrics: Iterable[str]) -> list[str]:
    out: list[str] = []
    for metric in metrics:
        needed = [
            f"paper_value_{metric}",
            f"our_value_{metric}",
            f"diff_{metric}",
            f"abs_diff_{metric}",
        ]
        if all(col in df.columns for col in needed):
            out.append(metric)
    return out


def coerce_metric_columns(df: pd.DataFrame, metrics: Iterable[str]) -> pd.DataFrame:
    out = df.copy()
    for metric in metrics:
        for prefix in ["paper_value", "our_value", "diff", "abs_diff"]:
            col = f"{prefix}_{metric}"
            if col in out.columns:
                out[col] = pd.to_numeric(out[col], errors="coerce")
    return out


def summarize_metric(df: pd.DataFrame, metric: str, tolerance: float) -> dict:
    paper = pd.to_numeric(df[f"paper_value_{metric}"], errors="coerce")
    our = pd.to_numeric(df[f"our_value_{metric}"], errors="coerce")
    diff = pd.to_numeric(df[f"diff_{metric}"], errors="coerce")
    abs_diff = pd.to_numeric(df[f"abs_diff_{metric}"], errors="coerce")

    comparable = paper.notna() & our.notna()
    comp_diff = diff[comparable]
    comp_abs = abs_diff[comparable]

    comparable_count = int(comparable.sum())
    identical_rows = int((comp_abs <= tolerance).sum()) if comparable_count else 0
    different_rows = comparable_count - identical_rows
    positive_rows = int((comp_diff > tolerance).sum()) if comparable_count else 0
    negative_rows = int((comp_diff < -tolerance).sum()) if comparable_count else 0

    return {
        "metric": metric,
        "analysis_rows": int(len(df)),
        "comparable_non_null": comparable_count,
        "identical_rows": identical_rows,
        "different_rows": different_rows,
        "identical_share_among_non_null": (identical_rows / comparable_count) if comparable_count else np.nan,
        "different_share_among_non_null": (different_rows / comparable_count) if comparable_count else np.nan,
        "positive_diff_rows": positive_rows,
        "negative_diff_rows": negative_rows,
        "positive_diff_share": (positive_rows / comparable_count) if comparable_count else np.nan,
        "negative_diff_share": (negative_rows / comparable_count) if comparable_count else np.nan,
        "mean_diff": float(comp_diff.mean()) if comparable_count else np.nan,
        "median_diff": float(comp_diff.median()) if comparable_count else np.nan,
        "median_abs_diff": float(comp_abs.median()) if comparable_count else np.nan,
        "p90_abs_diff": float(comp_abs.quantile(0.90)) if comparable_count else np.nan,
        "p95_abs_diff": float(comp_abs.quantile(0.95)) if comparable_count else np.nan,
        "p99_abs_diff": float(comp_abs.quantile(0.99)) if comparable_count else np.nan,
        "max_abs_diff": float(comp_abs.max()) if comparable_count else np.nan,
        "paper_mean": float(paper[comparable].mean()) if comparable_count else np.nan,
        "our_mean": float(our[comparable].mean()) if comparable_count else np.nan,
    }


def summarize_by_group(df: pd.DataFrame, metric: str, group_col: str, tolerance: float) -> pd.DataFrame:
    rows = []
    for group_value, g in df.groupby(group_col, dropna=False):
        rec = summarize_metric(g, metric, tolerance)
        rec[group_col] = group_value
        rows.append(rec)
    if not rows:
        return pd.DataFrame()
    cols = [group_col] + [col for col in rows[0].keys() if col != group_col]
    return pd.DataFrame(rows)[cols]


def build_long_differences(df: pd.DataFrame, metrics: Iterable[str]) -> pd.DataFrame:
    keep_cols = [col for col in KEY_COLUMNS if col in df.columns]
    rows = []

    for metric in metrics:
        needed = [
            f"paper_value_{metric}",
            f"our_value_{metric}",
            f"diff_{metric}",
            f"abs_diff_{metric}",
        ]
        if not all(col in df.columns for col in needed):
            continue

        tmp = df[keep_cols + needed].copy()
        tmp.insert(len(keep_cols), "metric", metric)
        tmp = tmp.rename(
            columns={
                f"paper_value_{metric}": "paper_value",
                f"our_value_{metric}": "our_value",
                f"diff_{metric}": "diff",
                f"abs_diff_{metric}": "abs_diff",
            }
        )
        rows.append(tmp)

    if not rows:
        return pd.DataFrame()

    out = pd.concat(rows, ignore_index=True)
    return out.sort_values("abs_diff", ascending=False, na_position="last")


def save_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


def save_metric_slices(long_df: pd.DataFrame, output_dir: Path, top_n: int) -> None:
    targets = [
        ("static_analysis_warnings", "sonarqube_rule_config_large_static_warning_diffs.csv"),
        ("static_analysis_warnings", "sonarqube_rule_config_large_static_warning_negative_diffs.csv"),
        ("static_analysis_warnings", "sonarqube_rule_config_large_static_warning_positive_diffs.csv"),
        ("code_smells", "sonarqube_rule_config_large_code_smell_diffs.csv"),
        ("code_smells", "sonarqube_rule_config_large_code_smell_negative_diffs.csv"),
        ("code_smells", "sonarqube_rule_config_large_code_smell_positive_diffs.csv"),
        ("bugs", "sonarqube_rule_config_large_bug_diffs.csv"),
        ("vulnerabilities", "sonarqube_rule_config_large_vulnerability_diffs.csv"),
        ("technical_debt", "sonarqube_rule_config_large_technical_debt_diffs.csv"),
    ]

    for metric, filename in targets:
        if long_df.empty:
            out = pd.DataFrame()
        else:
            out = long_df[long_df["metric"].eq(metric)].copy()
            if "negative" in filename:
                out = out[out["diff"] < 0].sort_values("diff", ascending=True)
            elif "positive" in filename:
                out = out[out["diff"] > 0].sort_values("diff", ascending=False)
            else:
                out = out.sort_values("abs_diff", ascending=False)
            out = out.head(top_n)
        save_csv(out, output_dir / filename)


def build_repo_summary(df: pd.DataFrame, metrics: Iterable[str]) -> pd.DataFrame:
    rows = []
    for repo, g in df.groupby("repo_name"):
        rec = {
            "repo_name": repo,
            "source_group": ";".join(sorted(g["source_group"].dropna().astype(str).unique())) if "source_group" in g.columns else "unknown",
            "analysis_rows": int(len(g)),
        }
        for metric in metrics:
            abs_col = f"abs_diff_{metric}"
            diff_col = f"diff_{metric}"
            if abs_col not in g.columns or diff_col not in g.columns:
                continue
            rec[f"sum_abs_diff_{metric}"] = float(g[abs_col].sum(skipna=True))
            rec[f"median_abs_diff_{metric}"] = float(g[abs_col].median(skipna=True))
            rec[f"max_abs_diff_{metric}"] = float(g[abs_col].max(skipna=True))
            rec[f"sum_diff_{metric}"] = float(g[diff_col].sum(skipna=True))
        rows.append(rec)

    out = pd.DataFrame(rows)
    sort_col = "sum_abs_diff_static_analysis_warnings"
    if sort_col in out.columns:
        out = out.sort_values(sort_col, ascending=False)
    return out


def build_month_summary(df: pd.DataFrame, metrics: Iterable[str]) -> pd.DataFrame:
    rows = []
    for month, g in df.groupby("time"):
        rec = {
            "time": month,
            "analysis_rows": int(len(g)),
            "unique_repos": int(g["repo_name"].nunique()),
        }
        for metric in metrics:
            abs_col = f"abs_diff_{metric}"
            diff_col = f"diff_{metric}"
            if abs_col not in g.columns or diff_col not in g.columns:
                continue
            rec[f"median_abs_diff_{metric}"] = float(g[abs_col].median(skipna=True))
            rec[f"mean_diff_{metric}"] = float(g[diff_col].mean(skipna=True))
            rec[f"sum_abs_diff_{metric}"] = float(g[abs_col].sum(skipna=True))
        rows.append(rec)

    out = pd.DataFrame(rows)
    if not out.empty:
        out = out.sort_values("time")
    return out


def write_signal_summary(path: Path, subset: pd.DataFrame, all_input: pd.DataFrame, warning_summary: pd.DataFrame) -> None:
    rows = [
        {"metric": "input_rows", "value": int(len(all_input))},
        {"metric": "input_unique_repos", "value": int(all_input["repo_name"].nunique())},
        {"metric": "exact_commit_ncloc_identical_rows", "value": int(len(subset))},
        {"metric": "exact_commit_ncloc_identical_unique_repos", "value": int(subset["repo_name"].nunique())},
    ]

    if "source_group" in subset.columns:
        for group, count in subset["source_group"].value_counts(dropna=False).items():
            rows.append({"metric": f"source_group_rows_{group}", "value": int(count)})

    for _, r in warning_summary.iterrows():
        metric = r["metric"]
        rows.extend([
            {"metric": f"{metric}_identical_share", "value": r["identical_share_among_non_null"]},
            {"metric": f"{metric}_different_share", "value": r["different_share_among_non_null"]},
            {"metric": f"{metric}_median_abs_diff", "value": r["median_abs_diff"]},
            {"metric": f"{metric}_negative_diff_share", "value": r["negative_diff_share"]},
            {"metric": f"{metric}_positive_diff_share", "value": r["positive_diff_share"]},
        ])

    pd.DataFrame(rows).to_csv(path, index=False)


def write_notes(path: Path, subset: pd.DataFrame, warning_summary: pd.DataFrame, all_summary: pd.DataFrame) -> None:
    lines = [
        "# SonarQube rule/config/analyzer difference diagnosis",
        "",
        "This diagnostic uses the strongest comparable subset:",
        "- Same repository",
        "- Same month",
        "- Exact same latest_commit hash",
        "- Identical ncloc",
        "",
        "If warning metrics differ in this subset, the most likely explanation is SonarQube rule set, quality profile, analyzer/plugin version, or scanner configuration.",
        "",
        "## Input scope",
        f"- Exact-commit and ncloc-identical rows: {len(subset)}",
        f"- Unique repositories: {subset['repo_name'].nunique() if 'repo_name' in subset.columns else 'NA'}",
        "",
        "## Warning metric signal",
    ]

    for _, r in warning_summary.iterrows():
        lines.append(
            f"- {r['metric']}: identical_share={r['identical_share_among_non_null']:.4f}, "
            f"different_share={r['different_share_among_non_null']:.4f}, "
            f"median_abs_diff={r['median_abs_diff']}, "
            f"negative_share={r['negative_diff_share']:.4f}, "
            f"positive_share={r['positive_diff_share']:.4f}"
        )

    lines.extend([
        "",
        "## Interpretation",
        "- ncloc-identical rows reduce the likelihood that the difference is caused only by source inclusion/exclusion scope.",
        "- Large warning differences in this subset point to rule/config/analyzer/profile differences.",
        "- Negative diff means our pyv2 value is lower than the paper value.",
        "- Positive diff means our pyv2 value is higher than the paper value.",
        "",
        "## All metric summary",
    ])

    for _, r in all_summary.iterrows():
        lines.append(
            f"- {r['metric']}: identical_share={r['identical_share_among_non_null']:.4f}, "
            f"median_abs_diff={r['median_abs_diff']}, max_abs_diff={r['max_abs_diff']}"
        )

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    input_path = Path(args.exact_commit_classification)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = read_csv_checked(input_path)
    df = clean_key_columns(df)

    metrics = available_metrics(df, ALL_METRICS)
    if not metrics:
        raise SystemExit("ERROR: no metric value/diff columns were found in the input file.")

    df = coerce_metric_columns(df, metrics)

    # The input file is expected to contain exact-commit rows from run-py-2b6.
    # Keep the commit filter for safety in case the input is later broadened.
    subset = df[
        df["commit_match_status"].astype(str).eq("exact_match")
        & df["ncloc_scope_status"].astype(str).eq("ncloc_identical")
    ].copy()

    if subset.empty:
        raise SystemExit("ERROR: no exact_match + ncloc_identical rows found.")

    warning_metrics = [m for m in WARNING_METRICS if m in metrics]

    all_summary = pd.DataFrame([summarize_metric(subset, metric, args.tolerance) for metric in metrics])
    warning_summary = pd.DataFrame([summarize_metric(subset, metric, args.tolerance) for metric in warning_metrics])

    save_csv(all_summary, output_dir / "sonarqube_rule_config_all_metric_summary.csv")
    save_csv(warning_summary, output_dir / "sonarqube_rule_config_warning_metric_summary.csv")

    write_signal_summary(
        output_dir / "sonarqube_rule_config_signal_summary.csv",
        subset=subset,
        all_input=df,
        warning_summary=warning_summary,
    )

    by_source_parts = [summarize_by_group(subset, metric, "source_group", args.tolerance) for metric in warning_metrics]
    by_source = pd.concat([x for x in by_source_parts if not x.empty], ignore_index=True) if by_source_parts else pd.DataFrame()
    save_csv(by_source, output_dir / "sonarqube_rule_config_diff_by_source_group.csv")

    long_df = build_long_differences(subset, metrics)
    save_csv(long_df, output_dir / "sonarqube_rule_config_differences_long.csv")
    save_metric_slices(long_df, output_dir, args.top_n)

    repo_summary = build_repo_summary(subset, warning_metrics)
    save_csv(repo_summary, output_dir / "sonarqube_rule_config_diff_by_repo.csv")

    month_summary = build_month_summary(subset, warning_metrics)
    save_csv(month_summary, output_dir / "sonarqube_rule_config_diff_by_month.csv")

    keep_cols = [c for c in KEY_COLUMNS if c in subset.columns]
    metric_cols = []
    for metric in metrics:
        metric_cols.extend([f"paper_value_{metric}", f"our_value_{metric}", f"diff_{metric}", f"abs_diff_{metric}"])
    save_csv(subset[keep_cols + metric_cols], output_dir / "sonarqube_rule_config_row_subset.csv")

    write_notes(
        output_dir / "sonarqube_rule_config_diagnosis_notes.md",
        subset=subset,
        warning_summary=warning_summary,
        all_summary=all_summary,
    )

    print("Saved output directory:", output_dir)
    print()
    print("Rule/config diagnostic subset rows:", len(subset))
    print("Unique repos:", subset["repo_name"].nunique())
    print("Available metrics:", ", ".join(metrics))
    print()
    print("Warning metric summary:")
    print(warning_summary.to_string(index=False))
    print()
    print("Key outputs:")
    print(output_dir / "sonarqube_rule_config_signal_summary.csv")
    print(output_dir / "sonarqube_rule_config_warning_metric_summary.csv")
    print(output_dir / "sonarqube_rule_config_large_static_warning_negative_diffs.csv")
    print(output_dir / "sonarqube_rule_config_diagnosis_notes.md")


if __name__ == "__main__":
    main()
