#!/usr/bin/env python3
"""
Diagnose SonarQube metric differences for repo-month rows where paper and our
pyv2 scan used the exact same commit hash.

This script reads the run-py-2b5 commit-hash comparison output and focuses on
commit_match_status == exact_match. It separates likely source-scope differences
from likely rule/analyzer differences by checking whether ncloc differs for the
same commit.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

RAW_METRICS = [
    "ncloc",
    "bugs",
    "vulnerabilities",
    "code_smells",
    "duplicated_lines_density",
    "comment_lines_density",
    "cognitive_complexity",
    "technical_debt",
]

DERIVED_METRICS = ["static_analysis_warnings"]
METRICS = RAW_METRICS + DERIVED_METRICS

KEY_COLUMNS = [
    "source_group",
    "repo_name",
    "time",
    "commit_match_status",
    "paper_latest_commit",
    "our_latest_commit",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Diagnose metric differences for exact same commit rows."
    )
    parser.add_argument(
        "--commit-comparison",
        required=True,
        help="CSV generated by run-py-2b5: sonarqube_commit_hash_comparison.csv.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory for diagnostic outputs.",
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=1e-9,
        help="Numeric tolerance used to treat differences as identical.",
    )
    parser.add_argument(
        "--ncloc-close-abs",
        type=float,
        default=10.0,
        help="Absolute ncloc difference threshold treated as close scope.",
    )
    parser.add_argument(
        "--ncloc-close-rel",
        type=float,
        default=0.01,
        help="Relative ncloc difference threshold treated as close scope.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=500,
        help="Number of largest-difference rows to save for each detailed file.",
    )
    return parser.parse_args()


def read_csv_checked(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise SystemExit(f"ERROR: input file not found: {path}")
    df = pd.read_csv(path, low_memory=False)
    required = {"repo_name", "time", "commit_match_status"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise SystemExit(f"ERROR: input file is missing columns: {missing}")
    return df


def clean_key_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["repo_name"] = out["repo_name"].astype(str).str.strip()
    out["time"] = out["time"].astype(str).str.strip().str[:7]
    if "source_group" not in out.columns:
        out["source_group"] = "unknown"
    out["source_group"] = out["source_group"].astype(str).str.strip()
    return out


def find_metric_pair(df: pd.DataFrame, metric: str) -> tuple[str | None, str | None]:
    paper_candidates = [
        f"paper_{metric}",
        f"{metric}_paper",
        f"paper_value_{metric}",
    ]
    our_candidates = [
        f"our_{metric}",
        f"{metric}_our",
        f"our_value_{metric}",
    ]

    paper_col = next((c for c in paper_candidates if c in df.columns), None)
    our_col = next((c for c in our_candidates if c in df.columns), None)
    return paper_col, our_col


def ensure_static_analysis_warnings(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    paper_static, our_static = find_metric_pair(out, "static_analysis_warnings")
    if paper_static and our_static:
        return out

    paper_components = [find_metric_pair(out, m)[0] for m in ["bugs", "vulnerabilities", "code_smells"]]
    our_components = [find_metric_pair(out, m)[1] for m in ["bugs", "vulnerabilities", "code_smells"]]

    if all(paper_components) and all(our_components):
        out["paper_static_analysis_warnings"] = sum(
            pd.to_numeric(out[c], errors="coerce") for c in paper_components if c
        )
        out["our_static_analysis_warnings"] = sum(
            pd.to_numeric(out[c], errors="coerce") for c in our_components if c
        )

    return out


def add_metric_differences(df: pd.DataFrame, metrics: Iterable[str]) -> tuple[pd.DataFrame, list[str]]:
    out = df.copy()
    available: list[str] = []

    for metric in metrics:
        paper_col, our_col = find_metric_pair(out, metric)
        if not paper_col or not our_col:
            continue

        paper_value = pd.to_numeric(out[paper_col], errors="coerce")
        our_value = pd.to_numeric(out[our_col], errors="coerce")
        out[f"paper_value_{metric}"] = paper_value
        out[f"our_value_{metric}"] = our_value
        out[f"diff_{metric}"] = our_value - paper_value
        out[f"abs_diff_{metric}"] = out[f"diff_{metric}"].abs()
        available.append(metric)

    return out, available


def classify_ncloc_scope(df: pd.DataFrame, tolerance: float, close_abs: float, close_rel: float) -> pd.Series:
    if "abs_diff_ncloc" not in df.columns:
        return pd.Series("ncloc_missing", index=df.index)

    paper = pd.to_numeric(df.get("paper_value_ncloc"), errors="coerce")
    abs_diff = pd.to_numeric(df.get("abs_diff_ncloc"), errors="coerce")
    denom = paper.abs().replace(0, np.nan)
    rel_diff = abs_diff / denom

    status = pd.Series("ncloc_missing", index=df.index)
    comparable = abs_diff.notna()
    status.loc[comparable & (abs_diff <= tolerance)] = "ncloc_identical"
    status.loc[comparable & (abs_diff > tolerance) & ((abs_diff <= close_abs) | (rel_diff <= close_rel))] = "ncloc_close"
    status.loc[comparable & (abs_diff > close_abs) & (rel_diff > close_rel)] = "ncloc_different"
    return status


def summarize_metric(df: pd.DataFrame, metric: str, tolerance: float) -> dict:
    paper = pd.to_numeric(df[f"paper_value_{metric}"], errors="coerce")
    our = pd.to_numeric(df[f"our_value_{metric}"], errors="coerce")
    diff = pd.to_numeric(df[f"diff_{metric}"], errors="coerce")
    abs_diff = diff.abs()
    comparable = paper.notna() & our.notna()
    comp_abs = abs_diff[comparable]

    identical = int((comp_abs <= tolerance).sum())
    comparable_count = int(comparable.sum())

    return {
        "metric": metric,
        "exact_commit_rows": int(len(df)),
        "comparable_non_null": comparable_count,
        "identical_rows": identical,
        "identical_share_among_non_null": (identical / comparable_count) if comparable_count else np.nan,
        "mean_diff": float(diff[comparable].mean()) if comparable_count else np.nan,
        "median_diff": float(diff[comparable].median()) if comparable_count else np.nan,
        "median_abs_diff": float(comp_abs.median()) if comparable_count else np.nan,
        "p90_abs_diff": float(comp_abs.quantile(0.90)) if comparable_count else np.nan,
        "p95_abs_diff": float(comp_abs.quantile(0.95)) if comparable_count else np.nan,
        "p99_abs_diff": float(comp_abs.quantile(0.99)) if comparable_count else np.nan,
        "max_abs_diff": float(comp_abs.max()) if comparable_count else np.nan,
        "paper_mean": float(paper[comparable].mean()) if comparable_count else np.nan,
        "our_mean": float(our[comparable].mean()) if comparable_count else np.nan,
    }


def summarize_metric_by_group(df: pd.DataFrame, metric: str, group_col: str, tolerance: float) -> pd.DataFrame:
    rows = []
    for group_value, g in df.groupby(group_col, dropna=False):
        rec = summarize_metric(g, metric, tolerance)
        rec[group_col] = group_value
        rows.append(rec)
    if not rows:
        return pd.DataFrame()
    cols = [group_col] + [c for c in rows[0].keys() if c != group_col]
    return pd.DataFrame(rows)[cols]


def build_long_differences(df: pd.DataFrame, metrics: list[str]) -> pd.DataFrame:
    rows = []
    keep_cols = [c for c in KEY_COLUMNS if c in df.columns]
    if "ncloc_scope_status" in df.columns:
        keep_cols.append("ncloc_scope_status")

    for metric in metrics:
        needed = [f"paper_value_{metric}", f"our_value_{metric}", f"diff_{metric}", f"abs_diff_{metric}"]
        if not all(c in df.columns for c in needed):
            continue
        tmp = df[keep_cols + needed].copy()
        tmp.insert(len(keep_cols), "metric", metric)
        tmp = tmp.rename(
            columns={
                f"paper_value_{metric}": "paper_value",
                f"our_value_{metric}": "our_value",
                f"diff_{metric}": "diff",
                f"abs_diff_{metric}": "abs_diff",
            }
        )
        rows.append(tmp)

    if not rows:
        return pd.DataFrame()
    out = pd.concat(rows, ignore_index=True)
    return out.sort_values("abs_diff", ascending=False, na_position="last")


def save_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


def write_notes(
    path: Path,
    exact: pd.DataFrame,
    metric_summary: pd.DataFrame,
    by_ncloc_status: pd.DataFrame,
    available_metrics: list[str],
) -> None:
    ncloc_counts = exact.get("ncloc_scope_status", pd.Series(dtype=str)).value_counts(dropna=False)

    lines = [
        "# SonarQube exact-commit difference diagnosis",
        "",
        "This diagnostic focuses only on repo-month rows where the paper data and our pyv2 scan used the exact same latest_commit hash.",
        "",
        "## Input scope",
        f"- Exact commit rows: {len(exact)}",
        f"- Unique repos: {exact['repo_name'].nunique() if 'repo_name' in exact.columns else 'NA'}",
        f"- Available metrics: {', '.join(available_metrics)}",
        "",
        "## ncloc scope classification",
    ]

    if ncloc_counts.empty:
        lines.append("- ncloc scope status was not available.")
    else:
        for status, count in ncloc_counts.items():
            lines.append(f"- {status}: {int(count)}")

    lines.extend([
        "",
        "## Interpretation guide",
        "- If ncloc differs for the same commit, SonarQube source inclusion or exclusion scope likely differs.",
        "- If ncloc is identical or close but warning metrics differ, SonarQube rule set, analyzer version, quality profile, or scanner options likely differ.",
        "- Static analysis warnings are computed as bugs + vulnerabilities + code_smells when needed.",
        "",
        "## Key metric summary",
    ])

    show_metrics = ["static_analysis_warnings", "code_smells", "bugs", "vulnerabilities", "cognitive_complexity", "ncloc"]
    for metric in show_metrics:
        row = metric_summary[metric_summary["metric"].eq(metric)] if not metric_summary.empty else pd.DataFrame()
        if row.empty:
            continue
        r = row.iloc[0]
        lines.append(
            f"- {metric}: identical_share={r['identical_share_among_non_null']:.4f}, "
            f"median_abs_diff={r['median_abs_diff']}, max_abs_diff={r['max_abs_diff']}"
        )

    lines.append("")
    lines.append("## ncloc-status split")
    if by_ncloc_status.empty:
        lines.append("- No ncloc-status split was generated.")
    else:
        subset = by_ncloc_status[by_ncloc_status["metric"].isin(show_metrics)].copy()
        for _, r in subset.iterrows():
            lines.append(
                f"- {r['ncloc_scope_status']} / {r['metric']}: "
                f"n={int(r['comparable_non_null'])}, "
                f"identical_share={r['identical_share_among_non_null']:.4f}, "
                f"median_abs_diff={r['median_abs_diff']}"
            )

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    input_path = Path(args.commit_comparison)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = read_csv_checked(input_path)
    df = clean_key_columns(df)
    df = ensure_static_analysis_warnings(df)

    exact = df[df["commit_match_status"].astype(str).eq("exact_match")].copy()
    exact, available_metrics = add_metric_differences(exact, METRICS)

    if exact.empty:
        raise SystemExit("ERROR: no exact_match rows found in commit comparison input.")

    exact["ncloc_scope_status"] = classify_ncloc_scope(
        exact,
        tolerance=args.tolerance,
        close_abs=args.ncloc_close_abs,
        close_rel=args.ncloc_close_rel,
    )

    metric_summary = pd.DataFrame(
        [summarize_metric(exact, metric, args.tolerance) for metric in available_metrics]
    )
    save_csv(metric_summary, output_dir / "sonarqube_exact_commit_metric_summary.csv")

    by_ncloc_parts = []
    for metric in available_metrics:
        by_ncloc_parts.append(
            summarize_metric_by_group(exact, metric, "ncloc_scope_status", args.tolerance)
        )
    by_ncloc = pd.concat([x for x in by_ncloc_parts if not x.empty], ignore_index=True)
    save_csv(by_ncloc, output_dir / "sonarqube_exact_commit_metric_summary_by_ncloc_status.csv")

    by_group_parts = []
    for metric in available_metrics:
        by_group_parts.append(
            summarize_metric_by_group(exact, metric, "source_group", args.tolerance)
        )
    by_source_group = pd.concat([x for x in by_group_parts if not x.empty], ignore_index=True)
    save_csv(by_source_group, output_dir / "sonarqube_exact_commit_diff_by_source_group.csv")

    long_df = build_long_differences(exact, available_metrics)
    save_csv(long_df, output_dir / "sonarqube_exact_commit_differences_long.csv")

    key_cols = [c for c in KEY_COLUMNS if c in exact.columns]
    classification_cols = key_cols + ["ncloc_scope_status"]
    metric_cols = []
    for metric in available_metrics:
        metric_cols.extend([f"paper_value_{metric}", f"our_value_{metric}", f"diff_{metric}", f"abs_diff_{metric}"])
    save_csv(exact[classification_cols + metric_cols], output_dir / "sonarqube_exact_commit_row_classification.csv")

    def save_large(metric: str, filename: str) -> None:
        if long_df.empty:
            save_csv(pd.DataFrame(), output_dir / filename)
            return
        out = long_df[long_df["metric"].eq(metric)].head(args.top_n).copy()
        save_csv(out, output_dir / filename)

    save_large("static_analysis_warnings", "sonarqube_exact_commit_large_static_warning_diffs.csv")
    save_large("code_smells", "sonarqube_exact_commit_large_code_smell_diffs.csv")
    save_large("ncloc", "sonarqube_exact_commit_large_ncloc_diffs.csv")
    save_large("cognitive_complexity", "sonarqube_exact_commit_large_cognitive_complexity_diffs.csv")

    repo_rows = []
    for repo, g in exact.groupby("repo_name"):
        rec = {
            "repo_name": repo,
            "source_group": ";".join(sorted(g["source_group"].dropna().astype(str).unique())),
            "exact_commit_rows": len(g),
        }
        for metric in available_metrics:
            if f"abs_diff_{metric}" in g.columns:
                rec[f"sum_abs_diff_{metric}"] = float(g[f"abs_diff_{metric}"].sum(skipna=True))
                rec[f"median_abs_diff_{metric}"] = float(g[f"abs_diff_{metric}"].median(skipna=True))
                rec[f"max_abs_diff_{metric}"] = float(g[f"abs_diff_{metric}"].max(skipna=True))
        repo_rows.append(rec)
    repo_summary = pd.DataFrame(repo_rows)
    sort_col = "sum_abs_diff_static_analysis_warnings" if "sum_abs_diff_static_analysis_warnings" in repo_summary.columns else None
    if sort_col:
        repo_summary = repo_summary.sort_values(sort_col, ascending=False)
    save_csv(repo_summary, output_dir / "sonarqube_exact_commit_diff_by_repo.csv")

    month_rows = []
    for month, g in exact.groupby("time"):
        rec = {"time": month, "exact_commit_rows": len(g), "unique_repos": g["repo_name"].nunique()}
        for metric in available_metrics:
            if f"abs_diff_{metric}" in g.columns:
                rec[f"median_abs_diff_{metric}"] = float(g[f"abs_diff_{metric}"].median(skipna=True))
                rec[f"mean_diff_{metric}"] = float(g[f"diff_{metric}"].mean(skipna=True))
        month_rows.append(rec)
    month_summary = pd.DataFrame(month_rows).sort_values("time")
    save_csv(month_summary, output_dir / "sonarqube_exact_commit_diff_by_month.csv")

    write_notes(
        output_dir / "sonarqube_exact_commit_diagnosis_notes.md",
        exact=exact,
        metric_summary=metric_summary,
        by_ncloc_status=by_ncloc,
        available_metrics=available_metrics,
    )

    print("Saved output directory:", output_dir)
    print()
    print("Exact commit rows:", len(exact))
    print("Unique repos:", exact["repo_name"].nunique())
    print("Available metrics:", ", ".join(available_metrics))
    print()
    print("ncloc scope status counts:")
    print(exact["ncloc_scope_status"].value_counts(dropna=False).to_string())
    print()
    print("Metric summary:")
    print(metric_summary.to_string(index=False))
    print()
    print("Key outputs:")
    print(output_dir / "sonarqube_exact_commit_metric_summary.csv")
    print(output_dir / "sonarqube_exact_commit_metric_summary_by_ncloc_status.csv")
    print(output_dir / "sonarqube_exact_commit_large_static_warning_diffs.csv")
    print(output_dir / "sonarqube_exact_commit_large_ncloc_diffs.csv")


if __name__ == "__main__":
    main()
