#!/usr/bin/env python3
"""Summarize run9f Borusyak quality DiD outputs for paper tables and figures.

Inputs are generated by run9f_did_borusyak_quality.sh.

Main outputs:
  - borusyak_quality_static_effects_paper_ready.csv
  - borusyak_quality_static_effects_paper_ready.md
  - borusyak_quality_static_effects_wide.csv
  - borusyak_quality_dynamic_effects_percent.csv
  - borusyak_quality_dynamic_effects_plot_ready.csv
  - borusyak_quality_summary_notes.txt
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import pandas as pd


PANEL_ORDER = [
    "main_balanced",
    "main_unbalanced",
    "strict_1to3_balanced",
    "strict_1to3_unbalanced",
]

PANEL_LABELS = {
    "main_balanced": "Main balanced",
    "main_unbalanced": "Main unbalanced",
    "strict_1to3_balanced": "Strict 1:3 balanced",
    "strict_1to3_unbalanced": "Strict 1:3 unbalanced",
}

OUTCOME_ORDER = [
    "log_static_analysis_warnings",
    "log_duplicate_line_density",
    "log_code_complexity",
]

OUTCOME_LABELS = {
    "log_static_analysis_warnings": "Static analysis warnings",
    "log_duplicate_line_density": "Duplicate line density",
    "log_code_complexity": "Code complexity",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize run9f Borusyak quality DiD outputs."
    )
    parser.add_argument(
        "--input-dir",
        default="tmp_jsts_test/data/jsts_did_final/quality_did_borusyak",
        help="Directory containing run9f combined Borusyak outputs.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Directory for summarized outputs. Defaults to input-dir/summary.",
    )
    parser.add_argument(
        "--main-panel",
        default="main_balanced",
        choices=PANEL_ORDER,
        help="Main panel used for primary interpretation.",
    )
    return parser.parse_args()


def pct_from_log(x: float | int | None) -> float | None:
    if pd.isna(x):
        return None
    return (math.exp(float(x)) - 1.0) * 100.0


def p_value_from_estimate(row: pd.Series) -> float | None:
    estimate = row.get("estimate")
    std_error = row.get("std_error")

    if pd.isna(estimate) or pd.isna(std_error) or float(std_error) == 0.0:
        return None

    z = abs(float(estimate) / float(std_error))
    # normal two-sided p-value using erf
    p = 2.0 * (1.0 - 0.5 * (1.0 + math.erf(z / math.sqrt(2.0))))
    return p


def significance_from_ci(row: pd.Series) -> bool:
    low = row.get("conf_low")
    high = row.get("conf_high")

    if pd.isna(low) or pd.isna(high):
        return False

    return (float(low) > 0.0) or (float(high) < 0.0)


def stars_from_p(p: float | None) -> str:
    if p is None or pd.isna(p):
        return ""
    if p < 0.001:
        return "***"
    if p < 0.01:
        return "**"
    if p < 0.05:
        return "*"
    if p < 0.10:
        return "+"
    return ""


def format_pct(value: float | None, digits: int = 1) -> str:
    if value is None or pd.isna(value):
        return ""
    return f"{value:.{digits}f}%"


def format_effect(row: pd.Series) -> str:
    pct = row.get("percent_change")
    low = row.get("conf_low_percent")
    high = row.get("conf_high_percent")
    stars = row.get("stars", "")

    if pd.isna(pct):
        return ""

    return (
        f"{pct:.1f}%{stars} "
        f"[{low:.1f}%, {high:.1f}%]"
    )


def require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")


def load_static(input_dir: Path) -> pd.DataFrame:
    path = input_dir / "borusyak_quality_static_effects_all.csv"
    require_file(path)

    df = pd.read_csv(path)

    required = {
        "panel",
        "outcome",
        "estimate",
        "std_error",
        "conf_low",
        "conf_high",
    }
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Static effects missing columns: {sorted(missing)}")

    return df


def load_dynamic(input_dir: Path) -> pd.DataFrame:
    path = input_dir / "borusyak_quality_dynamic_effects_all.csv"
    require_file(path)

    df = pd.read_csv(path)

    required = {
        "panel",
        "outcome",
        "time",
        "estimate",
        "std_error",
        "conf_low",
        "conf_high",
    }
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Dynamic effects missing columns: {sorted(missing)}")

    return df


def load_optional(input_dir: Path, filename: str) -> pd.DataFrame:
    path = input_dir / filename
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def prepare_static(static_df: pd.DataFrame) -> pd.DataFrame:
    df = static_df.copy()

    for col in ["estimate", "std_error", "conf_low", "conf_high", "p_value"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df["panel_label"] = df["panel"].map(PANEL_LABELS).fillna(df["panel"])
    df["outcome_label"] = df["outcome"].map(OUTCOME_LABELS).fillna(df["outcome"])

    df["percent_change"] = df["estimate"].apply(pct_from_log)
    df["conf_low_percent"] = df["conf_low"].apply(pct_from_log)
    df["conf_high_percent"] = df["conf_high"].apply(pct_from_log)

    if "p_value" not in df.columns:
        df["p_value"] = pd.NA

    computed_p = df.apply(p_value_from_estimate, axis=1)
    df["p_value_computed"] = computed_p

    df["p_value_final"] = df["p_value"]
    df.loc[df["p_value_final"].isna(), "p_value_final"] = df.loc[
        df["p_value_final"].isna(), "p_value_computed"
    ]

    df["ci_excludes_zero"] = df.apply(significance_from_ci, axis=1)
    df["stars"] = df["p_value_final"].apply(stars_from_p)
    df["effect_percent_ci"] = df.apply(format_effect, axis=1)

    df["panel_order"] = df["panel"].map(
        {panel: i for i, panel in enumerate(PANEL_ORDER)}
    )
    df["outcome_order"] = df["outcome"].map(
        {outcome: i for i, outcome in enumerate(OUTCOME_ORDER)}
    )

    df = df.sort_values(["panel_order", "outcome_order"]).reset_index(drop=True)

    return df


def prepare_dynamic(dynamic_df: pd.DataFrame) -> pd.DataFrame:
    df = dynamic_df.copy()

    for col in ["time", "estimate", "std_error", "conf_low", "conf_high", "p_value"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df["panel_label"] = df["panel"].map(PANEL_LABELS).fillna(df["panel"])
    df["outcome_label"] = df["outcome"].map(OUTCOME_LABELS).fillna(df["outcome"])

    df["percent_change"] = df["estimate"].apply(pct_from_log)
    df["conf_low_percent"] = df["conf_low"].apply(pct_from_log)
    df["conf_high_percent"] = df["conf_high"].apply(pct_from_log)

    if "p_value" not in df.columns:
        df["p_value"] = pd.NA

    computed_p = df.apply(p_value_from_estimate, axis=1)
    df["p_value_computed"] = computed_p

    df["p_value_final"] = df["p_value"]
    df.loc[df["p_value_final"].isna(), "p_value_final"] = df.loc[
        df["p_value_final"].isna(), "p_value_computed"
    ]

    df["ci_excludes_zero"] = df.apply(significance_from_ci, axis=1)
    df["stars"] = df["p_value_final"].apply(stars_from_p)

    df["panel_order"] = df["panel"].map(
        {panel: i for i, panel in enumerate(PANEL_ORDER)}
    )
    df["outcome_order"] = df["outcome"].map(
        {outcome: i for i, outcome in enumerate(OUTCOME_ORDER)}
    )

    df = df.sort_values(["panel_order", "outcome_order", "time"]).reset_index(
        drop=True
    )

    return df


def build_static_wide(static_ready: pd.DataFrame) -> pd.DataFrame:
    keep = static_ready[
        [
            "panel",
            "panel_label",
            "outcome",
            "outcome_label",
            "effect_percent_ci",
        ]
    ].copy()

    wide = keep.pivot_table(
        index=["panel", "panel_label"],
        columns="outcome_label",
        values="effect_percent_ci",
        aggfunc="first",
    ).reset_index()

    ordered_outcome_labels = [OUTCOME_LABELS[o] for o in OUTCOME_ORDER]
    existing = [c for c in ordered_outcome_labels if c in wide.columns]
    wide = wide[["panel", "panel_label"] + existing]

    wide["panel_order"] = wide["panel"].map(
        {panel: i for i, panel in enumerate(PANEL_ORDER)}
    )
    wide = wide.sort_values("panel_order").drop(columns=["panel_order"])

    return wide


def build_main_panel_table(static_ready: pd.DataFrame, main_panel: str) -> pd.DataFrame:
    main = static_ready[static_ready["panel"] == main_panel].copy()

    cols = [
        "outcome_label",
        "estimate",
        "std_error",
        "conf_low",
        "conf_high",
        "percent_change",
        "conf_low_percent",
        "conf_high_percent",
        "p_value_final",
        "stars",
        "ci_excludes_zero",
        "effect_percent_ci",
    ]

    return main[cols]


def markdown_cell(value: object) -> str:
    """Format one markdown table cell without requiring tabulate."""
    if pd.isna(value):
        return ""
    text = str(value)
    text = text.replace("\n", "<br>")
    text = text.replace("|", "\\|")
    return text


def write_markdown_table(df: pd.DataFrame, path: Path) -> None:
    """Write a markdown table without pandas.to_markdown/tabulate."""
    cols = list(df.columns)

    lines = []
    lines.append("| " + " | ".join(markdown_cell(c) for c in cols) + " |")
    lines.append("| " + " | ".join("---" for _ in cols) + " |")

    for _, row in df.iterrows():
        lines.append(
            "| " + " | ".join(markdown_cell(row[c]) for c in cols) + " |"
        )

    path.write_text("\n".join(lines) + "\n")


def build_notes(
    static_ready: pd.DataFrame,
    main_panel: str,
    errors_df: pd.DataFrame,
) -> str:
    lines: list[str] = []

    lines.append("Borusyak Quality DiD Summary")
    lines.append("=" * 32)
    lines.append("")
    lines.append(f"Main panel: {main_panel}")
    lines.append("")
    lines.append("Static effects are log-point estimates converted to percent changes:")
    lines.append("percent_change = (exp(estimate) - 1) * 100")
    lines.append("")

    main = static_ready[static_ready["panel"] == main_panel].copy()

    for _, row in main.iterrows():
        lines.append(
            f"- {row['outcome_label']}: "
            f"{format_pct(row['percent_change'])} "
            f"[{format_pct(row['conf_low_percent'])}, "
            f"{format_pct(row['conf_high_percent'])}], "
            f"CI excludes zero: {bool(row['ci_excludes_zero'])}"
        )

    lines.append("")
    lines.append("Robustness pattern:")
    for outcome in OUTCOME_ORDER:
        sub = static_ready[static_ready["outcome"] == outcome]
        positive = int((sub["estimate"] > 0).sum())
        significant = int(sub["ci_excludes_zero"].sum())
        total = len(sub)
        lines.append(
            f"- {OUTCOME_LABELS[outcome]}: positive in {positive}/{total} panels; "
            f"CI excludes zero in {significant}/{total} panels."
        )

    lines.append("")
    if errors_df.empty:
        lines.append("Model errors: none recorded.")
    else:
        lines.append(f"Model errors: {len(errors_df)} rows recorded.")
        for _, row in errors_df.head(20).iterrows():
            lines.append(f"- {row.to_dict()}")

    lines.append("")
    lines.append("Recommended interpretation:")
    code = static_ready[static_ready["outcome"] == "log_code_complexity"]
    if len(code) and int(code["ci_excludes_zero"].sum()) == len(code):
        lines.append(
            "Code complexity is the most robust quality outcome: all panels show "
            "positive estimates with confidence intervals excluding zero."
        )
    else:
        lines.append(
            "Code complexity remains the primary outcome to inspect, but not all "
            "robustness panels have confidence intervals excluding zero."
        )

    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir) if args.output_dir else input_dir / "summary"
    output_dir.mkdir(parents=True, exist_ok=True)

    static_df = load_static(input_dir)
    dynamic_df = load_dynamic(input_dir)
    checks_df = load_optional(input_dir, "borusyak_quality_panel_checks_all.csv")
    input_summary_df = load_optional(input_dir, "borusyak_quality_input_summary_all.csv")
    errors_df = load_optional(input_dir, "borusyak_quality_errors_all.csv")

    static_ready = prepare_static(static_df)
    dynamic_ready = prepare_dynamic(dynamic_df)

    static_wide = build_static_wide(static_ready)
    main_table = build_main_panel_table(static_ready, args.main_panel)

    static_ready_path = output_dir / "borusyak_quality_static_effects_paper_ready.csv"
    static_wide_path = output_dir / "borusyak_quality_static_effects_wide.csv"
    main_table_path = output_dir / "borusyak_quality_main_panel_table.csv"
    main_table_md_path = output_dir / "borusyak_quality_main_panel_table.md"
    dynamic_percent_path = output_dir / "borusyak_quality_dynamic_effects_percent.csv"
    dynamic_plot_path = output_dir / "borusyak_quality_dynamic_effects_plot_ready.csv"
    notes_path = output_dir / "borusyak_quality_summary_notes.txt"

    static_ready.to_csv(static_ready_path, index=False)
    static_wide.to_csv(static_wide_path, index=False)
    main_table.to_csv(main_table_path, index=False)
    write_markdown_table(main_table, main_table_md_path)

    dynamic_ready.to_csv(dynamic_percent_path, index=False)
    dynamic_ready[
        [
            "panel",
            "panel_label",
            "outcome",
            "outcome_label",
            "time",
            "percent_change",
            "conf_low_percent",
            "conf_high_percent",
            "ci_excludes_zero",
            "stars",
        ]
    ].to_csv(dynamic_plot_path, index=False)

    notes = build_notes(static_ready, args.main_panel, errors_df)
    notes_path.write_text(notes)

    if not checks_df.empty:
        checks_df.to_csv(output_dir / "borusyak_quality_panel_checks_copy.csv", index=False)

    if not input_summary_df.empty:
        input_summary_df.to_csv(
            output_dir / "borusyak_quality_input_summary_copy.csv",
            index=False,
        )

    if not errors_df.empty:
        errors_df.to_csv(output_dir / "borusyak_quality_errors_copy.csv", index=False)

    print("Saved summary outputs to:", output_dir)
    print()
    print("Main panel table:")
    print(main_table.to_string(index=False))
    print()
    print("Static effects wide:")
    print(static_wide.to_string(index=False))
    print()
    print("Notes:")
    print(notes)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
