#!/usr/bin/env python3
"""Collect monthly physical lines added in tracked Python files.

This is the self-contained collection stage for run-x-b02-v4. It reproduces
repository-month activity from a frozen repository history tip and computes the
Python-only flow outcome used by the later DiD analysis.

Measurement contract
--------------------
- Commit universe: commits reachable from a repository-level history tip SHA
  resolved once from the configured history ref at repository start.
- Month assignment: Git committer timestamp in the configured timezone.
- Broad outcome: compare every non-root commit with its first parent, including
  merge commits for backward compatibility with v3.
- Cleaned outcomes: exclude merge commits while retaining reachable branch
  commits in their original committer month.
- Root commits: count the commit, but exclude root additions from line metrics.
- Python scope: post-change regular files whose path ends in .py and whose
  directory is not excluded by the configured run-x-b02 policy.
- Source scope: exclude explicit vendor and conservative generated path markers;
  tests remain in the primary source outcome and are excluded in a sensitivity
  outcome only.
- Metric: physical added lines reported by Git numstat. Blank lines, comments,
  and docstrings are included because this is a development-flow metric.
- No-commit months receive zero activity. Monthly activity is never carried
  forward.

The script never checks out, resets, cleans, fetches, pulls, or modifies a
repository clone.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import logging
import math
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Optional, Sequence
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import numpy as np
import pandas as pd


IMPLEMENTATION_VERSION = "v4"
COUNT_BACKEND = "git_first_parent_numstat_python_multi_outcome"
EXPECTED_DATASET_SOURCES = {"treatment", "control"}
VALID_PYTHON_MODES = {"100644", "100755"}
EXCLUDED_DIRECTORY_NAMES = {
    ".git",
    ".scannerwork",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    "node_modules",
    "dist",
    "build",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    "coverage",
    ".next",
    ".nuxt",
}
VENDOR_DIRECTORY_NAMES = {"vendor", "_vendor"}
GENERATED_API_DIRECTORY_NAMES = {
    "openapi_client",
    "swagger_client",
    "generated_client",
    "generated_api",
    "autogenerated",
    "auto_generated",
}
TEST_DIRECTORY_NAMES = {"test", "tests", "testing", "testsuite", "test_suite"}
REQUIRED_PANEL_COLUMNS = {
    "repo_id",
    "repo_name",
    "dataset_source",
    "time",
    "time_index",
    "commits",
    "lines_added",
    "latest_commit_effective",
    "clone_path",
}
OUTCOME_NAMES = [
    "lines_added_py_all",
    "lines_added_py_no_merge",
    "lines_added_py_source",
    "lines_added_py_source_no_tests",
]
LOG_OUTCOME_NAMES = [f"log_{name}" for name in OUTCOME_NAMES]

REPO_MONTH_COLUMNS = [
    "repo_id",
    "repo_name",
    "dataset_source",
    "time",
    "time_index",
    "commits_original",
    "commits_recomputed",
    "commits_match_original",
    "lines_added_repo_original",
    "log_lines_added_repo_original",
    "lines_added_repo_recomputed",
    "lines_added_repo_match_original",
    "lines_removed_repo_recomputed",
    "lines_added_py_total",
    "lines_added_py",
    "log_lines_added_py",
    *OUTCOME_NAMES,
    *LOG_OUTCOME_NAMES,
    "python_commits_touched",
    "python_commits_with_added_lines",
    "python_file_change_events",
    "python_unique_paths_changed",
    "python_commits_touched_no_merge",
    "python_commits_with_added_lines_no_merge",
    "python_file_change_events_no_merge",
    "python_unique_paths_changed_no_merge",
    "python_commits_touched_source",
    "python_commits_with_added_lines_source",
    "python_file_change_events_source",
    "python_unique_paths_changed_source",
    "python_commits_touched_source_no_tests",
    "python_commits_with_added_lines_source_no_tests",
    "python_file_change_events_source_no_tests",
    "python_unique_paths_changed_source_no_tests",
    "latest_commit_recomputed",
    "latest_commit_effective",
    "analysis_tip_commit",
    "analysis_history_ref",
    "analysis_timezone",
    "count_backend",
    "history_complete",
    "python_added_lines_complete",
    "reference_reconciliation_complete",
    "reference_reconciliation_status",
    "history_reconciliation_complete",
    "python_added_lines_available",
    "python_added_lines_status",
    "issue_count",
]
COMMIT_COLUMNS = [
    "repo_name",
    "dataset_source",
    "commit_sha",
    "first_parent_sha",
    "commit_time_epoch",
    "commit_time_local",
    "commit_month",
    "parent_count",
    "is_merge_commit",
    "is_root_commit",
    "lines_added_repo_recomputed",
    "lines_removed_repo_recomputed",
    "lines_added_py",
    "lines_removed_py",
    *OUTCOME_NAMES,
    "included_in_py_all",
    "included_in_py_no_merge",
    "included_in_py_source",
    "included_in_py_source_no_tests",
    "python_file_change_events",
    "python_unique_paths_changed",
    "python_file_change_events_no_merge",
    "python_unique_paths_changed_no_merge",
    "python_file_change_events_source",
    "python_unique_paths_changed_source",
    "python_file_change_events_source_no_tests",
    "python_unique_paths_changed_source_no_tests",
    "python_touched",
    "python_has_added_lines",
    "python_touched_no_merge",
    "python_has_added_lines_no_merge",
    "python_touched_source",
    "python_has_added_lines_source",
    "python_touched_source_no_tests",
    "python_has_added_lines_source_no_tests",
    "diff_status",
    "python_metric_complete",
    "runtime_seconds",
]
FILE_COLUMNS = [
    "repo_name",
    "dataset_source",
    "commit_sha",
    "commit_month",
    "is_merge_commit",
    "change_status",
    "old_mode",
    "new_mode",
    "old_path",
    "new_path",
    "post_path",
    "path_is_python",
    "post_mode_is_regular_python",
    "is_binary",
    "is_vendor_path",
    "is_generated_api_client",
    "is_generated_resource_module",
    "is_generated_path",
    "is_test_path",
    "source_exclusion_reason",
    "lines_added",
    "lines_removed",
    "included_in_python_metric",
    "included_in_py_all",
    "included_in_py_no_merge",
    "included_in_py_source",
    "included_in_py_source_no_tests",
    "file_status",
]
ISSUE_COLUMNS = [
    "repo_name",
    "dataset_source",
    "time",
    "commit_sha",
    "path",
    "stage",
    "error_type",
    "error_message",
    "resolution_status",
]
RECONCILIATION_COLUMNS = [
    "repo_id",
    "repo_name",
    "dataset_source",
    "time",
    "commits_original",
    "commits_recomputed",
    "commits_delta",
    "lines_added_repo_original",
    "lines_added_repo_recomputed",
    "lines_added_delta",
    "commits_match_original",
    "lines_added_repo_match_original",
    "history_complete",
    "python_added_lines_complete",
    "reference_reconciliation_complete",
    "reference_reconciliation_status",
    "history_reconciliation_complete",
    "analysis_tip_commit",
    "analysis_history_ref",
    "analysis_timezone",
]


class StageError(RuntimeError):
    """Represent a stage-specific processing failure."""

    def __init__(self, stage: str, message: str) -> None:
        super().__init__(message)
        self.stage = stage
        self.message = message


@dataclass(frozen=True)
class RawChange:
    """One path-level change from Git raw diff output."""

    status: str
    old_mode: str
    new_mode: str
    old_path: str
    new_path: str


@dataclass(frozen=True)
class NumstatChange:
    """One path-level line-count record from Git numstat output."""

    old_path: str
    new_path: str
    added: Optional[int]
    removed: Optional[int]
    is_binary: bool


@dataclass(frozen=True)
class CommitInfo:
    """One commit assigned to a requested repository-month."""

    commit_sha: str
    parents: tuple[str, ...]
    commit_time_epoch: int
    commit_time_local: str
    commit_month: str

    @property
    def first_parent_sha(self) -> str:
        return self.parents[0] if self.parents else ""

    @property
    def is_root_commit(self) -> bool:
        return not self.parents

    @property
    def is_merge_commit(self) -> bool:
        return len(self.parents) > 1


def clean_text(value: Any) -> str:
    """Return a trimmed string and normalize missing values to empty."""
    if value is None or pd.isna(value):
        return ""
    return str(value).strip()


def sha256_text(value: str) -> str:
    """Return a stable SHA-256 digest for text."""
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def stable_repo_key(dataset_source: str, repo_name: str) -> str:
    """Create a filesystem-safe repository cache key."""
    readable = re.sub(r"[^A-Za-z0-9._-]+", "_", f"{dataset_source}__{repo_name}")
    digest = sha256_text(f"{dataset_source}|{repo_name.casefold()}")[:16]
    return f"{readable}__{digest}"


def save_dataframe(df: pd.DataFrame, path: Path, columns: Optional[Sequence[str]] = None) -> None:
    """Write a CSV atomically, including a header for an empty table."""
    target = path.expanduser().resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    output = df.copy()
    if columns is not None:
        for column in columns:
            if column not in output.columns:
                output[column] = pd.NA
        output = output[list(columns)]
    temporary = target.with_suffix(target.suffix + ".tmp")
    output.to_csv(temporary, index=False)
    temporary.replace(target)


def write_json(payload: dict[str, Any], path: Path) -> None:
    """Write JSON atomically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    temporary.replace(path)


def run_command(
    command: Sequence[str],
    *,
    timeout: int,
    text: bool = False,
) -> subprocess.CompletedProcess[Any]:
    """Run a read-only external command and capture output."""
    logging.debug("Running command: %s", " ".join(command))
    return subprocess.run(
        list(command),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        timeout=timeout,
        text=text,
    )


def git_text(clone_path: Path, args: Sequence[str], timeout: int) -> str:
    """Run Git and return text output or raise a stage error."""
    process = run_command(["git", "-C", str(clone_path), *args], timeout=timeout, text=True)
    if process.returncode != 0:
        raise StageError("git", process.stderr.strip() or "Git command failed")
    return process.stdout


def git_bytes(clone_path: Path, args: Sequence[str], timeout: int) -> bytes:
    """Run Git and return byte output or raise a stage error."""
    process = run_command(["git", "-C", str(clone_path), *args], timeout=timeout, text=False)
    if process.returncode != 0:
        message = process.stderr.decode("utf-8", errors="replace").strip()
        raise StageError("git", message or "Git command failed")
    return process.stdout


def validate_clone(clone_path: Path, timeout: int) -> tuple[bool, str]:
    """Validate that a clone path is a readable Git repository."""
    if not clone_path.exists():
        return False, "clone_path_missing"
    try:
        git_dir = git_text(clone_path, ["rev-parse", "--git-dir"], timeout).strip()
    except Exception as exc:
        return False, f"not_git_repository:{exc}"
    return bool(git_dir), "ready"


def commit_exists(clone_path: Path, commit_sha: str, timeout: int) -> bool:
    """Return whether a commit object exists locally."""
    process = run_command(
        ["git", "-C", str(clone_path), "cat-file", "-e", f"{commit_sha}^{{commit}}"],
        timeout=timeout,
    )
    return process.returncode == 0


def commit_is_ancestor(clone_path: Path, ancestor: str, descendant: str, timeout: int) -> bool:
    """Return whether one commit is an ancestor of another."""
    process = run_command(
        ["git", "-C", str(clone_path), "merge-base", "--is-ancestor", ancestor, descendant],
        timeout=timeout,
    )
    return process.returncode == 0


def path_is_python(path_text: str) -> bool:
    """Apply the broad run-x-b02 Python path policy."""
    if not path_text:
        return False
    path = PurePosixPath(path_text)
    if not path.name.casefold().endswith(".py"):
        return False
    return not any(part.casefold() in EXCLUDED_DIRECTORY_NAMES for part in path.parts[:-1])


def classify_python_path(path_text: str) -> dict[str, Any]:
    """Classify conservative vendor, generated, and test path patterns."""
    path = PurePosixPath(path_text)
    parts = [part.casefold() for part in path.parts]
    directory_parts = parts[:-1]
    filename = path.name.casefold()

    is_vendor = any(part in VENDOR_DIRECTORY_NAMES for part in directory_parts)
    is_generated_api = any(part in GENERATED_API_DIRECTORY_NAMES for part in directory_parts)
    is_generated_resource = (
        filename.endswith("_rc.py")
        or filename in {"resources_rc.py", "resource_rc.py"}
        or (filename == "resources.py" and "resources" in directory_parts)
    )
    is_test = (
        any(part in TEST_DIRECTORY_NAMES for part in directory_parts)
        or filename.startswith("test_")
        or filename.endswith("_test.py")
    )

    reasons: list[str] = []
    if is_vendor:
        reasons.append("vendor_path")
    if is_generated_api:
        reasons.append("generated_api_client")
    if is_generated_resource:
        reasons.append("generated_resource_module")
    return {
        "is_vendor_path": int(is_vendor),
        "is_generated_api_client": int(is_generated_api),
        "is_generated_resource_module": int(is_generated_resource),
        "is_generated_path": int(is_generated_api or is_generated_resource),
        "is_test_path": int(is_test),
        "source_exclusion_reason": "|".join(reasons),
    }


def parse_raw_diff(payload: bytes) -> list[RawChange]:
    """Parse `git diff-tree --raw -z` records."""
    parts = payload.split(b"\0")
    output: list[RawChange] = []
    index = 0
    while index < len(parts):
        header = parts[index]
        index += 1
        if not header:
            continue
        header_text = header.decode("utf-8", errors="surrogateescape")
        fields = header_text.split()
        if len(fields) < 5 or not fields[0].startswith(":"):
            raise ValueError(f"Unexpected raw diff header: {header_text!r}")
        old_mode = fields[0][1:]
        new_mode = fields[1]
        status = fields[4]
        code = status[:1]
        if index >= len(parts):
            raise ValueError("Raw diff path is missing")
        first_path = parts[index].decode("utf-8", errors="surrogateescape")
        index += 1
        if code in {"R", "C"}:
            if index >= len(parts):
                raise ValueError("Raw rename/copy destination path is missing")
            second_path = parts[index].decode("utf-8", errors="surrogateescape")
            index += 1
            old_path, new_path = first_path, second_path
        elif code == "A":
            old_path, new_path = "", first_path
        elif code == "D":
            old_path, new_path = first_path, ""
        else:
            old_path, new_path = first_path, first_path
        output.append(
            RawChange(
                status=status,
                old_mode=old_mode,
                new_mode=new_mode,
                old_path=old_path,
                new_path=new_path,
            )
        )
    return output


def parse_numstat_z(payload: bytes) -> list[NumstatChange]:
    """Parse `git diff --numstat -z` including rename/copy records."""
    parts = payload.split(b"\0")
    output: list[NumstatChange] = []
    index = 0
    while index < len(parts):
        record = parts[index]
        index += 1
        if not record:
            continue
        fields = record.split(b"\t")
        if len(fields) < 3:
            raise ValueError(f"Unexpected numstat record: {record!r}")
        added_raw, removed_raw = fields[0], fields[1]
        path_field = b"\t".join(fields[2:])
        if path_field:
            path = path_field.decode("utf-8", errors="surrogateescape")
            old_path = path
            new_path = path
        else:
            if index + 1 >= len(parts):
                raise ValueError("Numstat rename/copy paths are missing")
            old_path = parts[index].decode("utf-8", errors="surrogateescape")
            new_path = parts[index + 1].decode("utf-8", errors="surrogateescape")
            index += 2
        is_binary = added_raw == b"-" or removed_raw == b"-"
        added = None if added_raw == b"-" else int(added_raw)
        removed = None if removed_raw == b"-" else int(removed_raw)
        output.append(
            NumstatChange(
                old_path=old_path,
                new_path=new_path,
                added=added,
                removed=removed,
                is_binary=is_binary,
            )
        )
    return output


def match_raw_change(change: NumstatChange, raw_changes: Sequence[RawChange]) -> RawChange:
    """Match a numstat path record to its raw diff metadata."""
    exact = [
        item
        for item in raw_changes
        if item.old_path == change.old_path and item.new_path == change.new_path
    ]
    if exact:
        return exact[0]
    by_new = [item for item in raw_changes if item.new_path and item.new_path == change.new_path]
    if len(by_new) == 1:
        return by_new[0]
    by_old = [item for item in raw_changes if item.old_path and item.old_path == change.old_path]
    if len(by_old) == 1:
        return by_old[0]
    return RawChange(
        status="unknown",
        old_mode="",
        new_mode="",
        old_path=change.old_path,
        new_path=change.new_path,
    )


def resolve_history_tip(clone_path: Path, history_ref: str, timeout: int) -> str:
    """Resolve a symbolic history ref once to a stable commit SHA."""
    tip_commit = git_text(clone_path, ["rev-parse", history_ref], timeout).strip().lower()
    if not re.fullmatch(r"[0-9a-f]{40}", tip_commit):
        raise StageError("history_tip_resolution", f"Invalid resolved Git commit: {tip_commit!r}")
    return tip_commit


def list_commits_for_months(
    clone_path: Path,
    tip_commit: str,
    requested_months: set[str],
    timezone: ZoneInfo,
    timeout: int,
) -> list[CommitInfo]:
    """List commits reachable from one frozen tip SHA and assign requested months."""
    output = git_text(
        clone_path,
        ["rev-list", "--parents", "--timestamp", tip_commit],
        timeout,
    )
    commits: list[CommitInfo] = []
    for line in output.splitlines():
        fields = line.split()
        if len(fields) < 2:
            continue
        epoch = int(fields[0])
        commit_sha = fields[1].lower()
        parents = tuple(value.lower() for value in fields[2:])
        local_time = datetime.fromtimestamp(epoch, timezone)
        month = local_time.strftime("%Y-%m")
        if month not in requested_months:
            continue
        commits.append(
            CommitInfo(
                commit_sha=commit_sha,
                parents=parents,
                commit_time_epoch=epoch,
                commit_time_local=local_time.isoformat(),
                commit_month=month,
            )
        )
    commits.sort(key=lambda item: (item.commit_time_epoch, item.commit_sha))
    return commits


def collect_commit_metrics(
    clone_path: Path,
    dataset_source: str,
    repo_name: str,
    commit: CommitInfo,
    timeout: int,
) -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]]:
    """Collect repository and multi-definition Python line metrics for one commit."""
    started = time.monotonic()
    commit_row: dict[str, Any] = {
        "repo_name": repo_name,
        "dataset_source": dataset_source,
        "commit_sha": commit.commit_sha,
        "first_parent_sha": commit.first_parent_sha,
        "commit_time_epoch": commit.commit_time_epoch,
        "commit_time_local": commit.commit_time_local,
        "commit_month": commit.commit_month,
        "parent_count": len(commit.parents),
        "is_merge_commit": int(commit.is_merge_commit),
        "is_root_commit": int(commit.is_root_commit),
        "lines_added_repo_recomputed": 0,
        "lines_removed_repo_recomputed": 0,
        "lines_added_py": 0,
        "lines_removed_py": 0,
        "lines_added_py_all": 0,
        "lines_added_py_no_merge": 0,
        "lines_added_py_source": 0,
        "lines_added_py_source_no_tests": 0,
        "included_in_py_all": 0,
        "included_in_py_no_merge": 0,
        "included_in_py_source": 0,
        "included_in_py_source_no_tests": 0,
        "python_file_change_events": 0,
        "python_unique_paths_changed": 0,
        "python_file_change_events_no_merge": 0,
        "python_unique_paths_changed_no_merge": 0,
        "python_file_change_events_source": 0,
        "python_unique_paths_changed_source": 0,
        "python_file_change_events_source_no_tests": 0,
        "python_unique_paths_changed_source_no_tests": 0,
        "python_touched": 0,
        "python_has_added_lines": 0,
        "python_touched_no_merge": 0,
        "python_has_added_lines_no_merge": 0,
        "python_touched_source": 0,
        "python_has_added_lines_source": 0,
        "python_touched_source_no_tests": 0,
        "python_has_added_lines_source_no_tests": 0,
        "diff_status": "root_excluded" if commit.is_root_commit else "pending",
        "python_metric_complete": 1,
        "runtime_seconds": 0.0,
    }
    if commit.is_root_commit:
        commit_row["runtime_seconds"] = round(time.monotonic() - started, 3)
        return commit_row, [], []

    file_rows: list[dict[str, Any]] = []
    issue_rows: list[dict[str, Any]] = []
    try:
        raw_payload = git_bytes(
            clone_path,
            [
                "diff-tree",
                "--no-commit-id",
                "--raw",
                "-r",
                "-M",
                "-C",
                "-z",
                commit.first_parent_sha,
                commit.commit_sha,
            ],
            timeout,
        )
        numstat_payload = git_bytes(
            clone_path,
            [
                "diff",
                "--numstat",
                "-z",
                "--find-renames",
                "--find-copies",
                f"{commit.first_parent_sha}..{commit.commit_sha}",
            ],
            timeout,
        )
        raw_changes = parse_raw_diff(raw_payload)
        numstat_changes = parse_numstat_z(numstat_payload)
    except Exception as exc:
        commit_row["diff_status"] = "diff_failed"
        commit_row["python_metric_complete"] = 0
        commit_row["runtime_seconds"] = round(time.monotonic() - started, 3)
        issue_rows.append(
            {
                "repo_name": repo_name,
                "dataset_source": dataset_source,
                "time": commit.commit_month,
                "commit_sha": commit.commit_sha,
                "path": "",
                "stage": "commit_diff",
                "error_type": type(exc).__name__,
                "error_message": str(exc),
                "resolution_status": "unresolved",
            }
        )
        return commit_row, file_rows, issue_rows

    repo_added = sum(item.added or 0 for item in numstat_changes if not item.is_binary)
    repo_removed = sum(item.removed or 0 for item in numstat_changes if not item.is_binary)
    commit_row["lines_added_repo_recomputed"] = repo_added
    commit_row["lines_removed_repo_recomputed"] = repo_removed

    outcome_sums = {name: 0 for name in OUTCOME_NAMES}
    broad_removed = 0
    included_paths = {
        "all": set(),
        "no_merge": set(),
        "source": set(),
        "source_no_tests": set(),
    }
    event_counts = {name: 0 for name in included_paths}

    for numstat in numstat_changes:
        raw = match_raw_change(numstat, raw_changes)
        post_path = raw.new_path or numstat.new_path
        is_python_path = path_is_python(post_path)
        regular_python_mode = is_python_path and raw.new_mode in VALID_PYTHON_MODES
        broad_included = regular_python_mode and bool(post_path)
        classification = classify_python_path(post_path) if broad_included else {
            "is_vendor_path": 0,
            "is_generated_api_client": 0,
            "is_generated_resource_module": 0,
            "is_generated_path": 0,
            "is_test_path": 0,
            "source_exclusion_reason": "",
        }
        source_eligible = broad_included and not (
            classification["is_vendor_path"] or classification["is_generated_path"]
        )
        included_all = broad_included
        included_no_merge = broad_included and not commit.is_merge_commit
        included_source = source_eligible and not commit.is_merge_commit
        included_source_no_tests = included_source and not classification["is_test_path"]

        file_status = "excluded_non_python_or_nonregular"
        if broad_included and numstat.is_binary:
            file_status = "binary_python_unresolved"
            commit_row["python_metric_complete"] = 0
            issue_rows.append(
                {
                    "repo_name": repo_name,
                    "dataset_source": dataset_source,
                    "time": commit.commit_month,
                    "commit_sha": commit.commit_sha,
                    "path": post_path,
                    "stage": "python_numstat",
                    "error_type": "BinaryPythonFile",
                    "error_message": "Git numstat reported '-' for an included Python file.",
                    "resolution_status": "unresolved",
                }
            )
        elif broad_included:
            if commit.is_merge_commit:
                file_status = "included_all_excluded_no_merge"
            elif not source_eligible:
                file_status = "included_no_merge_excluded_source"
            elif classification["is_test_path"]:
                file_status = "included_source_excluded_source_no_tests"
            else:
                file_status = "included_all_outcomes"

            added = int(numstat.added or 0)
            removed = int(numstat.removed or 0)
            if included_all:
                outcome_sums["lines_added_py_all"] += added
                broad_removed += removed
                included_paths["all"].add(post_path)
                event_counts["all"] += 1
            if included_no_merge:
                outcome_sums["lines_added_py_no_merge"] += added
                included_paths["no_merge"].add(post_path)
                event_counts["no_merge"] += 1
            if included_source:
                outcome_sums["lines_added_py_source"] += added
                included_paths["source"].add(post_path)
                event_counts["source"] += 1
            if included_source_no_tests:
                outcome_sums["lines_added_py_source_no_tests"] += added
                included_paths["source_no_tests"].add(post_path)
                event_counts["source_no_tests"] += 1

        file_rows.append(
            {
                "repo_name": repo_name,
                "dataset_source": dataset_source,
                "commit_sha": commit.commit_sha,
                "commit_month": commit.commit_month,
                "is_merge_commit": int(commit.is_merge_commit),
                "change_status": raw.status,
                "old_mode": raw.old_mode,
                "new_mode": raw.new_mode,
                "old_path": raw.old_path,
                "new_path": raw.new_path,
                "post_path": post_path,
                "path_is_python": int(is_python_path),
                "post_mode_is_regular_python": int(regular_python_mode),
                "is_binary": int(numstat.is_binary),
                **classification,
                "lines_added": numstat.added if numstat.added is not None else "",
                "lines_removed": numstat.removed if numstat.removed is not None else "",
                "included_in_python_metric": int(included_all),
                "included_in_py_all": int(included_all),
                "included_in_py_no_merge": int(included_no_merge),
                "included_in_py_source": int(included_source),
                "included_in_py_source_no_tests": int(included_source_no_tests),
                "file_status": file_status,
            }
        )

    commit_row.update(outcome_sums)
    # Backward-compatible v3 aliases retain the broad, merge-inclusive metric.
    commit_row["lines_added_py"] = outcome_sums["lines_added_py_all"]
    commit_row["lines_removed_py"] = broad_removed
    commit_row["included_in_py_all"] = int(bool(included_paths["all"]))
    commit_row["included_in_py_no_merge"] = int(bool(included_paths["no_merge"]))
    commit_row["included_in_py_source"] = int(bool(included_paths["source"]))
    commit_row["included_in_py_source_no_tests"] = int(bool(included_paths["source_no_tests"]))
    commit_row["python_file_change_events"] = event_counts["all"]
    commit_row["python_unique_paths_changed"] = len(included_paths["all"])
    commit_row["python_file_change_events_no_merge"] = event_counts["no_merge"]
    commit_row["python_unique_paths_changed_no_merge"] = len(included_paths["no_merge"])
    commit_row["python_file_change_events_source"] = event_counts["source"]
    commit_row["python_unique_paths_changed_source"] = len(included_paths["source"])
    commit_row["python_file_change_events_source_no_tests"] = event_counts["source_no_tests"]
    commit_row["python_unique_paths_changed_source_no_tests"] = len(included_paths["source_no_tests"])
    commit_row["python_touched"] = int(bool(included_paths["all"]))
    commit_row["python_has_added_lines"] = int(outcome_sums["lines_added_py_all"] > 0)
    commit_row["python_touched_no_merge"] = int(bool(included_paths["no_merge"]))
    commit_row["python_has_added_lines_no_merge"] = int(outcome_sums["lines_added_py_no_merge"] > 0)
    commit_row["python_touched_source"] = int(bool(included_paths["source"]))
    commit_row["python_has_added_lines_source"] = int(outcome_sums["lines_added_py_source"] > 0)
    commit_row["python_touched_source_no_tests"] = int(bool(included_paths["source_no_tests"]))
    commit_row["python_has_added_lines_source_no_tests"] = int(
        outcome_sums["lines_added_py_source_no_tests"] > 0
    )
    commit_row["diff_status"] = (
        "success" if int(commit_row["python_metric_complete"]) == 1 else "partial_unresolved"
    )
    commit_row["runtime_seconds"] = round(time.monotonic() - started, 3)
    return commit_row, file_rows, issue_rows

def add_issue(
    issues: list[dict[str, Any]],
    *,
    repo_name: str,
    dataset_source: str,
    time_value: str,
    commit_sha: str,
    path: str,
    stage: str,
    error: Exception | str,
    resolution_status: str = "unresolved",
) -> None:
    """Append one normalized issue record."""
    if isinstance(error, Exception):
        error_type = type(error).__name__
        error_message = str(error)
    else:
        error_type = stage
        error_message = str(error)
    issues.append(
        {
            "repo_name": repo_name,
            "dataset_source": dataset_source,
            "time": time_value,
            "commit_sha": commit_sha,
            "path": path,
            "stage": stage,
            "error_type": error_type,
            "error_message": error_message,
            "resolution_status": resolution_status,
        }
    )


def normalize_panel(raw: pd.DataFrame) -> pd.DataFrame:
    """Validate and normalize the run-x-a05 Model A panel."""
    missing = sorted(REQUIRED_PANEL_COLUMNS - set(raw.columns))
    if missing:
        raise ValueError(f"Base panel is missing required columns: {missing}")
    panel = raw.copy()
    panel["dataset_source"] = panel["dataset_source"].map(clean_text).str.casefold()
    panel["repo_name"] = panel["repo_name"].map(clean_text)
    panel["time"] = panel["time"].map(clean_text)
    panel["latest_commit_effective"] = (
        panel["latest_commit_effective"].map(clean_text).str.casefold()
    )
    panel["clone_path"] = panel["clone_path"].map(clean_text)
    unexpected = set(panel["dataset_source"].unique()) - EXPECTED_DATASET_SOURCES
    if unexpected:
        raise ValueError(f"Unexpected dataset_source values: {sorted(unexpected)}")
    if not panel["time"].str.fullmatch(r"\d{4}-\d{2}").all():
        raise ValueError("Panel time must use YYYY-MM format")
    for column in ["repo_id", "time_index", "commits", "lines_added"]:
        panel[column] = pd.to_numeric(panel[column], errors="raise")
    panel["repo_id"] = panel["repo_id"].astype(int)
    panel["time_index"] = panel["time_index"].astype(int)
    if panel.duplicated(["repo_id", "time_index"]).any():
        raise ValueError("Base panel contains duplicate repo_id-time_index rows")
    repo_clone_counts = panel.groupby(["dataset_source", "repo_name"])["clone_path"].nunique()
    if (repo_clone_counts > 1).any():
        bad = repo_clone_counts[repo_clone_counts > 1].head(20)
        raise ValueError(f"Repositories have multiple clone paths: {bad.to_dict()}")
    return panel.sort_values(["repo_id", "time_index"], kind="stable").reset_index(drop=True)


def repository_fingerprint(
    group: pd.DataFrame, args: argparse.Namespace, analysis_tip_commit: str
) -> str:
    """Create a stable cache fingerprint for one repository input."""
    columns = [
        "repo_id",
        "repo_name",
        "dataset_source",
        "time",
        "time_index",
        "commits",
        "lines_added",
        "latest_commit_effective",
        "clone_path",
    ]
    payload = group[columns].sort_values("time_index", kind="stable").to_csv(index=False)
    payload += json.dumps(
        {
            "implementation_version": IMPLEMENTATION_VERSION,
            "timezone": args.analysis_timezone,
            "history_ref": args.history_ref,
            "analysis_tip_commit": analysis_tip_commit,
            "excluded_directories": sorted(EXCLUDED_DIRECTORY_NAMES),
            "valid_modes": sorted(VALID_PYTHON_MODES),
        },
        sort_keys=True,
    )
    return sha256_text(payload)


def load_repo_cache(cache_dir: Path, fingerprint: str) -> Optional[dict[str, pd.DataFrame]]:
    """Load a completed repository cache when its fingerprint matches."""
    metadata_path = cache_dir / "metadata.json"
    if not metadata_path.exists():
        return None
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    if (
        metadata.get("status") != "completed"
        or metadata.get("fingerprint") != fingerprint
        or metadata.get("implementation_version") != IMPLEMENTATION_VERSION
    ):
        return None
    paths = {
        "repo_month": cache_dir / "repo_month.csv",
        "commits": cache_dir / "commits.csv",
        "files": cache_dir / "files.csv",
        "issues": cache_dir / "issues.csv",
    }
    if not all(path.exists() for path in paths.values()):
        return None
    return {name: pd.read_csv(path, low_memory=False) for name, path in paths.items()}


def save_repo_cache(
    cache_dir: Path,
    fingerprint: str,
    outputs: dict[str, pd.DataFrame],
) -> None:
    """Persist one completed repository result for resume behavior."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    save_dataframe(outputs["repo_month"], cache_dir / "repo_month.csv", REPO_MONTH_COLUMNS)
    save_dataframe(outputs["commits"], cache_dir / "commits.csv", COMMIT_COLUMNS)
    save_dataframe(outputs["files"], cache_dir / "files.csv", FILE_COLUMNS)
    save_dataframe(outputs["issues"], cache_dir / "issues.csv", ISSUE_COLUMNS)
    write_json(
        {
            "status": "completed",
            "fingerprint": fingerprint,
            "implementation_version": IMPLEMENTATION_VERSION,
        },
        cache_dir / "metadata.json",
    )


def process_repository(
    group: pd.DataFrame,
    args: argparse.Namespace,
    timezone: ZoneInfo,
) -> dict[str, pd.DataFrame]:
    """Collect all requested repository-month metrics for one repository."""
    dataset_source = str(group["dataset_source"].iloc[0])
    repo_name = str(group["repo_name"].iloc[0])
    clone_path = Path(str(group["clone_path"].iloc[0])).expanduser().resolve()
    cache_dir = args.cache_dir.expanduser().resolve() / stable_repo_key(dataset_source, repo_name)

    repo_month_rows: list[dict[str, Any]] = []
    commit_rows: list[dict[str, Any]] = []
    file_rows: list[dict[str, Any]] = []
    issue_rows: list[dict[str, Any]] = []
    history_complete = True
    analysis_tip = ""
    commits: list[CommitInfo] = []

    ready, clone_status = validate_clone(clone_path, args.git_timeout_seconds)
    if not ready:
        history_complete = False
        add_issue(
            issue_rows,
            repo_name=repo_name,
            dataset_source=dataset_source,
            time_value="",
            commit_sha="",
            path=str(clone_path),
            stage="clone_validation",
            error=clone_status,
        )
    else:
        try:
            # Resolve HEAD or another symbolic ref once. All later history commands use
            # this immutable SHA, and the SHA is included in the cache fingerprint.
            analysis_tip = resolve_history_tip(
                clone_path, args.history_ref, args.git_timeout_seconds
            )
        except Exception as exc:
            history_complete = False
            add_issue(
                issue_rows,
                repo_name=repo_name,
                dataset_source=dataset_source,
                time_value="",
                commit_sha="",
                path=str(clone_path),
                stage="history_tip_resolution",
                error=exc,
            )

    fingerprint = repository_fingerprint(group, args, analysis_tip)
    if not args.analysis_again and ready and analysis_tip:
        cached = load_repo_cache(cache_dir, fingerprint)
        if cached is not None:
            logging.info("Resume skip: %s at frozen tip %s", repo_name, analysis_tip[:12])
            return cached
    elif args.analysis_again and cache_dir.exists():
        shutil.rmtree(cache_dir)

    if ready and analysis_tip and history_complete:
        try:
            commits = list_commits_for_months(
                clone_path,
                analysis_tip,
                set(group["time"].astype(str)),
                timezone,
                args.git_timeout_seconds,
            )
        except Exception as exc:
            history_complete = False
            commits = []
            add_issue(
                issue_rows,
                repo_name=repo_name,
                dataset_source=dataset_source,
                time_value="",
                commit_sha=analysis_tip,
                path=str(clone_path),
                stage="history_scan",
                error=exc,
            )

    if ready and analysis_tip:
        for commit_sha in sorted(set(group["latest_commit_effective"]) - {""}):
            if not commit_exists(clone_path, commit_sha, args.git_timeout_seconds):
                add_issue(
                    issue_rows,
                    repo_name=repo_name,
                    dataset_source=dataset_source,
                    time_value="",
                    commit_sha=commit_sha,
                    path="",
                    stage="panel_commit_validation",
                    error="Panel effective commit is missing from the local clone.",
                    resolution_status="reference_warning",
                )
            elif not commit_is_ancestor(
                clone_path,
                commit_sha,
                analysis_tip,
                args.git_timeout_seconds,
            ):
                add_issue(
                    issue_rows,
                    repo_name=repo_name,
                    dataset_source=dataset_source,
                    time_value="",
                    commit_sha=commit_sha,
                    path="",
                    stage="panel_commit_reachability",
                    error=(
                        f"Panel effective commit is not reachable from {args.history_ref} "
                        f"tip {analysis_tip}."
                    ),
                    resolution_status="reference_warning",
                )

    if args.dry_run:
        commits = []

    for position, commit in enumerate(commits, start=1):
        commit_row, one_file_rows, one_issue_rows = collect_commit_metrics(
            clone_path,
            dataset_source,
            repo_name,
            commit,
            args.git_timeout_seconds,
        )
        commit_rows.append(commit_row)
        file_rows.extend(one_file_rows)
        issue_rows.extend(one_issue_rows)
        # Commit-level metric failures are evaluated in their own month. They do
        # not invalidate technically complete months in the same repository.
        if position % max(args.progress_every_commits, 1) == 0:
            logging.info(
                "%s: processed %d/%d requested commits",
                repo_name,
                position,
                len(commits),
            )

    commits_df = pd.DataFrame(commit_rows, columns=COMMIT_COLUMNS)
    files_df = pd.DataFrame(file_rows, columns=FILE_COLUMNS)
    issues_df = pd.DataFrame(issue_rows, columns=ISSUE_COLUMNS)

    for row in group.sort_values("time_index", kind="stable").to_dict("records"):
        month = str(row["time"])
        month_commits = commits_df[commits_df["commit_month"].astype(str).eq(month)].copy()
        month_issues = issues_df[
            issues_df["time"].fillna("").astype(str).isin(["", month])
        ]
        commits_recomputed = len(month_commits)
        lines_repo = int(pd.to_numeric(month_commits.get("lines_added_repo_recomputed"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0
        removed_repo = int(pd.to_numeric(month_commits.get("lines_removed_repo_recomputed"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0
        monthly_outcomes = {
            name: (
                int(pd.to_numeric(month_commits.get(name), errors="coerce").fillna(0).sum())
                if not month_commits.empty
                else 0
            )
            for name in OUTCOME_NAMES
        }
        lines_py = monthly_outcomes["lines_added_py_all"]
        python_complete = bool(
            history_complete
            and (
                month_commits.empty
                or pd.to_numeric(month_commits["python_metric_complete"], errors="coerce").fillna(0).eq(1).all()
            )
        )
        commits_original = int(round(float(row["commits"])))
        lines_original = int(round(float(row["lines_added"])))
        commits_match = commits_recomputed == commits_original
        lines_match = lines_repo == lines_original
        reconciliation_complete = bool(history_complete and commits_match and lines_match)
        latest_commit = ""
        if not month_commits.empty:
            latest_row = month_commits.sort_values(
                ["commit_time_epoch", "commit_sha"], kind="stable"
            ).iloc[-1]
            latest_commit = str(latest_row["commit_sha"])
        unique_paths_by_outcome: dict[str, set[str]] = {
            "all": set(),
            "no_merge": set(),
            "source": set(),
            "source_no_tests": set(),
        }
        if not files_df.empty:
            month_file_mask = files_df["commit_month"].astype(str).eq(month)
            inclusion_columns = {
                "all": "included_in_py_all",
                "no_merge": "included_in_py_no_merge",
                "source": "included_in_py_source",
                "source_no_tests": "included_in_py_source_no_tests",
            }
            for label, column in inclusion_columns.items():
                selected_files = files_df[
                    month_file_mask
                    & pd.to_numeric(files_df[column], errors="coerce").fillna(0).eq(1)
                ]
                unique_paths_by_outcome[label] = set(
                    selected_files["post_path"].dropna().astype(str)
                )
        # Model A is a downstream experimental panel, not the measurement
        # ground truth. Reference drift is retained as audit information and does
        # not make a technically complete Python measurement unavailable.
        available = bool(python_complete)
        if available and reconciliation_complete:
            status = "success"
        elif available:
            status = "success_reference_drift"
        else:
            status = "unresolved_measurement"
        repo_month_rows.append(
            {
                "repo_id": int(row["repo_id"]),
                "repo_name": repo_name,
                "dataset_source": dataset_source,
                "time": month,
                "time_index": int(row["time_index"]),
                "commits_original": commits_original,
                "commits_recomputed": commits_recomputed,
                "commits_match_original": int(commits_match),
                "lines_added_repo_original": lines_original,
                "log_lines_added_repo_original": float(np.log1p(lines_original)),
                "lines_added_repo_recomputed": lines_repo,
                "lines_added_repo_match_original": int(lines_match),
                "lines_removed_repo_recomputed": removed_repo,
                "lines_added_py_total": lines_py,
                "lines_added_py": lines_py,
                "log_lines_added_py": float(np.log1p(lines_py)),
                **monthly_outcomes,
                **{f"log_{name}": float(np.log1p(value)) for name, value in monthly_outcomes.items()},
                "python_commits_touched": int(pd.to_numeric(month_commits.get("python_touched"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_commits_with_added_lines": int(pd.to_numeric(month_commits.get("python_has_added_lines"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_file_change_events": int(pd.to_numeric(month_commits.get("python_file_change_events"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_unique_paths_changed": len(unique_paths_by_outcome["all"]),
                "python_commits_touched_no_merge": int(pd.to_numeric(month_commits.get("python_touched_no_merge"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_commits_with_added_lines_no_merge": int(pd.to_numeric(month_commits.get("python_has_added_lines_no_merge"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_file_change_events_no_merge": int(pd.to_numeric(month_commits.get("python_file_change_events_no_merge"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_unique_paths_changed_no_merge": len(unique_paths_by_outcome["no_merge"]),
                "python_commits_touched_source": int(pd.to_numeric(month_commits.get("python_touched_source"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_commits_with_added_lines_source": int(pd.to_numeric(month_commits.get("python_has_added_lines_source"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_file_change_events_source": int(pd.to_numeric(month_commits.get("python_file_change_events_source"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_unique_paths_changed_source": len(unique_paths_by_outcome["source"]),
                "python_commits_touched_source_no_tests": int(pd.to_numeric(month_commits.get("python_touched_source_no_tests"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_commits_with_added_lines_source_no_tests": int(pd.to_numeric(month_commits.get("python_has_added_lines_source_no_tests"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_file_change_events_source_no_tests": int(pd.to_numeric(month_commits.get("python_file_change_events_source_no_tests"), errors="coerce").fillna(0).sum()) if not month_commits.empty else 0,
                "python_unique_paths_changed_source_no_tests": len(unique_paths_by_outcome["source_no_tests"]),
                "latest_commit_recomputed": latest_commit,
                "latest_commit_effective": clean_text(row["latest_commit_effective"]).casefold(),
                "analysis_tip_commit": analysis_tip,
                "analysis_history_ref": args.history_ref,
                "analysis_timezone": args.analysis_timezone,
                "count_backend": COUNT_BACKEND,
                "history_complete": int(history_complete),
                "python_added_lines_complete": int(python_complete),
                "reference_reconciliation_complete": int(reconciliation_complete),
                "reference_reconciliation_status": (
                    "match" if reconciliation_complete else "drift"
                ),
                # Legacy audit alias retained for compatibility. It is not used
                # as an availability gate in v4.
                "history_reconciliation_complete": int(reconciliation_complete),
                "python_added_lines_available": int(available),
                "python_added_lines_status": status,
                "issue_count": len(month_issues),
            }
        )

    outputs = {
        "repo_month": pd.DataFrame(repo_month_rows, columns=REPO_MONTH_COLUMNS),
        "commits": commits_df,
        "files": files_df,
        "issues": issues_df,
    }
    if not args.dry_run:
        save_repo_cache(cache_dir, fingerprint, outputs)
    return outputs


def build_reconciliation(repo_month: pd.DataFrame) -> pd.DataFrame:
    """Build the repository-month reconciliation audit table."""
    output = repo_month.copy()
    output["commits_delta"] = output["commits_recomputed"] - output["commits_original"]
    output["lines_added_delta"] = (
        output["lines_added_repo_recomputed"] - output["lines_added_repo_original"]
    )
    return output[RECONCILIATION_COLUMNS]


def build_qc_and_summary(
    panel: pd.DataFrame,
    repo_month: pd.DataFrame,
    commits: pd.DataFrame,
    files: pd.DataFrame,
    issues: pd.DataFrame,
    args: argparse.Namespace,
    selected_repositories: int,
    full_scope: bool,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Build structural QC checks and a long-form run summary."""
    checks: list[dict[str, Any]] = []

    def add_check(
        name: str,
        observed: Any,
        expected: Any,
        *,
        policy: str = "always",
        note: str = "",
    ) -> None:
        if observed == expected:
            status = "pass"
        elif policy == "always":
            status = "fail"
        elif policy == "strict":
            status = "fail" if args.strict_expected_counts else "warn"
        else:
            status = "warn"
        checks.append(
            {
                "check_name": name,
                "status": status,
                "observed": observed,
                "expected": expected,
                "policy": policy,
                "note": note,
            }
        )

    add_check("selected_panel_rows_output", len(repo_month), len(panel))
    add_check(
        "duplicate_repo_id_time_index_rows",
        int(repo_month.duplicated(["repo_id", "time_index"]).sum()),
        0,
    )
    for outcome in OUTCOME_NAMES:
        values = pd.to_numeric(repo_month[outcome], errors="coerce")
        add_check(f"negative_{outcome}", int((values < 0).sum()), 0)
        expected_log = np.log1p(values)
        add_check(
            f"log_transform_mismatches_{outcome}",
            int((~np.isclose(expected_log, repo_month[f"log_{outcome}"], rtol=0, atol=1e-12)).sum()),
            0,
        )
        add_check(
            f"no_commit_month_with_{outcome}",
            int(((repo_month["commits_recomputed"] == 0) & values.ne(0)).sum()),
            0,
        )

    add_check(
        "python_all_lines_exceed_repository_lines",
        int((repo_month["lines_added_py_all"] > repo_month["lines_added_repo_recomputed"]).sum()),
        0,
    )
    add_check(
        "legacy_python_alias_mismatches",
        int(
            (
                repo_month["lines_added_py"].ne(repo_month["lines_added_py_all"])
                | repo_month["lines_added_py_total"].ne(repo_month["lines_added_py_all"])
                | ~np.isclose(
                    repo_month["log_lines_added_py"],
                    repo_month["log_lines_added_py_all"],
                    rtol=0,
                    atol=1e-12,
                )
            ).sum()
        ),
        0,
    )
    add_check(
        "outcome_nesting_mismatches",
        int(
            (
                (repo_month["lines_added_py_source_no_tests"] > repo_month["lines_added_py_source"])
                | (repo_month["lines_added_py_source"] > repo_month["lines_added_py_no_merge"])
                | (repo_month["lines_added_py_no_merge"] > repo_month["lines_added_py_all"])
            ).sum()
        ),
        0,
    )

    file_inclusion_columns = {
        "lines_added_py_all": "included_in_py_all",
        "lines_added_py_no_merge": "included_in_py_no_merge",
        "lines_added_py_source": "included_in_py_source",
        "lines_added_py_source_no_tests": "included_in_py_source_no_tests",
    }
    for outcome, inclusion_column in file_inclusion_columns.items():
        commit_sum = (
            int(pd.to_numeric(commits.get(outcome), errors="coerce").fillna(0).sum())
            if not commits.empty
            else 0
        )
        month_sum = int(pd.to_numeric(repo_month[outcome], errors="coerce").fillna(0).sum())
        file_sum = (
            int(
                pd.to_numeric(
                    files.loc[
                        pd.to_numeric(files.get(inclusion_column), errors="coerce").fillna(0).eq(1),
                        "lines_added",
                    ],
                    errors="coerce",
                ).fillna(0).sum()
            )
            if not files.empty
            else 0
        )
        add_check(f"commit_to_repo_month_sum_{outcome}", commit_sum, month_sum)
        add_check(f"file_to_commit_sum_{outcome}", file_sum, commit_sum)

    if not commits.empty:
        merge_rows = pd.to_numeric(commits["is_merge_commit"], errors="coerce").fillna(0).eq(1)
        add_check(
            "merge_commit_no_merge_outcome_nonzero",
            int(
                (
                    merge_rows
                    & (
                        commits["lines_added_py_no_merge"].ne(0)
                        | commits["lines_added_py_source"].ne(0)
                        | commits["lines_added_py_source_no_tests"].ne(0)
                    )
                ).sum()
            ),
            0,
        )
    if not files.empty:
        merge_file_rows = pd.to_numeric(files["is_merge_commit"], errors="coerce").fillna(0).eq(1)
        source_excluded_rows = (
            pd.to_numeric(files["is_vendor_path"], errors="coerce").fillna(0).eq(1)
            | pd.to_numeric(files["is_generated_path"], errors="coerce").fillna(0).eq(1)
        )
        test_rows = pd.to_numeric(files["is_test_path"], errors="coerce").fillna(0).eq(1)
        add_check(
            "merge_files_included_in_no_merge_outcomes",
            int(
                (
                    merge_file_rows
                    & (
                        pd.to_numeric(files["included_in_py_no_merge"], errors="coerce").fillna(0).eq(1)
                        | pd.to_numeric(files["included_in_py_source"], errors="coerce").fillna(0).eq(1)
                        | pd.to_numeric(files["included_in_py_source_no_tests"], errors="coerce").fillna(0).eq(1)
                    )
                ).sum()
            ),
            0,
        )
        add_check(
            "vendor_generated_files_included_in_source",
            int(
                (
                    source_excluded_rows
                    & pd.to_numeric(files["included_in_py_source"], errors="coerce").fillna(0).eq(1)
                ).sum()
            ),
            0,
        )
        add_check(
            "test_files_included_in_source_no_tests",
            int(
                (
                    test_rows
                    & pd.to_numeric(files["included_in_py_source_no_tests"], errors="coerce").fillna(0).eq(1)
                ).sum()
            ),
            0,
        )
    add_check(
        "binary_python_issue_rows",
        int((issues.get("error_type", pd.Series(dtype=str)).astype(str) == "BinaryPythonFile").sum()) if not issues.empty else 0,
        0,
        policy="warn",
        note="Binary included Python files make affected rows unavailable.",
    )
    reference_warning_rows = int(
        issues.get("resolution_status", pd.Series(dtype=str))
        .astype(str)
        .eq("reference_warning")
        .sum()
    ) if not issues.empty else 0
    add_check(
        "panel_reference_commit_warning_rows",
        reference_warning_rows,
        0,
        policy="warn",
        note="Panel snapshot reachability is an audit reference and does not gate Python flow measurement.",
    )
    add_check(
        "unavailable_repo_month_rows",
        int((repo_month["python_added_lines_available"] != 1).sum()),
        0,
        policy="warn",
        note="The full audit output retains unavailable rows for review.",
    )
    reference_commits_mismatch = repo_month["commits_match_original"].ne(1)
    reference_lines_mismatch = repo_month["lines_added_repo_match_original"].ne(1)
    reference_drift = repo_month["reference_reconciliation_complete"].ne(1)
    add_check(
        "reference_commits_mismatch_rows",
        int(reference_commits_mismatch.sum()),
        0,
        policy="warn",
        note="Model A commit counts are a historical reference only.",
    )
    add_check(
        "reference_lines_added_mismatch_rows",
        int(reference_lines_mismatch.sum()),
        0,
        policy="warn",
        note="Model A lines_added values are a historical reference only.",
    )
    add_check(
        "reference_reconciliation_drift_rows",
        int(reference_drift.sum()),
        0,
        policy="warn",
        note="Reference drift is audited but does not exclude a complete measurement.",
    )
    technically_complete_drift = reference_drift & repo_month["python_added_lines_complete"].eq(1)
    add_check(
        "technically_complete_reference_drift_rows_not_retained",
        int((technically_complete_drift & repo_month["python_added_lines_available"].ne(1)).sum()),
        0,
        policy="always",
        note="Every technically complete drift row must remain available in v4.",
    )
    if full_scope:
        add_check("full_panel_rows", len(repo_month), args.expected_panel_rows, policy="strict")
        add_check("full_repositories", selected_repositories, args.expected_repositories, policy="strict")
        add_check(
            "treatment_rows",
            int(repo_month["dataset_source"].eq("treatment").sum()),
            args.expected_treatment_rows,
            policy="strict",
        )
        add_check(
            "control_rows",
            int(repo_month["dataset_source"].eq("control").sum()),
            args.expected_control_rows,
            policy="strict",
        )
        add_check(
            "treatment_repositories",
            int(repo_month.loc[repo_month["dataset_source"].eq("treatment"), "repo_name"].nunique()),
            args.expected_treatment_repositories,
            policy="strict",
        )
        add_check(
            "control_repositories",
            int(repo_month.loc[repo_month["dataset_source"].eq("control"), "repo_name"].nunique()),
            args.expected_control_repositories,
            policy="strict",
        )

    qc = pd.DataFrame(checks)
    summary_rows: list[dict[str, Any]] = []

    def add_summary(section: str, metric: str, value: Any, note: str = "") -> None:
        summary_rows.append(
            {"section": section, "metric": metric, "value": value, "note": note}
        )

    add_summary("implementation", "version", IMPLEMENTATION_VERSION)
    add_summary("definition", "primary_metric", "lines_added_py_source")
    add_summary("definition", "legacy_metric", "lines_added_py_all")
    add_summary("definition", "robustness_metrics", "lines_added_py_no_merge|lines_added_py_source_no_tests|lines_added_py_all")
    add_summary("definition", "count_backend", COUNT_BACKEND)
    add_summary("definition", "history_ref", args.history_ref)
    add_summary("definition", "history_tip_policy", "resolve_once_to_commit_sha_per_repository")
    add_summary("definition", "availability_policy", "technical_measurement_complete_only")
    add_summary("definition", "model_a_reconciliation_policy", "warning_only_reference_drift_audit")
    add_summary("definition", "analysis_timezone", args.analysis_timezone)
    add_summary("definition", "merge_policy_all", "first_parent_included")
    add_summary("definition", "merge_policy_cleaned", "exclude_merge_commits_keep_branch_commit_months")
    add_summary("definition", "source_policy", "exclude_vendor_and_conservative_generated_path_patterns")
    add_summary("definition", "test_policy", "included_in_source_excluded_in_source_no_tests")
    add_summary("definition", "root_commit_policy", "commit_counted_lines_excluded")
    add_summary("definition", "python_path_policy", "post_change_regular_dot_py")
    add_summary("definition", "excluded_directories", "|".join(sorted(EXCLUDED_DIRECTORY_NAMES)))
    add_summary("input", "selected_panel_rows", len(panel))
    add_summary("input", "selected_repositories", selected_repositories)
    add_summary("output", "repo_month_rows", len(repo_month))
    add_summary("output", "commit_rows", len(commits))
    add_summary("output", "file_rows", len(files))
    add_summary("output", "issue_rows", len(issues))
    add_summary("availability", "available_repo_month_rows", int(repo_month["python_added_lines_available"].sum()))
    add_summary("availability", "unavailable_repo_month_rows", int((repo_month["python_added_lines_available"] != 1).sum()))
    add_summary("reference_drift", "commits_mismatch_rows", int(repo_month["commits_match_original"].ne(1).sum()))
    add_summary("reference_drift", "lines_added_mismatch_rows", int(repo_month["lines_added_repo_match_original"].ne(1).sum()))
    add_summary("reference_drift", "reconciliation_drift_rows", int(repo_month["reference_reconciliation_complete"].ne(1).sum()))
    add_summary("reference_drift", "commits_delta_total", int((repo_month["commits_recomputed"] - repo_month["commits_original"]).sum()))
    add_summary("reference_drift", "lines_added_delta_total", int((repo_month["lines_added_repo_recomputed"] - repo_month["lines_added_repo_original"]).sum()))
    for outcome in OUTCOME_NAMES:
        add_summary("metric", f"{outcome}_total", int(repo_month[outcome].sum()))
    add_summary("metric", "python_commits_touched", int(repo_month["python_commits_touched"].sum()))
    add_summary("metric", "python_commits_with_added_lines", int(repo_month["python_commits_with_added_lines"].sum()))
    add_summary("qc", "blocking_failures", int(qc["status"].eq("fail").sum()))
    add_summary("qc", "warnings", int(qc["status"].eq("warn").sum()))
    for role, role_data in repo_month.groupby("dataset_source", sort=True):
        add_summary("metric_by_role", f"{role}_rows", len(role_data))
        for outcome in OUTCOME_NAMES:
            add_summary("metric_by_role", f"{role}_{outcome}", int(role_data[outcome].sum()))
        add_summary("metric_by_role", f"{role}_available_rows", int(role_data["python_added_lines_available"].sum()))
    return qc, pd.DataFrame(summary_rows)


def filter_panel(panel: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    """Apply repository-level smoke-test filters without splitting repositories."""
    repositories = (
        panel[["dataset_source", "repo_name", "repo_id"]]
        .drop_duplicates()
        .sort_values(["dataset_source", "repo_name"], kind="stable")
        .reset_index(drop=True)
    )
    repositories.insert(0, "repo_order", range(1, len(repositories) + 1))
    if args.dataset_source:
        repositories = repositories[repositories["dataset_source"].eq(args.dataset_source)]
    if args.repo_name:
        repositories = repositories[repositories["repo_name"].eq(args.repo_name)]
    repositories = repositories[repositories["repo_order"] >= args.start_repo_order]
    if args.limit_repos > 0:
        repositories = repositories.head(args.limit_repos)
    if repositories.empty:
        raise ValueError("No repositories matched the requested filters")
    selected_keys = set(zip(repositories["dataset_source"], repositories["repo_name"]))
    mask = [
        (source, repo) in selected_keys
        for source, repo in zip(panel["dataset_source"], panel["repo_name"])
    ]
    return panel.loc[mask].copy()


def run_self_test() -> None:
    """Test the Git numstat and raw-diff parsers."""
    ordinary = b"3\t1\tpkg/a.py\0"
    parsed = parse_numstat_z(ordinary)
    assert parsed == [NumstatChange("pkg/a.py", "pkg/a.py", 3, 1, False)]
    renamed = b"2\t0\t\0old.py\0new.py\0"
    parsed_rename = parse_numstat_z(renamed)
    assert parsed_rename == [NumstatChange("old.py", "new.py", 2, 0, False)]
    binary = b"-\t-\timage.py\0"
    parsed_binary = parse_numstat_z(binary)
    assert parsed_binary[0].is_binary and parsed_binary[0].added is None
    raw = (
        b":100644 100644 1111111 2222222 M\0pkg/a.py\0"
        b":100644 100644 3333333 4444444 R100\0old.py\0new.py\0"
    )
    parsed_raw = parse_raw_diff(raw)
    assert parsed_raw[0].new_path == "pkg/a.py"
    assert parsed_raw[1].old_path == "old.py" and parsed_raw[1].new_path == "new.py"
    assert path_is_python("src/module.py")
    assert not path_is_python("build/module.py")
    assert classify_python_path("src/_vendor/client.py")["is_vendor_path"] == 1
    assert classify_python_path("src/openapi_client/api.py")["is_generated_api_client"] == 1
    assert classify_python_path("anylabeling/resources/resources.py")["is_generated_resource_module"] == 1
    assert classify_python_path("tests/test_client.py")["is_test_path"] == 1
    assert classify_python_path("src/client.py")["source_exclusion_reason"] == ""
    logging.info(
        "Self-test PASS: numstat, raw diff, rename, binary, broad path, "
        "vendor/generated, and test policies"
    )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    if "--self-test" in sys.argv[1:]:
        return argparse.Namespace(self_test=True, log_level="INFO")
    parser = argparse.ArgumentParser(
        description="Collect monthly physical lines added in tracked Python files."
    )
    parser.add_argument("--panel-file", type=Path, required=True)
    parser.add_argument("--repo-month-output", type=Path, required=True)
    parser.add_argument("--commit-output", type=Path, required=True)
    parser.add_argument("--file-output", type=Path, required=True)
    parser.add_argument("--issues-output", type=Path, required=True)
    parser.add_argument("--reconciliation-output", type=Path, required=True)
    parser.add_argument("--qc-output", type=Path, required=True)
    parser.add_argument("--summary-output", type=Path, required=True)
    parser.add_argument("--cache-dir", type=Path, required=True)
    parser.add_argument("--analysis-timezone", default="America/Chicago")
    parser.add_argument("--history-ref", default="HEAD")
    parser.add_argument("--git-timeout-seconds", type=int, default=300)
    parser.add_argument("--start-repo-order", type=int, default=1)
    parser.add_argument("--limit-repos", type=int, default=0)
    parser.add_argument("--dataset-source", choices=["", "treatment", "control"], default="")
    parser.add_argument("--repo-name", default="")
    parser.add_argument("--analysis-again", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--strict-expected-counts", action="store_true")
    parser.add_argument("--progress-every-repos", type=int, default=5)
    parser.add_argument("--progress-every-commits", type=int, default=250)
    parser.add_argument("--expected-panel-rows", type=int, default=1954)
    parser.add_argument("--expected-repositories", type=int, default=167)
    parser.add_argument("--expected-treatment-rows", type=int, default=914)
    parser.add_argument("--expected-control-rows", type=int, default=1040)
    parser.add_argument("--expected-treatment-repositories", type=int, default=63)
    parser.add_argument("--expected-control-repositories", type=int, default=104)
    parser.add_argument("--log-level", default="INFO", choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    """Validate CLI arguments."""
    for name in [
        "git_timeout_seconds",
        "start_repo_order",
        "limit_repos",
        "progress_every_repos",
        "progress_every_commits",
        "expected_panel_rows",
        "expected_repositories",
        "expected_treatment_rows",
        "expected_control_rows",
        "expected_treatment_repositories",
        "expected_control_repositories",
    ]:
        if int(getattr(args, name)) < 0:
            raise ValueError(f"--{name.replace('_', '-')} must be non-negative")
    if args.start_repo_order < 1:
        raise ValueError("--start-repo-order must be at least 1")
    if args.git_timeout_seconds <= 0 and not args.dry_run:
        raise ValueError("--git-timeout-seconds must be positive")
    try:
        ZoneInfo(args.analysis_timezone)
    except ZoneInfoNotFoundError as exc:
        raise ValueError(f"Unknown analysis timezone: {args.analysis_timezone}") from exc


def main() -> int:
    """Run the Python added-lines collection workflow."""
    args = parse_args()
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
    )
    if args.self_test:
        run_self_test()
        return 0
    validate_args(args)
    panel_path = args.panel_file.expanduser().resolve()
    if not panel_path.exists():
        raise FileNotFoundError(f"Base panel not found: {panel_path}")
    panel = normalize_panel(pd.read_csv(panel_path, low_memory=False))
    selected = filter_panel(panel, args)
    full_scope = (
        not args.dataset_source
        and not args.repo_name
        and args.start_repo_order == 1
        and args.limit_repos == 0
    )
    timezone = ZoneInfo(args.analysis_timezone)
    grouped = list(selected.groupby(["dataset_source", "repo_name"], sort=True))
    all_repo_month: list[pd.DataFrame] = []
    all_commits: list[pd.DataFrame] = []
    all_files: list[pd.DataFrame] = []
    all_issues: list[pd.DataFrame] = []
    run_started = time.monotonic()
    for position, (_, group) in enumerate(grouped, start=1):
        logging.info(
            "Repository %d/%d: %s (%d panel months)",
            position,
            len(grouped),
            group["repo_name"].iloc[0],
            len(group),
        )
        outputs = process_repository(group, args, timezone)
        all_repo_month.append(outputs["repo_month"])
        all_commits.append(outputs["commits"])
        all_files.append(outputs["files"])
        all_issues.append(outputs["issues"])
        if position % max(args.progress_every_repos, 1) == 0 or position == len(grouped):
            elapsed = max(time.monotonic() - run_started, 0.001)
            rate = position / elapsed * 3600
            remaining = len(grouped) - position
            eta = remaining / rate if rate > 0 else math.nan
            logging.info(
                "Progress: repositories=%d/%d; rate=%.2f/hour; eta_hours=%s",
                position,
                len(grouped),
                rate,
                f"{eta:.2f}" if math.isfinite(eta) else "unknown",
            )

    repo_month = pd.concat(all_repo_month, ignore_index=True) if all_repo_month else pd.DataFrame(columns=REPO_MONTH_COLUMNS)
    nonempty_commits = [frame for frame in all_commits if not frame.empty]
    commits = pd.concat(nonempty_commits, ignore_index=True) if nonempty_commits else pd.DataFrame(columns=COMMIT_COLUMNS)
    nonempty_files = [frame for frame in all_files if not frame.empty]
    files = pd.concat(nonempty_files, ignore_index=True) if nonempty_files else pd.DataFrame(columns=FILE_COLUMNS)
    nonempty_issues = [frame for frame in all_issues if not frame.empty]
    issues = pd.concat(nonempty_issues, ignore_index=True) if nonempty_issues else pd.DataFrame(columns=ISSUE_COLUMNS)
    repo_month = repo_month.sort_values(["repo_id", "time_index"], kind="stable").reset_index(drop=True)
    if not commits.empty:
        commits = commits.sort_values(["dataset_source", "repo_name", "commit_time_epoch", "commit_sha"], kind="stable").reset_index(drop=True)
    if not files.empty:
        files = files.sort_values(["dataset_source", "repo_name", "commit_sha", "post_path"], kind="stable").reset_index(drop=True)
    reconciliation = build_reconciliation(repo_month)
    qc, summary = build_qc_and_summary(
        selected,
        repo_month,
        commits,
        files,
        issues,
        args,
        len(grouped),
        full_scope,
    )
    save_dataframe(repo_month, args.repo_month_output, REPO_MONTH_COLUMNS)
    save_dataframe(commits, args.commit_output, COMMIT_COLUMNS)
    save_dataframe(files, args.file_output, FILE_COLUMNS)
    save_dataframe(issues, args.issues_output, ISSUE_COLUMNS)
    save_dataframe(reconciliation, args.reconciliation_output, RECONCILIATION_COLUMNS)
    save_dataframe(qc, args.qc_output)
    save_dataframe(summary, args.summary_output)
    blocking_failures = qc[qc["status"].eq("fail")]
    logging.info(
        "Completed run-x-b02 added-lines collection: repo_month=%d; commits=%d; "
        "files=%d; issues=%d; blocking_failures=%d; warnings=%d",
        len(repo_month),
        len(commits),
        len(files),
        len(issues),
        len(blocking_failures),
        int(qc["status"].eq("warn").sum()),
    )
    if not blocking_failures.empty:
        logging.error("Blocking QC failures:\n%s", blocking_failures.to_string(index=False))
        return 3
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("Interrupted by user.", file=sys.stderr)
        raise SystemExit(130)
    except Exception as exc:
        logging.exception("collect_python_added_lines failed: %s", exc)
        raise SystemExit(1)
