"""
Complete Rule-to-Category Mapping for Static Analysis Warnings
====================================================================
For studying AI Coding Assistant (Cursor) impact on code quality.

Categories designed to test hypotheses about AI-generated code characteristics.
"""

# ============================================================================
# MAIN MAPPING: rule -> category
# ============================================================================

RULE_TO_CATEGORY = {
    # =========================================================================
    # 1. CODE STYLE (180 rules)
    # Hypothesis: AI may not follow consistent style
    # Expected: mixed | AI Relevance: low
    # =========================================================================
    "css:S1116": "Code Style",
    "go:S1125": "Code Style",
    "go:S1940": "Code Style",
    "ipython:S3457": "Code Style",
    "java:S1066": "Code Style",
    "java:S1116": "Code Style",
    "java:S1121": "Code Style",
    "java:S1124": "Code Style",
    "java:S1125": "Code Style",
    "java:S1126": "Code Style",
    "java:S1153": "Code Style",
    "java:S1155": "Code Style",
    "java:S1158": "Code Style",
    "java:S1197": "Code Style",
    "java:S1264": "Code Style",
    "java:S1301": "Code Style",
    "java:S1319": "Code Style",
    "java:S1488": "Code Style",
    "java:S1596": "Code Style",
    "java:S1602": "Code Style",
    "java:S1604": "Code Style",
    "java:S1611": "Code Style",
    "java:S1612": "Code Style",
    "java:S1643": "Code Style",
    "java:S1659": "Code Style",
    "java:S1858": "Code Style",
    "java:S1905": "Code Style",
    "java:S1940": "Code Style",
    "java:S2293": "Code Style",
    "java:S2692": "Code Style",
    "java:S2786": "Code Style",
    "java:S2864": "Code Style",
    "java:S3038": "Code Style",
    "java:S3457": "Code Style",
    "java:S3878": "Code Style",
    "java:S4201": "Code Style",
    "java:S4276": "Code Style",
    "java:S4719": "Code Style",
    "java:S4968": "Code Style",
    "java:S5361": "Code Style",
    "java:S5411": "Code Style",
    "java:S7158": "Code Style",
    "javascript:S1119": "Code Style",
    "javascript:S1121": "Code Style",
    "javascript:S1125": "Code Style",
    "javascript:S1126": "Code Style",
    "javascript:S1199": "Code Style",
    "javascript:S1219": "Code Style",
    "javascript:S1264": "Code Style",
    "javascript:S1301": "Code Style",
    "javascript:S1439": "Code Style",
    "javascript:S1516": "Code Style",
    "javascript:S1788": "Code Style",
    "javascript:S1940": "Code Style",
    "javascript:S2301": "Code Style",
    "javascript:S2685": "Code Style",
    "javascript:S2703": "Code Style",
    "javascript:S2814": "Code Style",
    "javascript:S2990": "Code Style",
    "javascript:S3504": "Code Style",
    "javascript:S3579": "Code Style",
    "javascript:S3686": "Code Style",
    "javascript:S3735": "Code Style",
    "javascript:S3863": "Code Style",
    "javascript:S4043": "Code Style",
    "javascript:S4138": "Code Style",
    "javascript:S6509": "Code Style",
    "javascript:S6535": "Code Style",
    "javascript:S6551": "Code Style",
    "javascript:S6582": "Code Style",
    "javascript:S6635": "Code Style",
    "javascript:S6643": "Code Style",
    "javascript:S6644": "Code Style",
    "javascript:S6645": "Code Style",
    "javascript:S6647": "Code Style",
    "javascript:S6650": "Code Style",
    "javascript:S6660": "Code Style",
    "javascript:S6661": "Code Style",
    "javascript:S6666": "Code Style",
    "javascript:S6676": "Code Style",
    "javascript:S6679": "Code Style",
    "javascript:S6836": "Code Style",
    "javascript:S6859": "Code Style",
    "javascript:S6861": "Code Style",
    "javascript:S878": "Code Style",
    "kotlin:S1066": "Code Style",
    "kotlin:S1125": "Code Style",
    "kotlin:S6510": "Code Style",
    "kotlin:S6511": "Code Style",
    "kotlin:S6514": "Code Style",
    "kotlin:S6515": "Code Style",
    "kotlin:S6517": "Code Style",
    "kotlin:S6518": "Code Style",
    "kotlin:S6519": "Code Style",
    "kotlin:S6532": "Code Style",
    "kotlin:S6615": "Code Style",
    "kotlin:S6624": "Code Style",
    "kotlin:S6625": "Code Style",
    "kotlin:S6626": "Code Style",
    "php:S1066": "Code Style",
    "php:S1110": "Code Style",
    "php:S1116": "Code Style",
    "php:S1125": "Code Style",
    "php:S1155": "Code Style",
    "php:S1185": "Code Style",
    "php:S121": "Code Style",
    "php:S1301": "Code Style",
    "php:S1488": "Code Style",
    "php:S1781": "Code Style",
    "php:S1784": "Code Style",
    "php:S1793": "Code Style",
    "php:S1940": "Code Style",
    "php:S2003": "Code Style",
    "php:S2010": "Code Style",
    "php:S3415": "Code Style",
    "php:S3801": "Code Style",
    "php:S4833": "Code Style",
    "php:S5361": "Code Style",
    "php:S5785": "Code Style",
    "php:S6600": "Code Style",
    "python:S1066": "Code Style",
    "python:S1110": "Code Style",
    "python:S1940": "Code Style",
    "python:S2772": "Code Style",
    "python:S2836": "Code Style",
    "python:S3457": "Code Style",
    "python:S5361": "Code Style",
    "python:S5685": "Code Style",
    "python:S5799": "Code Style",
    "python:S5899": "Code Style",
    "python:S5906": "Code Style",
    "python:S5918": "Code Style",
    "python:S6659": "Code Style",
    "python:S6660": "Code Style",
    "ruby:S1066": "Code Style",
    "typescript:S1119": "Code Style",
    "typescript:S1121": "Code Style",
    "typescript:S1125": "Code Style",
    "typescript:S1199": "Code Style",
    "typescript:S1264": "Code Style",
    "typescript:S1301": "Code Style",
    "typescript:S1439": "Code Style",
    "typescript:S1516": "Code Style",
    "typescript:S1788": "Code Style",
    "typescript:S1940": "Code Style",
    "typescript:S2301": "Code Style",
    "typescript:S2692": "Code Style",
    "typescript:S2870": "Code Style",
    "typescript:S2933": "Code Style",
    "typescript:S3504": "Code Style",
    "typescript:S3579": "Code Style",
    "typescript:S3735": "Code Style",
    "typescript:S3863": "Code Style",
    "typescript:S4043": "Code Style",
    "typescript:S4138": "Code Style",
    "typescript:S4140": "Code Style",
    "typescript:S4524": "Code Style",
    "typescript:S4619": "Code Style",
    "typescript:S6509": "Code Style",
    "typescript:S6522": "Code Style",
    "typescript:S6535": "Code Style",
    "typescript:S6551": "Code Style",
    "typescript:S6568": "Code Style",
    "typescript:S6582": "Code Style",
    "typescript:S6606": "Code Style",
    "typescript:S6635": "Code Style",
    "typescript:S6643": "Code Style",
    "typescript:S6644": "Code Style",
    "typescript:S6647": "Code Style",
    "typescript:S6650": "Code Style",
    "typescript:S6657": "Code Style",
    "typescript:S6660": "Code Style",
    "typescript:S6661": "Code Style",
    "typescript:S6666": "Code Style",
    "typescript:S6676": "Code Style",
    "typescript:S6679": "Code Style",
    "typescript:S6836": "Code Style",
    "typescript:S6859": "Code Style",
    "typescript:S6861": "Code Style",
    "typescript:S878": "Code Style",
    # =========================================================================
    # 2. LOGIC ERROR (171 rules)
    # Hypothesis: Core AI competency - should reduce bugs
    # Expected: decrease | AI Relevance: high
    # =========================================================================
    "go:S1763": "Logic Error",
    "go:S1764": "Logic Error",
    "go:S1862": "Logic Error",
    "go:S1871": "Logic Error",
    "go:S3923": "Logic Error",
    "ipython:S1763": "Logic Error",
    "ipython:S5727": "Logic Error",
    "ipython:S930": "Logic Error",
    "java:S1206": "Logic Error",
    "java:S131": "Logic Error",
    "java:S1656": "Logic Error",
    "java:S1751": "Logic Error",
    "java:S1763": "Logic Error",
    "java:S1871": "Logic Error",
    "java:S2097": "Logic Error",
    "java:S2153": "Logic Error",
    "java:S2159": "Logic Error",
    "java:S2178": "Logic Error",
    "java:S2184": "Logic Error",
    "java:S2201": "Logic Error",
    "java:S2234": "Logic Error",
    "java:S2259": "Logic Error",
    "java:S2589": "Logic Error",
    "java:S2676": "Logic Error",
    "java:S2681": "Logic Error",
    "java:S2789": "Logic Error",
    "java:S3599": "Logic Error",
    "java:S3699": "Logic Error",
    "java:S3923": "Logic Error",
    "java:S3973": "Logic Error",
    "java:S4348": "Logic Error",
    "java:S4973": "Logic Error",
    "java:S5998": "Logic Error",
    "java:S899": "Logic Error",
    "javascript:S1226": "Logic Error",
    "javascript:S128": "Logic Error",
    "javascript:S1515": "Logic Error",
    "javascript:S1534": "Logic Error",
    "javascript:S1656": "Logic Error",
    "javascript:S1751": "Logic Error",
    "javascript:S1763": "Logic Error",
    "javascript:S1764": "Logic Error",
    "javascript:S1848": "Logic Error",
    "javascript:S1862": "Logic Error",
    "javascript:S1871": "Logic Error",
    "javascript:S1994": "Logic Error",
    "javascript:S2189": "Logic Error",
    "javascript:S2201": "Logic Error",
    "javascript:S2234": "Logic Error",
    "javascript:S2259": "Logic Error",
    "javascript:S2432": "Logic Error",
    "javascript:S2589": "Logic Error",
    "javascript:S2681": "Logic Error",
    "javascript:S2871": "Logic Error",
    "javascript:S2999": "Logic Error",
    "javascript:S3403": "Logic Error",
    "javascript:S3500": "Logic Error",
    "javascript:S3516": "Logic Error",
    "javascript:S3531": "Logic Error",
    "javascript:S3699": "Logic Error",
    "javascript:S3799": "Logic Error",
    "javascript:S3800": "Logic Error",
    "javascript:S3923": "Logic Error",
    "javascript:S3972": "Logic Error",
    "javascript:S4158": "Logic Error",
    "javascript:S4822": "Logic Error",
    "javascript:S6523": "Logic Error",
    "javascript:S6534": "Logic Error",
    "javascript:S6544": "Logic Error",
    "javascript:S6638": "Logic Error",
    "javascript:S6671": "Logic Error",
    "javascript:S6959": "Logic Error",
    "javascript:S905": "Logic Error",
    "javascript:S930": "Logic Error",
    "kotlin:S1871": "Logic Error",
    "kotlin:S6218": "Logic Error",
    "kotlin:S6530": "Logic Error",
    "kotlin:S6619": "Logic Error",
    "kotlin:S899": "Logic Error",
    "php:S1045": "Logic Error",
    "php:S1226": "Logic Error",
    "php:S128": "Logic Error",
    "php:S131": "Logic Error",
    "php:S1656": "Logic Error",
    "php:S1763": "Logic Error",
    "php:S1848": "Logic Error",
    "php:S1871": "Logic Error",
    "php:S2014": "Logic Error",
    "php:S2761": "Logic Error",
    "php:S3699": "Logic Error",
    "php:S3973": "Logic Error",
    "php:S4143": "Logic Error",
    "php:S5797": "Logic Error",
    "php:S836": "Logic Error",
    "php:S930": "Logic Error",
    "python:S1045": "Logic Error",
    "python:S1226": "Logic Error",
    "python:S1244": "Logic Error",
    "python:S1515": "Logic Error",
    "python:S1656": "Logic Error",
    "python:S1751": "Logic Error",
    "python:S1763": "Logic Error",
    "python:S1764": "Logic Error",
    "python:S1862": "Logic Error",
    "python:S1871": "Logic Error",
    "python:S2159": "Logic Error",
    "python:S2190": "Logic Error",
    "python:S2201": "Logic Error",
    "python:S2711": "Logic Error",
    "python:S3403": "Logic Error",
    "python:S3516": "Logic Error",
    "python:S3699": "Logic Error",
    "python:S3827": "Logic Error",
    "python:S3862": "Logic Error",
    "python:S3923": "Logic Error",
    "python:S3981": "Logic Error",
    "python:S4143": "Logic Error",
    "python:S5607": "Logic Error",
    "python:S5642": "Logic Error",
    "python:S5644": "Logic Error",
    "python:S5719": "Logic Error",
    "python:S5727": "Logic Error",
    "python:S5795": "Logic Error",
    "python:S5796": "Logic Error",
    "python:S5797": "Logic Error",
    "python:S5807": "Logic Error",
    "python:S5905": "Logic Error",
    "python:S5915": "Logic Error",
    "python:S6662": "Logic Error",
    "python:S6663": "Logic Error",
    "python:S905": "Logic Error",
    "python:S930": "Logic Error",
    "ruby:S131": "Logic Error",
    "typescript:S1226": "Logic Error",
    "typescript:S128": "Logic Error",
    "typescript:S1529": "Logic Error",
    "typescript:S1534": "Logic Error",
    "typescript:S1656": "Logic Error",
    "typescript:S1751": "Logic Error",
    "typescript:S1763": "Logic Error",
    "typescript:S1764": "Logic Error",
    "typescript:S1848": "Logic Error",
    "typescript:S1862": "Logic Error",
    "typescript:S1871": "Logic Error",
    "typescript:S1994": "Logic Error",
    "typescript:S2201": "Logic Error",
    "typescript:S2234": "Logic Error",
    "typescript:S2589": "Logic Error",
    "typescript:S2681": "Logic Error",
    "typescript:S2871": "Logic Error",
    "typescript:S2999": "Logic Error",
    "typescript:S3516": "Logic Error",
    "typescript:S3531": "Logic Error",
    "typescript:S3699": "Logic Error",
    "typescript:S3799": "Logic Error",
    "typescript:S3854": "Logic Error",
    "typescript:S3923": "Logic Error",
    "typescript:S3972": "Logic Error",
    "typescript:S3981": "Logic Error",
    "typescript:S4143": "Logic Error",
    "typescript:S4158": "Logic Error",
    "typescript:S4275": "Logic Error",
    "typescript:S4822": "Logic Error",
    "typescript:S6523": "Logic Error",
    "typescript:S6534": "Logic Error",
    "typescript:S6544": "Logic Error",
    "typescript:S6638": "Logic Error",
    "typescript:S6671": "Logic Error",
    "typescript:S6959": "Logic Error",
    "typescript:S905": "Logic Error",
    "typescript:S930": "Logic Error",
    # =========================================================================
    # 3. CODE HYGIENE (74 rules)
    # Hypothesis: AI scaffolding leaves artifacts (TODOs, commented code)
    # Expected: increase | AI Relevance: high
    # =========================================================================
    "Web:AvoidCommentedOutCodeCheck": "Code Hygiene",
    "Web:S1134": "Code Hygiene",
    "Web:S1135": "Code Hygiene",
    "css:S125": "Code Hygiene",
    "docker:S1135": "Code Hygiene",
    "go:S1134": "Code Hygiene",
    "go:S1135": "Code Hygiene",
    "ipython:S1135": "Code Hygiene",
    "ipython:S1172": "Code Hygiene",
    "ipython:S125": "Code Hygiene",
    "ipython:S3626": "Code Hygiene",
    "java:S1068": "Code Hygiene",
    "java:S1128": "Code Hygiene",
    "java:S1134": "Code Hygiene",
    "java:S1135": "Code Hygiene",
    "java:S1144": "Code Hygiene",
    "java:S1172": "Code Hygiene",
    "java:S125": "Code Hygiene",
    "java:S1450": "Code Hygiene",
    "java:S1481": "Code Hygiene",
    "java:S1854": "Code Hygiene",
    "java:S3400": "Code Hygiene",
    "java:S3626": "Code Hygiene",
    "javascript:S1068": "Code Hygiene",
    "javascript:S1128": "Code Hygiene",
    "javascript:S1134": "Code Hygiene",
    "javascript:S1135": "Code Hygiene",
    "javascript:S125": "Code Hygiene",
    "javascript:S1481": "Code Hygiene",
    "javascript:S1854": "Code Hygiene",
    "javascript:S2310": "Code Hygiene",
    "javascript:S3626": "Code Hygiene",
    "javascript:S4030": "Code Hygiene",
    "javascript:S4165": "Code Hygiene",
    "kotlin:S1128": "Code Hygiene",
    "kotlin:S1135": "Code Hygiene",
    "kotlin:S1144": "Code Hygiene",
    "kotlin:S1172": "Code Hygiene",
    "kotlin:S1481": "Code Hygiene",
    "kubernetes:S1135": "Code Hygiene",
    "php:S1068": "Code Hygiene",
    "php:S1134": "Code Hygiene",
    "php:S1135": "Code Hygiene",
    "php:S1144": "Code Hygiene",
    "php:S1172": "Code Hygiene",
    "php:S125": "Code Hygiene",
    "php:S1481": "Code Hygiene",
    "php:S1854": "Code Hygiene",
    "php:S3626": "Code Hygiene",
    "python:S1134": "Code Hygiene",
    "python:S1135": "Code Hygiene",
    "python:S1144": "Code Hygiene",
    "python:S1172": "Code Hygiene",
    "python:S125": "Code Hygiene",
    "python:S1481": "Code Hygiene",
    "python:S1854": "Code Hygiene",
    "python:S3626": "Code Hygiene",
    "python:S4487": "Code Hygiene",
    "python:S5603": "Code Hygiene",
    "ruby:S1135": "Code Hygiene",
    "ruby:S1172": "Code Hygiene",
    "ruby:S1481": "Code Hygiene",
    "terraform:S1135": "Code Hygiene",
    "typescript:S1068": "Code Hygiene",
    "typescript:S1128": "Code Hygiene",
    "typescript:S1134": "Code Hygiene",
    "typescript:S1135": "Code Hygiene",
    "typescript:S125": "Code Hygiene",
    "typescript:S1854": "Code Hygiene",
    "typescript:S2310": "Code Hygiene",
    "typescript:S3626": "Code Hygiene",
    "typescript:S4030": "Code Hygiene",
    "typescript:S4165": "Code Hygiene",
    "xml:S125": "Code Hygiene",
    # =========================================================================
    # 4. ACCESSIBILITY (63 rules)
    # Hypothesis: AI training data underrepresents a11y patterns
    # Expected: increase | AI Relevance: medium
    # =========================================================================
    "Web:FrameWithoutTitleCheck": "Accessibility",
    "Web:ImgWithoutAltCheck": "Accessibility",
    "Web:MouseEventWithoutKeyboardEquivalentCheck": "Accessibility",
    "Web:PageWithoutTitleCheck": "Accessibility",
    "Web:S4084": "Accessibility",
    "Web:S5254": "Accessibility",
    "Web:S5255": "Accessibility",
    "Web:S5256": "Accessibility",
    "Web:S5257": "Accessibility",
    "Web:S6793": "Accessibility",
    "Web:S6807": "Accessibility",
    "Web:S6819": "Accessibility",
    "Web:S6821": "Accessibility",
    "Web:S6822": "Accessibility",
    "Web:S6825": "Accessibility",
    "Web:S6827": "Accessibility",
    "Web:S6840": "Accessibility",
    "Web:S6841": "Accessibility",
    "Web:S6842": "Accessibility",
    "Web:S6843": "Accessibility",
    "Web:S6844": "Accessibility",
    "Web:S6845": "Accessibility",
    "Web:S6846": "Accessibility",
    "Web:S6847": "Accessibility",
    "Web:S6848": "Accessibility",
    "Web:S6850": "Accessibility",
    "Web:S6851": "Accessibility",
    "Web:S6853": "Accessibility",
    "Web:TableHeaderHasIdOrScopeCheck": "Accessibility",
    "javascript:S1082": "Accessibility",
    "javascript:S4084": "Accessibility",
    "javascript:S5254": "Accessibility",
    "javascript:S6819": "Accessibility",
    "javascript:S6825": "Accessibility",
    "javascript:S6827": "Accessibility",
    "javascript:S6842": "Accessibility",
    "javascript:S6844": "Accessibility",
    "javascript:S6848": "Accessibility",
    "javascript:S6853": "Accessibility",
    "typescript:S1077": "Accessibility",
    "typescript:S1082": "Accessibility",
    "typescript:S1090": "Accessibility",
    "typescript:S4084": "Accessibility",
    "typescript:S5254": "Accessibility",
    "typescript:S5256": "Accessibility",
    "typescript:S6807": "Accessibility",
    "typescript:S6811": "Accessibility",
    "typescript:S6819": "Accessibility",
    "typescript:S6821": "Accessibility",
    "typescript:S6822": "Accessibility",
    "typescript:S6825": "Accessibility",
    "typescript:S6827": "Accessibility",
    "typescript:S6841": "Accessibility",
    "typescript:S6842": "Accessibility",
    "typescript:S6843": "Accessibility",
    "typescript:S6844": "Accessibility",
    "typescript:S6845": "Accessibility",
    "typescript:S6847": "Accessibility",
    "typescript:S6848": "Accessibility",
    "typescript:S6850": "Accessibility",
    "typescript:S6851": "Accessibility",
    "typescript:S6852": "Accessibility",
    "typescript:S6853": "Accessibility",
    # =========================================================================
    # 5. REGEX ISSUES (57 rules)
    # Hypothesis: AI-generated regex may be complex or incorrect
    # Expected: increase | AI Relevance: high
    # =========================================================================
    "ipython:S5869": "Regex Issues",
    "ipython:S6353": "Regex Issues",
    "java:S5843": "Regex Issues",
    "java:S5869": "Regex Issues",
    "java:S6353": "Regex Issues",
    "javascript:S5842": "Regex Issues",
    "javascript:S5843": "Regex Issues",
    "javascript:S5850": "Regex Issues",
    "javascript:S5868": "Regex Issues",
    "javascript:S5869": "Regex Issues",
    "javascript:S6019": "Regex Issues",
    "javascript:S6035": "Regex Issues",
    "javascript:S6323": "Regex Issues",
    "javascript:S6324": "Regex Issues",
    "javascript:S6325": "Regex Issues",
    "javascript:S6326": "Regex Issues",
    "javascript:S6353": "Regex Issues",
    "javascript:S6397": "Regex Issues",
    "php:S5842": "Regex Issues",
    "php:S5843": "Regex Issues",
    "php:S5850": "Regex Issues",
    "php:S5857": "Regex Issues",
    "php:S5869": "Regex Issues",
    "php:S6019": "Regex Issues",
    "php:S6035": "Regex Issues",
    "php:S6353": "Regex Issues",
    "php:S6395": "Regex Issues",
    "php:S6396": "Regex Issues",
    "python:S5842": "Regex Issues",
    "python:S5843": "Regex Issues",
    "python:S5850": "Regex Issues",
    "python:S5855": "Regex Issues",
    "python:S5857": "Regex Issues",
    "python:S5869": "Regex Issues",
    "python:S5996": "Regex Issues",
    "python:S6019": "Regex Issues",
    "python:S6035": "Regex Issues",
    "python:S6323": "Regex Issues",
    "python:S6326": "Regex Issues",
    "python:S6353": "Regex Issues",
    "python:S6395": "Regex Issues",
    "python:S6396": "Regex Issues",
    "python:S6397": "Regex Issues",
    "typescript:S5842": "Regex Issues",
    "typescript:S5843": "Regex Issues",
    "typescript:S5850": "Regex Issues",
    "typescript:S5860": "Regex Issues",
    "typescript:S5869": "Regex Issues",
    "typescript:S6019": "Regex Issues",
    "typescript:S6035": "Regex Issues",
    "typescript:S6323": "Regex Issues",
    "typescript:S6324": "Regex Issues",
    "typescript:S6325": "Regex Issues",
    "typescript:S6331": "Regex Issues",
    "typescript:S6351": "Regex Issues",
    "typescript:S6353": "Regex Issues",
    "typescript:S6397": "Regex Issues",
    # =========================================================================
    # 6. CODE COMPLEXITY (52 rules)
    # Hypothesis: Iterative AI edits may increase nesting/complexity
    # Expected: increase | AI Relevance: high
    # =========================================================================
    "azureresourcemanager:S1192": "Code Complexity",
    "go:S107": "Code Complexity",
    "go:S1192": "Code Complexity",
    "go:S1479": "Code Complexity",
    "go:S3776": "Code Complexity",
    "go:S4144": "Code Complexity",
    "ipython:S1192": "Code Complexity",
    "ipython:S3358": "Code Complexity",
    "ipython:S3776": "Code Complexity",
    "java:S107": "Code Complexity",
    "java:S1192": "Code Complexity",
    "java:S135": "Code Complexity",
    "java:S3358": "Code Complexity",
    "java:S3776": "Code Complexity",
    "java:S4144": "Code Complexity",
    "java:S6541": "Code Complexity",
    "javascript:S107": "Code Complexity",
    "javascript:S1479": "Code Complexity",
    "javascript:S2004": "Code Complexity",
    "javascript:S3358": "Code Complexity",
    "javascript:S3776": "Code Complexity",
    "javascript:S4144": "Code Complexity",
    "javascript:S4624": "Code Complexity",
    "kotlin:S107": "Code Complexity",
    "kotlin:S1192": "Code Complexity",
    "kotlin:S3776": "Code Complexity",
    "php:S107": "Code Complexity",
    "php:S110": "Code Complexity",
    "php:S1142": "Code Complexity",
    "php:S1192": "Code Complexity",
    "php:S127": "Code Complexity",
    "php:S138": "Code Complexity",
    "php:S1448": "Code Complexity",
    "php:S3358": "Code Complexity",
    "php:S3776": "Code Complexity",
    "php:S4144": "Code Complexity",
    "python:S107": "Code Complexity",
    "python:S1192": "Code Complexity",
    "python:S3358": "Code Complexity",
    "python:S3776": "Code Complexity",
    "python:S4144": "Code Complexity",
    "ruby:S107": "Code Complexity",
    "ruby:S1192": "Code Complexity",
    "ruby:S3776": "Code Complexity",
    "ruby:S4144": "Code Complexity",
    "typescript:S107": "Code Complexity",
    "typescript:S1479": "Code Complexity",
    "typescript:S2004": "Code Complexity",
    "typescript:S3358": "Code Complexity",
    "typescript:S3776": "Code Complexity",
    "typescript:S4144": "Code Complexity",
    "typescript:S4624": "Code Complexity",
    # =========================================================================
    # 7. NAMING CONVENTIONS (51 rules)
    # Hypothesis: AI may not follow project conventions
    # Expected: mixed | AI Relevance: low
    # =========================================================================
    "go:S100": "Naming Conventions",
    "go:S117": "Naming Conventions",
    "ipython:S117": "Naming Conventions",
    "ipython:S1542": "Naming Conventions",
    "ipython:S1700": "Naming Conventions",
    "ipython:S5720": "Naming Conventions",
    "ipython:S5806": "Naming Conventions",
    "java:S100": "Naming Conventions",
    "java:S101": "Naming Conventions",
    "java:S1117": "Naming Conventions",
    "java:S115": "Naming Conventions",
    "java:S116": "Naming Conventions",
    "java:S117": "Naming Conventions",
    "java:S119": "Naming Conventions",
    "java:S120": "Naming Conventions",
    "java:S1223": "Naming Conventions",
    "java:S1700": "Naming Conventions",
    "java:S1845": "Naming Conventions",
    "java:S2166": "Naming Conventions",
    "java:S3008": "Naming Conventions",
    "java:S6213": "Naming Conventions",
    "javascript:S101": "Naming Conventions",
    "javascript:S2137": "Naming Conventions",
    "javascript:S2392": "Naming Conventions",
    "javascript:S2430": "Naming Conventions",
    "kotlin:S100": "Naming Conventions",
    "php:S100": "Naming Conventions",
    "php:S101": "Naming Conventions",
    "php:S114": "Naming Conventions",
    "php:S115": "Naming Conventions",
    "php:S116": "Naming Conventions",
    "php:S117": "Naming Conventions",
    "php:S2166": "Naming Conventions",
    "python:S100": "Naming Conventions",
    "python:S101": "Naming Conventions",
    "python:S116": "Naming Conventions",
    "python:S117": "Naming Conventions",
    "python:S1542": "Naming Conventions",
    "python:S1700": "Naming Conventions",
    "python:S1845": "Naming Conventions",
    "python:S2710": "Naming Conventions",
    "python:S5720": "Naming Conventions",
    "python:S5806": "Naming Conventions",
    "ruby:S100": "Naming Conventions",
    "ruby:S101": "Naming Conventions",
    "ruby:S117": "Naming Conventions",
    "terraform:S6273": "Naming Conventions",
    "typescript:S101": "Naming Conventions",
    "typescript:S2137": "Naming Conventions",
    "typescript:S2392": "Naming Conventions",
    "typescript:S2430": "Naming Conventions",
    # =========================================================================
    # 8. REACT PATTERNS (43 rules)
    # Hypothesis: AI reproduces anti-patterns from training data
    # Expected: mixed | AI Relevance: high
    # =========================================================================
    "javascript:S6440": "React Patterns",
    "javascript:S6441": "React Patterns",
    "javascript:S6443": "React Patterns",
    "javascript:S6477": "React Patterns",
    "javascript:S6478": "React Patterns",
    "javascript:S6479": "React Patterns",
    "javascript:S6481": "React Patterns",
    "javascript:S6746": "React Patterns",
    "javascript:S6747": "React Patterns",
    "javascript:S6748": "React Patterns",
    "javascript:S6749": "React Patterns",
    "javascript:S6754": "React Patterns",
    "javascript:S6756": "React Patterns",
    "javascript:S6757": "React Patterns",
    "javascript:S6767": "React Patterns",
    "javascript:S6770": "React Patterns",
    "javascript:S6772": "React Patterns",
    "javascript:S6774": "React Patterns",
    "javascript:S6775": "React Patterns",
    "javascript:S6788": "React Patterns",
    "javascript:S6791": "React Patterns",
    "typescript:S6438": "React Patterns",
    "typescript:S6439": "React Patterns",
    "typescript:S6440": "React Patterns",
    "typescript:S6441": "React Patterns",
    "typescript:S6443": "React Patterns",
    "typescript:S6477": "React Patterns",
    "typescript:S6478": "React Patterns",
    "typescript:S6479": "React Patterns",
    "typescript:S6481": "React Patterns",
    "typescript:S6486": "React Patterns",
    "typescript:S6747": "React Patterns",
    "typescript:S6748": "React Patterns",
    "typescript:S6749": "React Patterns",
    "typescript:S6754": "React Patterns",
    "typescript:S6756": "React Patterns",
    "typescript:S6757": "React Patterns",
    "typescript:S6767": "React Patterns",
    "typescript:S6770": "React Patterns",
    "typescript:S6772": "React Patterns",
    "typescript:S6775": "React Patterns",
    "typescript:S6791": "React Patterns",
    "typescript:S6957": "React Patterns",
    # =========================================================================
    # 9. OOP/DESIGN (35 rules)
    # Hypothesis: AI may not follow OOP best practices
    # Expected: mixed | AI Relevance: medium
    # =========================================================================
    "ipython:S2208": "OOP/Design",
    "java:S106": "OOP/Design",
    "java:S1075": "OOP/Design",
    "java:S1104": "OOP/Design",
    "java:S1118": "OOP/Design",
    "java:S1165": "OOP/Design",
    "java:S1168": "OOP/Design",
    "java:S1170": "OOP/Design",
    "java:S1171": "OOP/Design",
    "java:S1214": "OOP/Design",
    "java:S1220": "OOP/Design",
    "java:S1444": "OOP/Design",
    "java:S1598": "OOP/Design",
    "java:S1948": "OOP/Design",
    "java:S2129": "OOP/Design",
    "java:S2130": "OOP/Design",
    "java:S2140": "OOP/Design",
    "java:S2160": "OOP/Design",
    "java:S2209": "OOP/Design",
    "java:S2386": "OOP/Design",
    "java:S2440": "OOP/Design",
    "java:S2479": "OOP/Design",
    "java:S2975": "OOP/Design",
    "java:S3252": "OOP/Design",
    "java:S3398": "OOP/Design",
    "java:S5993": "OOP/Design",
    "java:S6548": "OOP/Design",
    "php:S3360": "OOP/Design",
    "python:S1607": "OOP/Design",
    "python:S2208": "OOP/Design",
    "python:S2638": "OOP/Design",
    "python:S5717": "OOP/Design",
    "python:S5780": "OOP/Design",
    "typescript:S1444": "OOP/Design",
    "typescript:S1607": "OOP/Design",
    # =========================================================================
    # 10. SECURITY (34 rules)
    # Hypothesis: AI may reproduce insecure patterns
    # Expected: mixed | AI Relevance: medium
    # =========================================================================
    "docker:S6437": "Security",
    "java:S2115": "Security",
    "java:S3010": "Security",
    "java:S3011": "Security",
    "javascript:S2819": "Security",
    "javascript:S4426": "Security",
    "javascript:S4830": "Security",
    "javascript:S5542": "Security",
    "kubernetes:S6864": "Security",
    "kubernetes:S6865": "Security",
    "kubernetes:S6867": "Security",
    "kubernetes:S6870": "Security",
    "php:S3011": "Security",
    "python:S2053": "Security",
    "python:S2755": "Security",
    "python:S4830": "Security",
    "python:S5445": "Security",
    "python:S5527": "Security",
    "python:S5659": "Security",
    "python:S6779": "Security",
    "secrets:S6334": "Security",
    "secrets:S6335": "Security",
    "secrets:S6687": "Security",
    "secrets:S6693": "Security",
    "secrets:S6697": "Security",
    "secrets:S6698": "Security",
    "secrets:S6703": "Security",
    "secrets:S6706": "Security",
    "secrets:S6739": "Security",
    "terraform:S4423": "Security",
    "terraform:S6321": "Security",
    "typescript:S2598": "Security",
    "typescript:S2819": "Security",
    "typescript:S5542": "Security",
    # =========================================================================
    # 11. ERROR HANDLING (32 rules)
    # Hypothesis: AI may generate incomplete error handling
    # Expected: increase | AI Relevance: medium
    # =========================================================================
    "go:S108": "Error Handling",
    "ipython:S108": "Error Handling",
    "java:S108": "Error Handling",
    "java:S112": "Error Handling",
    "java:S1130": "Error Handling",
    "java:S1141": "Error Handling",
    "java:S2142": "Error Handling",
    "java:S2147": "Error Handling",
    "javascript:S108": "Error Handling",
    "javascript:S1143": "Error Handling",
    "javascript:S2737": "Error Handling",
    "javascript:S3696": "Error Handling",
    "kotlin:S108": "Error Handling",
    "php:S108": "Error Handling",
    "php:S112": "Error Handling",
    "php:S5713": "Error Handling",
    "python:S108": "Error Handling",
    "python:S112": "Error Handling",
    "python:S1143": "Error Handling",
    "python:S2737": "Error Handling",
    "python:S3984": "Error Handling",
    "python:S5632": "Error Handling",
    "python:S5709": "Error Handling",
    "python:S5713": "Error Handling",
    "python:S5747": "Error Handling",
    "python:S5754": "Error Handling",
    "ruby:S108": "Error Handling",
    "typescript:S108": "Error Handling",
    "typescript:S1143": "Error Handling",
    "typescript:S2486": "Error Handling",
    "typescript:S2737": "Error Handling",
    "typescript:S3696": "Error Handling",
    # =========================================================================
    # 12. TYPE SAFETY (29 rules)
    # Hypothesis: AI may over/under-specify types
    # Expected: mixed | AI Relevance: medium
    # =========================================================================
    "ipython:S5886": "Type Safety",
    "java:S1452": "Type Safety",
    "java:S2326": "Type Safety",
    "java:S3740": "Type Safety",
    "javascript:S1533": "Type Safety",
    "javascript:S3782": "Type Safety",
    "python:S5655": "Type Safety",
    "python:S5864": "Type Safety",
    "python:S5886": "Type Safety",
    "python:S5890": "Type Safety",
    "python:S5914": "Type Safety",
    "typescript:S1533": "Type Safety",
    "typescript:S4323": "Type Safety",
    "typescript:S4325": "Type Safety",
    "typescript:S4335": "Type Safety",
    "typescript:S4621": "Type Safety",
    "typescript:S4623": "Type Safety",
    "typescript:S4782": "Type Safety",
    "typescript:S6550": "Type Safety",
    "typescript:S6564": "Type Safety",
    "typescript:S6565": "Type Safety",
    "typescript:S6569": "Type Safety",
    "typescript:S6571": "Type Safety",
    "typescript:S6572": "Type Safety",
    "typescript:S6578": "Type Safety",
    "typescript:S6583": "Type Safety",
    "typescript:S6590": "Type Safety",
    "typescript:S6598": "Type Safety",
    "typescript:S6759": "Type Safety",
    # =========================================================================
    # 13. API USAGE (28 rules)
    # Hypothesis: AI training data contains outdated patterns
    # Expected: increase | AI Relevance: medium
    # =========================================================================
    "Web:S1827": "API Usage",
    "Web:UnsupportedTagsInHtml5Check": "API Usage",
    "java:S1123": "API Usage",
    "java:S1133": "API Usage",
    "java:S1161": "API Usage",
    "java:S1191": "API Usage",
    "java:S1874": "API Usage",
    "java:S5738": "API Usage",
    "javascript:S1874": "API Usage",
    "javascript:S6557": "API Usage",
    "javascript:S6594": "API Usage",
    "javascript:S6627": "API Usage",
    "javascript:S6653": "API Usage",
    "javascript:S6654": "API Usage",
    "kotlin:S1133": "API Usage",
    "kotlin:S1874": "API Usage",
    "kubernetes:S1874": "API Usage",
    "php:S1874": "API Usage",
    "python:S6553": "API Usage",
    "python:S6559": "API Usage",
    "python:S6887": "API Usage",
    "python:S6903": "API Usage",
    "typescript:S1874": "API Usage",
    "typescript:S6557": "API Usage",
    "typescript:S6594": "API Usage",
    "typescript:S6627": "API Usage",
    "typescript:S6653": "API Usage",
    "typescript:S6654": "API Usage",
    # =========================================================================
    # 14. INFRASTRUCTURE (24 rules)
    # Hypothesis: AI may generate suboptimal container configs
    # Expected: mixed | AI Relevance: medium
    # =========================================================================
    "azureresourcemanager:S6874": "Infrastructure",
    "azureresourcemanager:S6975": "Infrastructure",
    "docker:S6476": "Infrastructure",
    "docker:S6570": "Infrastructure",
    "docker:S6573": "Infrastructure",
    "docker:S6579": "Infrastructure",
    "docker:S6584": "Infrastructure",
    "docker:S6587": "Infrastructure",
    "docker:S6589": "Infrastructure",
    "docker:S6595": "Infrastructure",
    "docker:S6596": "Infrastructure",
    "docker:S6597": "Infrastructure",
    "docker:S7018": "Infrastructure",
    "docker:S7019": "Infrastructure",
    "docker:S7020": "Infrastructure",
    "docker:S7026": "Infrastructure",
    "docker:S7029": "Infrastructure",
    "docker:S7031": "Infrastructure",
    "kubernetes:S6596": "Infrastructure",
    "kubernetes:S6873": "Infrastructure",
    "kubernetes:S6892": "Infrastructure",
    "kubernetes:S6893": "Infrastructure",
    "kubernetes:S6897": "Infrastructure",
    "kubernetes:S6907": "Infrastructure",
    # =========================================================================
    # 15. CONCURRENCY (17 rules)
    # Hypothesis: AI may not handle async correctly
    # Expected: mixed | AI Relevance: medium
    # =========================================================================
    "java:S1149": "Concurrency",
    "java:S2119": "Concurrency",
    "java:S2168": "Concurrency",
    "java:S2696": "Concurrency",
    "java:S2885": "Concurrency",
    "java:S2886": "Concurrency",
    "java:S3014": "Concurrency",
    "java:S3064": "Concurrency",
    "java:S3077": "Concurrency",
    "java:S3078": "Concurrency",
    "java:S5164": "Concurrency",
    "javascript:S4123": "Concurrency",
    "javascript:S4634": "Concurrency",
    "javascript:S7059": "Concurrency",
    "typescript:S4123": "Concurrency",
    "typescript:S4634": "Concurrency",
    "typescript:S7059": "Concurrency",
    # =========================================================================
    # 16. EMPTY/INCOMPLETE CODE (14 rules)
    # Hypothesis: AI may generate stubs without implementation
    # Expected: increase | AI Relevance: high
    # =========================================================================
    "css:S4658": "Empty/Incomplete Code",
    "css:S4667": "Empty/Incomplete Code",
    "go:S1186": "Empty/Incomplete Code",
    "ipython:S1186": "Empty/Incomplete Code",
    "java:S1186": "Empty/Incomplete Code",
    "java:S2094": "Empty/Incomplete Code",
    "javascript:S1186": "Empty/Incomplete Code",
    "javascript:S2094": "Empty/Incomplete Code",
    "kotlin:S1186": "Empty/Incomplete Code",
    "php:S1186": "Empty/Incomplete Code",
    "python:S1186": "Empty/Incomplete Code",
    "ruby:S1186": "Empty/Incomplete Code",
    "typescript:S1186": "Empty/Incomplete Code",
    "typescript:S2094": "Empty/Incomplete Code",
    # =========================================================================
    # 17. CSS ISSUES (13 rules)
    # Hypothesis: AI may generate invalid CSS
    # Expected: mixed | AI Relevance: medium
    # =========================================================================
    "css:S4648": "CSS Issues",
    "css:S4649": "CSS Issues",
    "css:S4650": "CSS Issues",
    "css:S4651": "CSS Issues",
    "css:S4653": "CSS Issues",
    "css:S4654": "CSS Issues",
    "css:S4656": "CSS Issues",
    "css:S4657": "CSS Issues",
    "css:S4659": "CSS Issues",
    "css:S4660": "CSS Issues",
    "css:S4662": "CSS Issues",
    "css:S4666": "CSS Issues",
    "css:S4670": "CSS Issues",
    # =========================================================================
    # 18. DATA SCIENCE (12 rules)
    # Hypothesis: AI may miss ML best practices
    # Expected: mixed | AI Relevance: medium
    # =========================================================================
    "ipython:S6709": "Data Science",
    "ipython:S6734": "Data Science",
    "ipython:S6969": "Data Science",
    "python:S6709": "Data Science",
    "python:S6711": "Data Science",
    "python:S6729": "Data Science",
    "python:S6730": "Data Science",
    "python:S6734": "Data Science",
    "python:S6735": "Data Science",
    "python:S6929": "Data Science",
    "python:S6973": "Data Science",
    "python:S6984": "Data Science",
    # =========================================================================
    # 19. RESOURCE MANAGEMENT (4 rules)
    # Hypothesis: AI may not properly manage resources
    # Expected: mixed | AI Relevance: low
    # =========================================================================
    "java:S2093": "Resource Management",
    "java:S2095": "Resource Management",
    "java:S4042": "Resource Management",
    "java:S4087": "Resource Management",
    # =========================================================================
    # 20. HTML STRUCTURE (4 rules)
    # Hypothesis: AI may generate invalid HTML structure
    # Expected: mixed | AI Relevance: low
    # =========================================================================
    "Web:DoctypePresenceCheck": "HTML Structure",
    "Web:ItemTagNotWithinContainerTagCheck": "HTML Structure",
    "Web:MetaRefreshCheck": "HTML Structure",
    "Web:S4645": "HTML Structure",
}


def get_category(rule: str) -> str:
    """Get category for a rule, returns 'Other' if not mapped."""
    return RULE_TO_CATEGORY.get(rule, "Other")


def categorize_dataframe(df, rule_column="rule"):
    """Add category column to a dataframe."""
    df = df.copy()
    df["category"] = df[rule_column].map(get_category)
    return df


if __name__ == "__main__":
    from collections import Counter
    from pathlib import Path

    import pandas as pd

    # Get paths
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent
    input_file = project_dir / "data" / "sonarqube_warning_definitions.csv"
    output_file = project_dir / "data" / "sonarqube_warning_definitions.csv"

    # Read the CSV file
    print(f"Reading from: {input_file}")
    df = pd.read_csv(input_file)
    print(f"Loaded {len(df)} rules")

    # Add category column
    df["category"] = df["rule"].map(get_category)

    # Save to new file
    df.to_csv(output_file, index=False)
    print(f"\nSaved categorized data to: {output_file}")

    # Print summary statistics
    print("\n" + "=" * 70)
    print("CATEGORY SUMMARY")
    print("=" * 70)

    category_counts = df["category"].value_counts()
    for cat, count in category_counts.items():
        print(f"\n{cat}: {count} rules")

    print("\n" + "=" * 70)
    print(f"Total rules in CSV: {len(df)}")
    print(f"Total rules mapped: {len(RULE_TO_CATEGORY)}")
    print(f"Rules categorized as 'Other': {(df['category'] == 'Other').sum()}")
    print("=" * 70)
