#!/usr/bin/env python3
"""
Compare baseline event_month with Git-history adoption_month.

Inputs:
  - Candidate/treatment repo file, e.g. ai_adopt_repo_python.csv
  - Git-history adoption file, e.g. ai_adoption_dates.csv

Output:
  - adoption_month_check.csv

This script helps verify whether the event month used for DiD matches the
actual adoption month detected from repository history.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare candidate event_month with detected adoption_month."
    )

    parser.add_argument(
        "--candidate-file",
        required=True,
        type=Path,
        help="Candidate repo CSV containing repo_name and event_month.",
    )

    parser.add_argument(
        "--adoption-file",
        required=True,
        type=Path,
        help="Adoption-date CSV generated by analyze_repos_v2.py.",
    )

    parser.add_argument(
        "--output-match-file",
        required=True,
        type=Path,
        help="Output CSV path for event/adoption month comparison.",
    )

    parser.add_argument(
        "--repo-column",
        default="repo_name",
        help="Repository column name. Default: repo_name.",
    )

    parser.add_argument(
        "--event-column",
        default="event_month",
        help="Candidate event-month column name. Default: event_month.",
    )

    parser.add_argument(
        "--adoption-column",
        default="adoption_month",
        help="Detected adoption-month column name. Default: adoption_month.",
    )

    return parser.parse_args()


def clean_month(series: pd.Series) -> pd.Series:
    return (
        series.astype(str)
        .str.strip()
        .str[:7]
        .replace({"nan": pd.NA, "NaT": pd.NA, "None": pd.NA, "": pd.NA})
    )


def main() -> None:
    args = parse_args()

    candidate_file = args.candidate_file.expanduser().resolve()
    adoption_file = args.adoption_file.expanduser().resolve()
    output_file = args.output_match_file.expanduser().resolve()

    if not candidate_file.exists():
        raise SystemExit(f"Candidate file not found: {candidate_file}")

    if not adoption_file.exists():
        raise SystemExit(f"Adoption file not found: {adoption_file}")

    candidates = pd.read_csv(candidate_file)
    adoption = pd.read_csv(adoption_file)

    required_candidate_cols = {args.repo_column, args.event_column}
    missing_candidate_cols = required_candidate_cols - set(candidates.columns)
    if missing_candidate_cols:
        raise SystemExit(
            f"Missing candidate columns: {sorted(missing_candidate_cols)}"
        )

    required_adoption_cols = {args.repo_column, args.adoption_column}
    missing_adoption_cols = required_adoption_cols - set(adoption.columns)
    if missing_adoption_cols:
        raise SystemExit(
            f"Missing adoption columns: {sorted(missing_adoption_cols)}"
        )

    keep_adoption_cols = [
        args.repo_column,
        args.adoption_column,
        "adoption_date",
        "adoption_commit",
        "adoption_tool",
        "evidence_paths",
        "evidence_type",
        "confidence",
        "message",
    ]
    keep_adoption_cols = [c for c in keep_adoption_cols if c in adoption.columns]

    adoption_small = adoption[keep_adoption_cols].drop_duplicates(
        subset=[args.repo_column],
        keep="first",
    )

    df = candidates.merge(
        adoption_small,
        on=args.repo_column,
        how="left",
        sort=False,
    )

    df["event_month_clean"] = clean_month(df[args.event_column])
    df["adoption_month_clean"] = clean_month(df[args.adoption_column])

    df["event_month_match"] = (
        df["event_month_clean"].eq(df["adoption_month_clean"])
        & df["event_month_clean"].notna()
        & df["adoption_month_clean"].notna()
    )

    df["adoption_month_missing"] = df["adoption_month_clean"].isna()

    df["month_difference"] = (
        pd.PeriodIndex(df["adoption_month_clean"], freq="M").astype("int64")
        - pd.PeriodIndex(df["event_month_clean"], freq="M").astype("int64")
    )

    df.loc[df["adoption_month_missing"], "month_difference"] = pd.NA

    output_file.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_file, index=False)

    total = len(df)
    matched = int(df["event_month_match"].sum())
    missing = int(df["adoption_month_missing"].sum())
    mismatched = total - matched - missing

    print("Candidate file:", candidate_file)
    print("Adoption file: ", adoption_file)
    print("Output file:   ", output_file)
    print()
    print("Treatment repos:", total)
    print("Matched event/adoption month:", matched)
    print("Mismatched event/adoption month:", mismatched)
    print("Missing adoption month:", missing)
    print()

    show_cols = [
        "rank",
        args.repo_column,
        args.event_column,
        args.adoption_column,
        "adoption_date",
        "event_month_match",
        "month_difference",
        "confidence",
        "evidence_paths",
    ]
    show_cols = [c for c in show_cols if c in df.columns]

    print("Event/adoption month check:")
    print(df[show_cols].to_string(index=False))


if __name__ == "__main__":
    main()
