#!/usr/bin/env python3
"""
Create a Python-only usable-repo table from run4a outputs.

Input:
  - top_100_clone_candidates.csv
  - run4a clone log CSV

Output:
  - tmp_adoption_test/data/ai_adopt_repo_python.csv

Important:
  The output includes ONLY usable Python repos:
    status in {cloned, skipped_existing, updated_existing}

Failed Python repos are printed in the terminal summary but are not written
to the output CSV.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


DEFAULT_CANDIDATES_FILE = Path("tmp_adoption_test/data/top_100_clone_candidates.csv")
DEFAULT_OUTPUT_FILE = Path("tmp_adoption_test/data/ai_adopt_repo_python.csv")
DEFAULT_LOGS_DIR = Path("logs")
DEFAULT_LOG_PREFIX = "run4a_clone_log"
USABLE_STATUSES = ["cloned", "skipped_existing", "updated_existing"]


def find_latest_clone_log(logs_dir: Path, log_prefix: str) -> Path:
    pattern = f"{log_prefix}_*.csv"
    logs = sorted(logs_dir.glob(pattern), key=lambda p: p.stat().st_mtime)

    if not logs:
        raise SystemExit(f"No clone log found under {logs_dir} matching {pattern}")

    return logs[-1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a usable Python-only clone-status table from run4a outputs."
    )

    parser.add_argument(
        "--candidates-file",
        type=Path,
        default=DEFAULT_CANDIDATES_FILE,
        help="Candidate CSV generated by find_repo_pre_post_ai_adoption.py.",
    )

    parser.add_argument(
        "--clone-log",
        type=Path,
        default=None,
        help=(
            "Clone log CSV generated by clone_repos_v2.py. "
            "If omitted, the latest logs/run4a_clone_log_*.csv is used."
        ),
    )

    parser.add_argument(
        "--logs-dir",
        type=Path,
        default=DEFAULT_LOGS_DIR,
        help="Directory used to search for the latest clone log.",
    )

    parser.add_argument(
        "--log-prefix",
        default=DEFAULT_LOG_PREFIX,
        help="Clone log prefix used when searching for latest clone log.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_FILE,
        help="Output CSV path for usable Python candidate repos.",
    )

    parser.add_argument(
        "--language",
        default="Python",
        help="Language to filter on. Default: Python.",
    )

    parser.add_argument(
        "--language-column",
        default="repo_primary_language",
        help="Column containing primary language. Default: repo_primary_language.",
    )

    parser.add_argument(
        "--repo-column",
        default="repo_name",
        help="Column containing GitHub repo name. Default: repo_name.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    candidates_file = args.candidates_file.expanduser().resolve()
    output_file = args.output.expanduser().resolve()

    if args.clone_log is None:
        clone_log = find_latest_clone_log(
            logs_dir=args.logs_dir.expanduser().resolve(),
            log_prefix=args.log_prefix,
        )
    else:
        clone_log = args.clone_log.expanduser().resolve()

    if not candidates_file.exists():
        raise SystemExit(f"Candidate file not found: {candidates_file}")

    if not clone_log.exists():
        raise SystemExit(f"Clone log not found: {clone_log}")

    candidates = pd.read_csv(candidates_file)
    log = pd.read_csv(clone_log)

    if args.repo_column not in candidates.columns:
        raise SystemExit(
            f"Column {args.repo_column!r} not found in candidate file: {candidates_file}"
        )

    if args.repo_column not in log.columns:
        raise SystemExit(
            f"Column {args.repo_column!r} not found in clone log: {clone_log}"
        )

    if args.language_column not in candidates.columns:
        raise SystemExit(
            f"Column {args.language_column!r} not found in candidate file: {candidates_file}"
        )

    # Keep one clone-log row per repo. If duplicate rows exist, keep the latest one.
    log = log.drop_duplicates(subset=[args.repo_column], keep="last")

    merged = candidates.merge(log, on=args.repo_column, how="left", sort=False)

    language_mask = (
        merged[args.language_column]
        .astype(str)
        .str.strip()
        .str.lower()
        .eq(args.language.strip().lower())
    )

    language_df = merged[language_mask].copy()

    if "status" not in language_df.columns:
        raise SystemExit("Column 'status' not found after merging candidate file and clone log.")

    usable_df = language_df[language_df["status"].isin(USABLE_STATUSES)].copy()
    failed_df = language_df[language_df["status"].eq("failed")].copy()
    missing_df = language_df[language_df["status"].isna()].copy()

    # Keep original candidate columns first, then append clone-log columns.
    candidate_cols = list(candidates.columns)
    log_cols = [c for c in log.columns if c != args.repo_column]
    ordered_cols = candidate_cols + [c for c in log_cols if c in usable_df.columns]

    usable_df = usable_df[ordered_cols].copy()

    output_file.parent.mkdir(parents=True, exist_ok=True)
    usable_df.to_csv(output_file, index=False)

    print("Candidate file:", candidates_file)
    print("Clone log:     ", clone_log)
    print("Output file:   ", output_file)
    print()
    print(f"{args.language} candidate repos:", len(language_df))
    print(f"{args.language} usable repos written:", len(usable_df))
    print(f"{args.language} failed repos excluded:", len(failed_df))
    print(f"{args.language} missing log rows excluded:", len(missing_df))
    print()

    print(f"{args.language} clone status counts before filtering:")
    print(language_df["status"].value_counts(dropna=False))
    print()

    show_cols = [
        "rank",
        args.repo_column,
        "event_month",
        "pre_panel_months",
        "post_panel_months",
        "cursor_commit_share",
        "cursor_commit_rows",
        "cursor_authors",
        "repo_commits",
        "repo_contributors",
        "status",
        "target_dir",
        "note",
    ]

    show_cols = [c for c in show_cols if c in language_df.columns]

    print(f"Usable {args.language} repos written to CSV:")
    if len(usable_df) > 0:
        print(usable_df[[c for c in show_cols if c in usable_df.columns]].to_string(index=False))
    else:
        print("(none)")

    if len(failed_df) > 0:
        print()
        print(f"Failed {args.language} repos excluded:")
        print(failed_df[show_cols].to_string(index=False))


if __name__ == "__main__":
    main()
