#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create usable cloned repo list and attach event-window metadata "
            "from panel_event_monthly.csv."
        )
    )
    parser.add_argument(
        "--clone-status-file",
        required=True,
        help="Clone status CSV generated by run7c/run7b.",
    )
    parser.add_argument(
        "--panel-file",
        default="data_baseline_backup/panel_event_monthly.csv",
        help="Panel event monthly CSV containing repo_name, dataset_source, time, event, time_to_event.",
    )
    parser.add_argument(
        "--output-file",
        required=True,
        help="Output CSV for usable cloned repositories with event metadata.",
    )
    parser.add_argument(
        "--failed-output-file",
        default=None,
        help="Optional output CSV for failed repositories.",
    )
    parser.add_argument(
        "--usable-statuses",
        nargs="+",
        default=["cloned", "skipped_existing", "updated_existing"],
        help="Clone statuses treated as usable.",
    )
    parser.add_argument(
        "--dataset-source",
        default="treatment",
        help="dataset_source value to use from panel_event_monthly.csv.",
    )
    parser.add_argument(
        "--top-print",
        type=int,
        default=50,
        help="Number of rows to print.",
    )
    return parser.parse_args()


def clean_month(series: pd.Series) -> pd.Series:
    out = series.astype(str).str.strip().str[:7]
    return out.mask(out.str.lower().isin(["", "nan", "nat", "none"]))


def summarize_clone_status(
    clone_df: pd.DataFrame,
    usable_statuses: set[str],
    top_print: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    usable = clone_df[clone_df["status"].isin(usable_statuses)].copy()
    failed = clone_df[clone_df["status"].eq("failed")].copy()

    print("Total rows:", len(clone_df))
    print("Unique repos:", clone_df["repo_name"].nunique())
    print()

    print("Status counts:")
    print(clone_df["status"].fillna("(missing)").value_counts().to_string())
    print()

    print("Usable repos:", len(usable))
    print("Failed repos:", len(failed))
    print()

    if "repo_primary_language" in clone_df.columns:
        print("Language counts among all candidates:")
        print(clone_df["repo_primary_language"].fillna("(missing)").value_counts().to_string())
        print()

        print("Language counts among usable repos:")
        print(usable["repo_primary_language"].fillna("(missing)").value_counts().to_string())
        print()

    print("Top failed repos:")
    cols = ["repo_name", "repo_primary_language", "status", "note"]
    cols = [c for c in cols if c in failed.columns]
    if len(failed) == 0:
        print("(No failed repositories.)")
    else:
        print(failed[cols].head(top_print).to_string(index=False))
    print()

    return usable, failed


def build_event_summary(panel: pd.DataFrame, dataset_source: str) -> pd.DataFrame:
    required = ["repo_name", "dataset_source", "time", "event", "time_to_event"]
    missing = [c for c in required if c not in panel.columns]
    if missing:
        raise SystemExit(f"ERROR: panel file is missing required columns: {missing}")

    p = panel.copy()
    p["repo_name"] = p["repo_name"].astype(str).str.strip()
    p["dataset_source_norm"] = p["dataset_source"].astype(str).str.lower()
    p = p[p["dataset_source_norm"].eq(dataset_source.lower())].copy()

    p["time"] = clean_month(p["time"])
    p["event_month"] = clean_month(p["event"])
    p["time_to_event_num"] = pd.to_numeric(p["time_to_event"], errors="coerce")

    p = p.dropna(subset=["repo_name", "time", "event_month", "time_to_event_num"])
    p["time_to_event_num"] = p["time_to_event_num"].astype(int)

    p = p.sort_values(["repo_name", "time"]).drop_duplicates(
        ["repo_name", "time"],
        keep="first",
    )

    summary = (
        p.groupby("repo_name")
        .agg(
            event_month=("event_month", "first"),
            panel_first_month=("time", "min"),
            panel_latest_month=("time", "max"),
            panel_month_count=("time", "nunique"),
            min_relative_month=("time_to_event_num", "min"),
            max_relative_month=("time_to_event_num", "max"),
            pre_panel_months=("time_to_event_num", lambda x: int((x < 0).sum())),
            event_months=("time_to_event_num", lambda x: int((x == 0).sum())),
            post_panel_months=("time_to_event_num", lambda x: int((x > 0).sum())),
        )
        .reset_index()
    )

    summary["balanced_window"] = summary[
        ["pre_panel_months", "post_panel_months"]
    ].min(axis=1)

    return summary


def main() -> None:
    args = parse_args()

    clone_status_path = Path(args.clone_status_file)
    panel_path = Path(args.panel_file)
    output_path = Path(args.output_file)
    failed_output_path = Path(args.failed_output_file) if args.failed_output_file else None

    if not clone_status_path.exists():
        raise SystemExit(f"ERROR: clone status file not found: {clone_status_path}")

    if not panel_path.exists():
        raise SystemExit(f"ERROR: panel file not found: {panel_path}")

    clone_df = pd.read_csv(clone_status_path)
    panel = pd.read_csv(panel_path, dtype=str, low_memory=False)

    if "repo_name" not in clone_df.columns:
        raise SystemExit("ERROR: clone status file must contain repo_name.")

    if "status" not in clone_df.columns:
        raise SystemExit("ERROR: clone status file must contain status.")

    clone_df["repo_name"] = clone_df["repo_name"].astype(str).str.strip()

    print("Clone status file:", clone_status_path)
    print("Panel file:", panel_path)
    print("Output file:", output_path)
    if failed_output_path:
        print("Failed output file:", failed_output_path)
    print()

    usable_statuses = set(args.usable_statuses)

    usable, failed = summarize_clone_status(
        clone_df=clone_df,
        usable_statuses=usable_statuses,
        top_print=args.top_print,
    )

    usable = usable.drop_duplicates("repo_name").reset_index(drop=True)

    event_summary = build_event_summary(panel, args.dataset_source)
    out = usable.merge(event_summary, on="repo_name", how="left")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_path, index=False)

    if failed_output_path:
        failed_output_path.parent.mkdir(parents=True, exist_ok=True)
        failed.to_csv(failed_output_path, index=False)

    print("Event metadata merge summary:")
    print("Usable rows:", len(usable))
    print("Unique usable repos:", usable["repo_name"].nunique())
    print("Rows with event_month:", out["event_month"].notna().sum())
    print("Rows missing event_month:", out["event_month"].isna().sum())
    print()

    if "repo_primary_language" in out.columns:
        print("Usable language counts:")
        print(out["repo_primary_language"].fillna("(missing)").value_counts().to_string())
        print()

    print("Balanced window counts among usable repos:")
    bw = pd.to_numeric(out["balanced_window"], errors="coerce")
    bw_counts = bw.dropna().astype(int).value_counts().sort_index()

    if bw_counts.empty:
        print("(No non-missing balanced_window values.)")
    else:
        print(bw_counts.to_string())

    missing_bw = int(bw.isna().sum())
    if missing_bw > 0:
        print(f"(missing) {missing_bw}")
    print()

    cols = [
        "repo_name",
        "repo_primary_language",
        "event_month",
        "panel_first_month",
        "panel_latest_month",
        "panel_month_count",
        "pre_panel_months",
        "post_panel_months",
        "balanced_window",
        "status",
        "target_dir",
    ]
    cols = [c for c in cols if c in out.columns]

    print(f"Top {args.top_print} usable repos with event metadata:")
    if len(out) == 0:
        print("(No usable repositories.)")
    else:
        print(out[cols].head(args.top_print).to_string(index=False))
    print()

    print("Saved usable repo file:", output_path)
    if failed_output_path:
        print("Saved failed repo file:", failed_output_path)


if __name__ == "__main__":
    main()
