#!/usr/bin/env python3
"""Prepare Borusyak DiD inputs for NPR-based commit-function AGC outcomes.

This stage consumes the complete repository-month table generated by
run-py-7a and joins the covariates used by the existing commit-function
Borusyak workflow. It does not estimate treatment effects.

Scientific scope
----------------
The default specification, ``range100_200``, includes only function-change
events whose implementation body contains 100-200 literal-space tokens and
was successfully scored by the frozen DetectCodeGPT NPR pipeline.

The full-sample count outcomes retain every repository-month, including months
with zero NPR-selected events. The AGC ratio outcome is defined only when at
least one NPR-selected event is present and is therefore interpreted as a
conditional composition outcome.

Competing NCLOC specifications
------------------------------
The paper-compatible and Python-snapshot NCLOC variables are preserved as two
alternative model specifications. They must never be entered together in the
same regression formula.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


SCRIPT_VERSION = "run-py-7b-v1"
KEY_COLUMNS = ["dataset_source", "repo_name", "time"]

FULL_SAMPLE_OUTCOMES = [
    "has_npr_scored_function_change_event",
    "log1p_npr_scored_function_change_events",
    "log1p_npr_agc_function_change_events",
    "log1p_npr_hwc_function_change_events",
]
CONDITIONAL_OUTCOMES = ["npr_agc_function_change_event_ratio"]

REQUIRED_EVENT_COLUMNS = ["time_to_event", "event", "post_event"]
REQUIRED_COUNT_COLUMNS = [
    "npr_scored_function_change_events",
    "npr_agc_function_change_events",
    "npr_hwc_function_change_events",
]
REQUIRED_SCOPE_COLUMNS = [
    "zero_npr_scored_function_event_month",
    "zero_all_function_event_month",
    "has_function_events_but_no_npr_selected_event",
    "npr_detection_complete",
    "npr_specification",
    "npr_treatment_period",
    "has_parse_exclusion",
    "parse_exclusion_records",
    "treatment_group",
]

COVARIATE_COLUMNS = [
    "age",
    "ncloc_paper",
    "ncloc_python_snapshot",
    "contributors",
    "stars",
    "issues",
]
EXPECTED_NULLABLE_COVARIATE_COLUMNS = [
    "age",
    "contributors",
    "stars",
    "issues",
    "ncloc_paper",
    "ncloc_python_snapshot",
]
SHARED_COVARIATE_COLUMNS = ["age", "contributors", "stars", "issues"]
SHARED_TRANSFORMED_COVARIATE_COLUMNS = [
    "log1p_age",
    "log1p_contributors",
    "log1p_stars",
    "log1p_issues",
]
PAPER_NCLOC_SPECIFICATION_COLUMNS = SHARED_TRANSFORMED_COVARIATE_COLUMNS + [
    "ncloc_paper"
]
PYTHON_SNAPSHOT_NCLOC_SPECIFICATION_COLUMNS = (
    SHARED_TRANSFORMED_COVARIATE_COLUMNS + ["ncloc_python_snapshot"]
)
READINESS_FLAG_COLUMNS = [
    "analysis_ready_npr_paper_ncloc",
    "analysis_ready_npr_python_snapshot_ncloc",
    "analysis_ready_npr_ratio_paper_ncloc",
    "analysis_ready_npr_ratio_python_snapshot_ncloc",
]
EXISTING_DIAGNOSTIC_READINESS_COLUMNS = [
    "analysis_ready_agc_changed_block_paper_ncloc",
    "analysis_ready_agc_changed_block_python_snapshot_ncloc",
]
LEAD_LAG_COLUMNS = [
    "lead_6",
    "lead_5",
    "lead_4",
    "lead_3",
    "lead_2",
    "lead_1",
    "lag_0",
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "lag_5",
    "lag_6",
]


class ValidationError(RuntimeError):
    """Raised when an input or cross-artifact invariant is violated."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Prepare covariate-complete Borusyak DiD input panels for "
            "NPR-based commit-function AGC outcomes."
        )
    )
    parser.add_argument("--input-table", type=Path)
    parser.add_argument("--covariate-panel", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--qc-dir", type=Path, default=None)
    parser.add_argument("--specification-name", default="range100_200")
    parser.add_argument("--expected-rows", type=int, default=1633)
    parser.add_argument(
        "--expected-positive-event-rows", type=int, default=1142
    )
    parser.add_argument("--expected-zero-event-rows", type=int, default=491)
    parser.add_argument(
        "--expected-function-event-no-selected-rows", type=int, default=147
    )
    parser.add_argument("--expected-control-rows", type=int, default=780)
    parser.add_argument("--expected-treatment-rows", type=int, default=853)
    parser.add_argument(
        "--expected-parse-exclusion-months", type=int, default=97
    )
    parser.add_argument(
        "--known-age-missing", type=int, default=15
    )
    parser.add_argument(
        "--known-contributors-missing", type=int, default=0
    )
    parser.add_argument(
        "--known-stars-missing", type=int, default=15
    )
    parser.add_argument(
        "--known-issues-missing", type=int, default=15
    )
    parser.add_argument(
        "--known-paper-ncloc-missing", type=int, default=37
    )
    parser.add_argument("--overwrite-output", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def require_file(path: Path | None, label: str) -> Path:
    if path is None:
        raise FileNotFoundError(f"{label} path was not supplied")
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")
    return path


def require_columns(
    frame: pd.DataFrame,
    required: Iterable[str],
    label: str,
) -> None:
    missing = sorted(set(required) - set(frame.columns))
    if missing:
        raise ValidationError(
            f"{label} is missing required columns: {missing}. "
            f"Available columns: {list(frame.columns)}"
        )


def require_unique(frame: pd.DataFrame, columns: list[str], label: str) -> None:
    duplicate_mask = frame.duplicated(columns, keep=False)
    if duplicate_mask.any():
        sample = frame.loc[duplicate_mask, columns].head(20)
        raise ValidationError(
            f"{label} contains duplicate keys for {columns}:\n"
            f"{sample.to_string(index=False)}"
        )


def normalize_keys(frame: pd.DataFrame) -> pd.DataFrame:
    result = frame.copy()
    for column in KEY_COLUMNS:
        if column in result.columns:
            result[column] = result[column].astype("string").str.strip()
    if "time" in result.columns:
        result["time"] = result["time"].str[:7]
    return result


def normalize_boolean(series: pd.Series, column_name: str) -> pd.Series:
    mapping: dict[Any, bool] = {
        True: True,
        False: False,
        1: True,
        0: False,
        1.0: True,
        0.0: False,
        "True": True,
        "False": False,
        "true": True,
        "false": False,
        "1": True,
        "0": False,
        "1.0": True,
        "0.0": False,
    }
    normalized = series.map(mapping).astype("boolean")
    if normalized.isna().any():
        unresolved = (
            series.loc[normalized.isna()]
            .astype("string")
            .value_counts(dropna=False)
            .head(20)
            .to_dict()
        )
        raise ValidationError(
            f"{column_name} contains unresolved Boolean values: {unresolved}"
        )
    return normalized


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_write_csv(frame: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        temporary_path = Path(handle.name)
        frame.to_csv(handle, index=False)
    os.replace(temporary_path, path)


def atomic_write_json(payload: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        temporary_path = Path(handle.name)
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")
    os.replace(temporary_path, path)


def prepare_output_directory(path: Path, overwrite: bool) -> None:
    if path.exists() and any(path.iterdir()):
        if not overwrite:
            raise FileExistsError(
                f"Output directory is not empty: {path}. "
                "Use --overwrite-output only for an intentional replacement."
            )
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def add_check(
    checks: list[dict[str, Any]],
    name: str,
    passed: bool,
    observed: Any,
    expected: Any,
    description: str,
) -> None:
    checks.append(
        {
            "check": name,
            "passed": bool(passed),
            "observed": json.dumps(observed, sort_keys=True)
            if isinstance(observed, (dict, list))
            else observed,
            "expected": json.dumps(expected, sort_keys=True)
            if isinstance(expected, (dict, list))
            else expected,
            "description": description,
        }
    )


def create_event_time_support(frame: pd.DataFrame) -> pd.DataFrame:
    support = (
        frame.groupby(["dataset_source", "time_to_event"], dropna=False)
        .agg(
            repo_months=("repo_name", "size"),
            repositories=("repo_name", "nunique"),
            npr_positive_months=(
                "has_npr_scored_function_change_event",
                "sum",
            ),
            zero_npr_selected_months=(
                "zero_npr_scored_function_event_month",
                "sum",
            ),
            all_function_positive_no_npr_selected_months=(
                "has_function_events_but_no_npr_selected_event",
                "sum",
            ),
            total_npr_scored_function_change_events=(
                "npr_scored_function_change_events",
                "sum",
            ),
            total_npr_agc_function_change_events=(
                "npr_agc_function_change_events",
                "sum",
            ),
            total_npr_hwc_function_change_events=(
                "npr_hwc_function_change_events",
                "sum",
            ),
            parse_exclusion_months=("has_parse_exclusion", "sum"),
        )
        .reset_index()
    )
    support["npr_positive_month_ratio"] = (
        support["npr_positive_months"] / support["repo_months"]
    )
    support["zero_npr_selected_month_ratio"] = (
        support["zero_npr_selected_months"] / support["repo_months"]
    )
    return support


def create_outcome_completeness(frame: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for outcome in FULL_SAMPLE_OUTCOMES + CONDITIONAL_OUTCOMES:
        values = pd.to_numeric(frame[outcome], errors="coerce")
        rows.append(
            {
                "outcome": outcome,
                "total_repo_months": int(len(frame)),
                "nonmissing_repo_months": int(values.notna().sum()),
                "missing_repo_months": int(values.isna().sum()),
                "zero_values": int(values.eq(0).sum()),
                "analysis_scope": (
                    "full_sample"
                    if outcome in FULL_SAMPLE_OUTCOMES
                    else "npr_positive_months_only"
                ),
            }
        )
    return pd.DataFrame(rows)


def create_covariate_completeness(frame: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for column in COVARIATE_COLUMNS + SHARED_TRANSFORMED_COVARIATE_COLUMNS:
        values = pd.to_numeric(frame[column], errors="coerce")
        rows.append(
            {
                "covariate": column,
                "repo_months": int(len(frame)),
                "nonmissing_repo_months": int(values.notna().sum()),
                "missing_repo_months": int(values.isna().sum()),
                "negative_values": int(values.lt(0).sum()),
                "zero_values": int(values.eq(0).sum()),
                "expected_nullable": bool(
                    column in EXPECTED_NULLABLE_COVARIATE_COLUMNS
                ),
            }
        )
    return pd.DataFrame(rows)


def create_sample_summary(
    full_panel: pd.DataFrame,
    ratio_panel: pd.DataFrame,
    parse_clean_full_panel: pd.DataFrame,
    parse_clean_ratio_panel: pd.DataFrame,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for name, frame in [
        ("full", full_panel),
        ("ratio_positive_npr_event", ratio_panel),
        ("parse_clean_full", parse_clean_full_panel),
        ("parse_clean_ratio_positive_npr_event", parse_clean_ratio_panel),
    ]:
        rows.append(
            {
                "sample": name,
                "repo_months": int(len(frame)),
                "repositories": int(frame["repo_name"].nunique()),
                "control_repo_months": int(
                    frame["dataset_source"].eq("control").sum()
                ),
                "treatment_repo_months": int(
                    frame["dataset_source"].eq("treatment").sum()
                ),
                "zero_npr_selected_months": int(
                    frame["zero_npr_scored_function_event_month"].sum()
                ),
                "npr_positive_months": int(
                    frame["has_npr_scored_function_change_event"].sum()
                ),
                "all_function_positive_no_npr_selected_months": int(
                    frame[
                        "has_function_events_but_no_npr_selected_event"
                    ].sum()
                ),
                "parse_exclusion_months": int(
                    frame["has_parse_exclusion"].sum()
                ),
            }
        )
    return pd.DataFrame(rows)


def create_specification_sample_summary(
    samples: list[tuple[str, pd.DataFrame]],
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for sample_name, frame in samples:
        rows.append(
            {
                "sample": sample_name,
                "paper_ncloc_analysis_ready_rows": int(
                    frame["analysis_ready_npr_paper_ncloc"].eq(1).sum()
                ),
                "python_snapshot_ncloc_analysis_ready_rows": int(
                    frame[
                        "analysis_ready_npr_python_snapshot_ncloc"
                    ].eq(1).sum()
                ),
                "paper_ncloc_ratio_analysis_ready_rows": int(
                    frame[
                        "analysis_ready_npr_ratio_paper_ncloc"
                    ].eq(1).sum()
                ),
                "python_snapshot_ncloc_ratio_analysis_ready_rows": int(
                    frame[
                        "analysis_ready_npr_ratio_python_snapshot_ncloc"
                    ].eq(1).sum()
                ),
            }
        )
    return pd.DataFrame(rows)


def validate_numeric_nonnegative(
    frame: pd.DataFrame,
    columns: Iterable[str],
) -> None:
    for column in columns:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")
        invalid = frame[column].lt(0) & frame[column].notna()
        if invalid.any():
            sample = frame.loc[invalid, KEY_COLUMNS + [column]].head(20)
            raise ValidationError(
                f"{column} contains negative values:\n"
                f"{sample.to_string(index=False)}"
            )


def build_outputs(
    input_table: Path,
    covariate_panel_path: Path,
    specification_name: str,
    expectations: dict[str, int],
    known_missing: dict[str, int],
) -> dict[str, Any]:
    analysis = normalize_keys(pd.read_csv(input_table))
    covariates = normalize_keys(pd.read_csv(covariate_panel_path))

    required_analysis = (
        KEY_COLUMNS
        + REQUIRED_EVENT_COLUMNS
        + REQUIRED_COUNT_COLUMNS
        + FULL_SAMPLE_OUTCOMES
        + CONDITIONAL_OUTCOMES
        + REQUIRED_SCOPE_COLUMNS
    )
    require_columns(analysis, required_analysis, "run-py-7a input table")
    require_columns(
        covariates,
        KEY_COLUMNS + COVARIATE_COLUMNS + LEAD_LAG_COLUMNS,
        "Covariate panel",
    )
    require_unique(analysis, KEY_COLUMNS, "run-py-7a input table")
    require_unique(covariates, KEY_COLUMNS, "Covariate panel")

    original_rows = len(analysis)
    original_keys = analysis[KEY_COLUMNS].reset_index(drop=True).copy()
    original_outcomes = analysis[
        KEY_COLUMNS + FULL_SAMPLE_OUTCOMES + CONDITIONAL_OUTCOMES
    ].reset_index(drop=True).copy()

    join_columns = KEY_COLUMNS + COVARIATE_COLUMNS + LEAD_LAG_COLUMNS
    optional_columns = [
        column
        for column in EXISTING_DIAGNOSTIC_READINESS_COLUMNS
        if column in covariates.columns
    ]
    minimal_covariates = covariates[join_columns + optional_columns].copy()

    overlap_nonkey = sorted(
        (set(minimal_covariates.columns) - set(KEY_COLUMNS))
        & set(analysis.columns)
    )
    if overlap_nonkey:
        analysis = analysis.drop(columns=overlap_nonkey)

    panel = analysis.merge(
        minimal_covariates,
        on=KEY_COLUMNS,
        how="left",
        validate="one_to_one",
        indicator="covariate_merge_status",
    )
    unmatched = panel["covariate_merge_status"].ne("both")
    if unmatched.any():
        sample = panel.loc[unmatched, KEY_COLUMNS].head(20)
        raise ValidationError(
            "Covariate panel is missing repository-month keys:\n"
            f"{sample.to_string(index=False)}"
        )
    panel = panel.drop(columns=["covariate_merge_status"])

    for column in REQUIRED_COUNT_COLUMNS + [
        "has_npr_scored_function_change_event",
        "zero_npr_scored_function_event_month",
        "zero_all_function_event_month",
        "has_function_events_but_no_npr_selected_event",
        "has_parse_exclusion",
        "parse_exclusion_records",
    ]:
        panel[column] = pd.to_numeric(panel[column], errors="raise")

    panel["event"] = (
        panel["event"]
        .astype("string")
        .str.strip()
        .replace(
            {
                "": pd.NA,
                "nan": pd.NA,
                "NaN": pd.NA,
                "None": pd.NA,
                "<NA>": pd.NA,
            }
        )
    )

    numeric_columns = (
        ["time_to_event", "post_event"]
        + COVARIATE_COLUMNS
        + LEAD_LAG_COLUMNS
        + FULL_SAMPLE_OUTCOMES
        + CONDITIONAL_OUTCOMES
    )
    for column in numeric_columns:
        panel[column] = pd.to_numeric(panel[column], errors="coerce")

    panel["npr_detection_complete"] = normalize_boolean(
        panel["npr_detection_complete"], "npr_detection_complete"
    )

    validate_numeric_nonnegative(
        panel,
        ["age", "contributors", "stars", "issues", "ncloc_paper", "ncloc_python_snapshot"],
    )

    panel["log1p_age"] = np.log1p(panel["age"])
    panel["log1p_contributors"] = np.log1p(panel["contributors"])
    panel["log1p_stars"] = np.log1p(panel["stars"])
    panel["log1p_issues"] = np.log1p(panel["issues"])

    shared_ready = panel[
        SHARED_TRANSFORMED_COVARIATE_COLUMNS
    ].notna().all(axis=1)
    panel["analysis_ready_npr_paper_ncloc"] = (
        shared_ready & panel["ncloc_paper"].notna()
    ).astype("int8")
    panel["analysis_ready_npr_python_snapshot_ncloc"] = (
        shared_ready & panel["ncloc_python_snapshot"].notna()
    ).astype("int8")

    ratio_ready_base = (
        panel["npr_scored_function_change_events"].gt(0)
        & panel["npr_agc_function_change_event_ratio"].notna()
    )
    panel["analysis_ready_npr_ratio_paper_ncloc"] = (
        ratio_ready_base
        & panel["analysis_ready_npr_paper_ncloc"].eq(1)
    ).astype("int8")
    panel["analysis_ready_npr_ratio_python_snapshot_ncloc"] = (
        ratio_ready_base
        & panel["analysis_ready_npr_python_snapshot_ncloc"].eq(1)
    ).astype("int8")

    panel["treat"] = (
        panel["dataset_source"]
        .map({"control": 0, "treatment": 1})
        .astype("Int64")
    )
    if panel["treat"].isna().any():
        unexpected = sorted(
            panel.loc[panel["treat"].isna(), "dataset_source"]
            .dropna()
            .unique()
            .tolist()
        )
        raise ValidationError(f"Unexpected dataset_source values: {unexpected}")

    panel["unit_id"] = panel["repo_name"].astype("string")
    panel["calendar_time"] = panel["time"].astype("string")
    panel["npr_ratio_sample"] = ratio_ready_base.astype("int8")

    positive_mask = panel["npr_scored_function_change_events"].gt(0)
    zero_mask = panel["npr_scored_function_change_events"].eq(0)
    parse_clean_mask = panel["has_parse_exclusion"].eq(0)

    full_panel = panel.copy()
    ratio_panel = panel.loc[positive_mask].copy()
    parse_clean_full_panel = panel.loc[parse_clean_mask].copy()
    parse_clean_ratio_panel = panel.loc[
        positive_mask & parse_clean_mask
    ].copy()

    event_time_support = create_event_time_support(full_panel)
    outcome_completeness = create_outcome_completeness(full_panel)
    covariate_completeness = create_covariate_completeness(full_panel)
    sample_summary = create_sample_summary(
        full_panel,
        ratio_panel,
        parse_clean_full_panel,
        parse_clean_ratio_panel,
    )
    specification_sample_summary = create_specification_sample_summary(
        [
            ("full", full_panel),
            ("ratio_positive_npr_event", ratio_panel),
            ("parse_clean_full", parse_clean_full_panel),
            (
                "parse_clean_ratio_positive_npr_event",
                parse_clean_ratio_panel,
            ),
        ]
    )

    checks: list[dict[str, Any]] = []
    add_check(
        checks,
        "covariate_join_row_count_unchanged",
        len(panel) == original_rows,
        len(panel),
        original_rows,
        "Joining covariates must not change the number of repository-months.",
    )
    add_check(
        checks,
        "covariate_join_key_order_unchanged",
        panel[KEY_COLUMNS].reset_index(drop=True).equals(original_keys),
        len(panel),
        original_rows,
        "The original repository-month key order must be preserved.",
    )
    merged_outcomes = panel[
        KEY_COLUMNS + FULL_SAMPLE_OUTCOMES + CONDITIONAL_OUTCOMES
    ].reset_index(drop=True)
    add_check(
        checks,
        "covariate_join_outcomes_unchanged",
        merged_outcomes.equals(original_outcomes),
        len(panel),
        original_rows,
        "Joining covariates must not alter NPR outcomes.",
    )
    add_check(
        checks,
        "specification_name_matches",
        bool(full_panel["npr_specification"].eq(specification_name).all()),
        sorted(full_panel["npr_specification"].dropna().unique().tolist()),
        [specification_name],
        "Every row must retain the requested frozen NPR specification.",
    )
    add_check(
        checks,
        "full_panel_row_count",
        len(full_panel) == expectations["rows"],
        len(full_panel),
        expectations["rows"],
        "The full DiD input must retain all matched repository-months.",
    )
    add_check(
        checks,
        "positive_npr_event_panel_row_count",
        len(ratio_panel) == expectations["positive_rows"],
        len(ratio_panel),
        expectations["positive_rows"],
        "The ratio panel must contain exactly the NPR-positive repository-months.",
    )
    add_check(
        checks,
        "zero_npr_selected_row_count",
        int(zero_mask.sum()) == expectations["zero_rows"],
        int(zero_mask.sum()),
        expectations["zero_rows"],
        "Zero NPR-selected repository-months must match run-py-7a.",
    )
    add_check(
        checks,
        "function_event_positive_but_no_npr_selected_row_count",
        int(
            full_panel[
                "has_function_events_but_no_npr_selected_event"
            ].sum()
        )
        == expectations["function_no_selected_rows"],
        int(
            full_panel[
                "has_function_events_but_no_npr_selected_event"
            ].sum()
        ),
        expectations["function_no_selected_rows"],
        "Months with function events outside this NPR range must remain visible.",
    )
    add_check(
        checks,
        "control_row_count",
        int(full_panel["dataset_source"].eq("control").sum())
        == expectations["control_rows"],
        int(full_panel["dataset_source"].eq("control").sum()),
        expectations["control_rows"],
        "Static control membership must match the frozen matched panel.",
    )
    add_check(
        checks,
        "treatment_row_count",
        int(full_panel["dataset_source"].eq("treatment").sum())
        == expectations["treatment_rows"],
        int(full_panel["dataset_source"].eq("treatment").sum()),
        expectations["treatment_rows"],
        "Static treatment membership must match the frozen matched panel.",
    )
    add_check(
        checks,
        "parse_exclusion_month_count",
        int(full_panel["has_parse_exclusion"].sum())
        == expectations["parse_exclusion_months"],
        int(full_panel["has_parse_exclusion"].sum()),
        expectations["parse_exclusion_months"],
        "Parse-exclusion coverage must match the upstream panel.",
    )
    add_check(
        checks,
        "npr_event_count_partition",
        bool(
            (
                full_panel["npr_agc_function_change_events"]
                + full_panel["npr_hwc_function_change_events"]
                == full_panel["npr_scored_function_change_events"]
            ).all()
        ),
        int(
            (
                full_panel["npr_agc_function_change_events"]
                + full_panel["npr_hwc_function_change_events"]
                != full_panel["npr_scored_function_change_events"]
            ).sum()
        ),
        0,
        "AGC-like and HWC-like NPR events must reconstruct all scored events.",
    )
    add_check(
        checks,
        "positive_npr_event_ratio_nonmissing",
        bool(ratio_panel["npr_agc_function_change_event_ratio"].notna().all()),
        int(ratio_panel["npr_agc_function_change_event_ratio"].isna().sum()),
        0,
        "Every NPR-positive repository-month must have a conditional AGC ratio.",
    )
    add_check(
        checks,
        "zero_npr_event_ratio_missing",
        bool(
            full_panel.loc[
                zero_mask, "npr_agc_function_change_event_ratio"
            ].isna().all()
        ),
        int(
            full_panel.loc[
                zero_mask, "npr_agc_function_change_event_ratio"
            ].notna().sum()
        ),
        0,
        "The conditional ratio must remain missing when the denominator is zero.",
    )
    add_check(
        checks,
        "npr_ratio_bounds",
        bool(
            ratio_panel["npr_agc_function_change_event_ratio"]
            .between(0, 1, inclusive="both")
            .all()
        ),
        int(
            (~ratio_panel["npr_agc_function_change_event_ratio"].between(
                0, 1, inclusive="both"
            )).sum()
        ),
        0,
        "The AGC event ratio must lie in [0, 1].",
    )
    add_check(
        checks,
        "npr_detection_complete_all_true",
        bool(full_panel["npr_detection_complete"].eq(True).all()),
        int(full_panel["npr_detection_complete"].eq(False).sum()),
        0,
        "Every repository-month must be backed by a complete frozen NPR result.",
    )
    add_check(
        checks,
        "treat_matches_dataset_source",
        bool(
            (
                full_panel["treat"]
                == full_panel["dataset_source"].map(
                    {"control": 0, "treatment": 1}
                )
            ).all()
        ),
        int(
            (
                full_panel["treat"]
                != full_panel["dataset_source"].map(
                    {"control": 0, "treatment": 1}
                )
            ).sum()
        ),
        0,
        "The regression treatment flag must encode static cohort membership.",
    )

    treatment_event_missing = int(
        full_panel.loc[
            full_panel["dataset_source"].eq("treatment"), "event"
        ].isna().sum()
    )
    control_event_nonmissing = int(
        full_panel.loc[
            full_panel["dataset_source"].eq("control"), "event"
        ].notna().sum()
    )
    treatment_event_counts = (
        full_panel.loc[
            full_panel["dataset_source"].eq("treatment"),
            ["repo_name", "event"],
        ]
        .groupby("repo_name")["event"]
        .nunique(dropna=True)
    )
    add_check(
        checks,
        "treatment_event_month_nonmissing",
        treatment_event_missing == 0,
        treatment_event_missing,
        0,
        "Every treatment repository-month must retain its adoption month.",
    )
    add_check(
        checks,
        "control_event_month_missing",
        control_event_nonmissing == 0,
        control_event_nonmissing,
        0,
        "Control repository-months must not be assigned an adoption month.",
    )
    add_check(
        checks,
        "one_event_month_per_treatment_repository",
        bool(treatment_event_counts.eq(1).all()),
        int(treatment_event_counts.ne(1).sum()),
        0,
        "Each treatment repository must have one consistent adoption month.",
    )
    add_check(
        checks,
        "full_sample_outcomes_nonmissing",
        bool(full_panel[FULL_SAMPLE_OUTCOMES].notna().all().all()),
        int(full_panel[FULL_SAMPLE_OUTCOMES].isna().sum().sum()),
        0,
        "Full-sample count outcomes must be defined for all repository-months.",
    )

    observed_missing = {
        "age": int(full_panel["age"].isna().sum()),
        "contributors": int(full_panel["contributors"].isna().sum()),
        "stars": int(full_panel["stars"].isna().sum()),
        "issues": int(full_panel["issues"].isna().sum()),
        "ncloc_paper": int(full_panel["ncloc_paper"].isna().sum()),
    }
    add_check(
        checks,
        "known_covariate_missing_counts_match_frozen_panel",
        observed_missing == known_missing,
        observed_missing,
        known_missing,
        "Expected genuine covariate missingness must not drift silently.",
    )
    add_check(
        checks,
        "transformed_covariates_missing_matches_raw",
        bool(
            full_panel["log1p_age"].isna().sum()
            == full_panel["age"].isna().sum()
            and full_panel["log1p_contributors"].isna().sum()
            == full_panel["contributors"].isna().sum()
            and full_panel["log1p_stars"].isna().sum()
            == full_panel["stars"].isna().sum()
            and full_panel["log1p_issues"].isna().sum()
            == full_panel["issues"].isna().sum()
        ),
        int(
            full_panel[SHARED_TRANSFORMED_COVARIATE_COLUMNS]
            .isna()
            .sum()
            .sum()
        ),
        int(
            full_panel[SHARED_COVARIATE_COLUMNS].isna().sum().sum()
        ),
        "Log transforms must preserve the raw missingness pattern.",
    )
    add_check(
        checks,
        "ratio_readiness_flags_subset_of_full_readiness",
        bool(
            (
                full_panel["analysis_ready_npr_ratio_paper_ncloc"]
                <= full_panel["analysis_ready_npr_paper_ncloc"]
            ).all()
            and (
                full_panel[
                    "analysis_ready_npr_ratio_python_snapshot_ncloc"
                ]
                <= full_panel[
                    "analysis_ready_npr_python_snapshot_ncloc"
                ]
            ).all()
        ),
        int(
            (
                full_panel["analysis_ready_npr_ratio_paper_ncloc"]
                > full_panel["analysis_ready_npr_paper_ncloc"]
            ).sum()
            + (
                full_panel[
                    "analysis_ready_npr_ratio_python_snapshot_ncloc"
                ]
                > full_panel[
                    "analysis_ready_npr_python_snapshot_ncloc"
                ]
            ).sum()
        ),
        0,
        "Ratio-ready rows must be subsets of the corresponding full samples.",
    )
    add_check(
        checks,
        "parse_clean_full_has_no_exclusions",
        int(parse_clean_full_panel["has_parse_exclusion"].sum()) == 0,
        int(parse_clean_full_panel["has_parse_exclusion"].sum()),
        0,
        "The parse-clean full sample must exclude every affected month.",
    )
    add_check(
        checks,
        "parse_clean_ratio_has_no_exclusions",
        int(parse_clean_ratio_panel["has_parse_exclusion"].sum()) == 0,
        int(parse_clean_ratio_panel["has_parse_exclusion"].sum()),
        0,
        "The parse-clean ratio sample must exclude every affected month.",
    )

    for existing_column, new_column in [
        (
            "analysis_ready_agc_changed_block_paper_ncloc",
            "analysis_ready_npr_paper_ncloc",
        ),
        (
            "analysis_ready_agc_changed_block_python_snapshot_ncloc",
            "analysis_ready_npr_python_snapshot_ncloc",
        ),
    ]:
        if existing_column in full_panel.columns:
            existing_values = pd.to_numeric(
                full_panel[existing_column], errors="coerce"
            )
            new_values = full_panel[new_column]
            add_check(
                checks,
                f"diagnostic_{existing_column}_vs_{new_column}_agreement",
                True,
                {
                    "agree": int((existing_values == new_values).sum()),
                    "disagree": int((existing_values != new_values).sum()),
                    "existing_missing": int(existing_values.isna().sum()),
                },
                "informational",
                "Readiness for the older outcome is diagnostic context only.",
            )

    checks_frame = pd.DataFrame(checks)
    overall_pass = bool(checks_frame["passed"].all())

    return {
        "full_panel": full_panel,
        "ratio_panel": ratio_panel,
        "parse_clean_full_panel": parse_clean_full_panel,
        "parse_clean_ratio_panel": parse_clean_ratio_panel,
        "event_time_support": event_time_support,
        "outcome_completeness": outcome_completeness,
        "covariate_completeness": covariate_completeness,
        "sample_summary": sample_summary,
        "specification_sample_summary": specification_sample_summary,
        "checks": checks_frame,
        "overall_pass": overall_pass,
    }


def write_outputs(
    outputs: dict[str, Any],
    input_table: Path,
    covariate_panel: Path,
    output_dir: Path,
    qc_dir: Path,
    specification_name: str,
) -> dict[str, Any]:
    paths = {
        "full_panel": output_dir
        / "panel_event_monthly_agc_commit_function_npr.csv",
        "ratio_panel": output_dir
        / "panel_event_monthly_agc_commit_function_npr_ratio_positive.csv",
        "parse_clean_full_panel": output_dir
        / "panel_event_monthly_agc_commit_function_npr_parse_clean.csv",
        "parse_clean_ratio_panel": output_dir
        / "panel_event_monthly_agc_commit_function_npr_ratio_positive_parse_clean.csv",
        "event_time_support": output_dir
        / "agc_commit_function_npr_event_time_support.csv",
        "outcome_completeness": output_dir
        / "agc_commit_function_npr_outcome_completeness.csv",
        "covariate_completeness": output_dir
        / "agc_commit_function_npr_covariate_completeness.csv",
        "sample_summary": output_dir
        / "agc_commit_function_npr_sample_summary.csv",
        "specification_sample_summary": output_dir
        / "agc_commit_function_npr_specification_sample_summary.csv",
        "checks": qc_dir / "agc_commit_function_npr_did_input_checks.csv",
        "summary": qc_dir / "agc_commit_function_npr_did_input_summary.json",
        "metadata": qc_dir / "agc_commit_function_npr_did_input_metadata.json",
    }

    for key in [
        "full_panel",
        "ratio_panel",
        "parse_clean_full_panel",
        "parse_clean_ratio_panel",
        "event_time_support",
        "outcome_completeness",
        "covariate_completeness",
        "sample_summary",
        "specification_sample_summary",
        "checks",
    ]:
        atomic_write_csv(outputs[key], paths[key])

    full_panel = outputs["full_panel"]
    ratio_panel = outputs["ratio_panel"]
    parse_clean_full = outputs["parse_clean_full_panel"]
    parse_clean_ratio = outputs["parse_clean_ratio_panel"]
    checks_frame = outputs["checks"]

    summary = {
        "status": "PASS" if outputs["overall_pass"] else "FAIL",
        "script_version": SCRIPT_VERSION,
        "specification": specification_name,
        "full_panel_rows": int(len(full_panel)),
        "ratio_panel_rows": int(len(ratio_panel)),
        "zero_npr_selected_rows": int(
            full_panel["zero_npr_scored_function_event_month"].sum()
        ),
        "function_event_positive_but_no_npr_selected_rows": int(
            full_panel[
                "has_function_events_but_no_npr_selected_event"
            ].sum()
        ),
        "control_rows": int(full_panel["dataset_source"].eq("control").sum()),
        "treatment_rows": int(
            full_panel["dataset_source"].eq("treatment").sum()
        ),
        "parse_exclusion_months": int(
            full_panel["has_parse_exclusion"].sum()
        ),
        "parse_clean_full_rows": int(len(parse_clean_full)),
        "parse_clean_ratio_rows": int(len(parse_clean_ratio)),
        "failed_checks": int((~checks_frame["passed"]).sum()),
        "full_sample_outcomes": FULL_SAMPLE_OUTCOMES,
        "conditional_outcomes": CONDITIONAL_OUTCOMES,
        "shared_covariates": SHARED_COVARIATE_COLUMNS,
        "shared_transformed_covariates": SHARED_TRANSFORMED_COVARIATE_COLUMNS,
        "paper_ncloc_specification": PAPER_NCLOC_SPECIFICATION_COLUMNS,
        "python_snapshot_ncloc_specification": (
            PYTHON_SNAPSHOT_NCLOC_SPECIFICATION_COLUMNS
        ),
        "readiness_flag_columns": READINESS_FLAG_COLUMNS,
        "outputs": {key: str(value) for key, value in paths.items()},
    }
    atomic_write_json(summary, paths["summary"])

    metadata = {
        "script_version": SCRIPT_VERSION,
        "specification": specification_name,
        "input_table": str(input_table),
        "input_table_sha256": sha256_file(input_table),
        "covariate_panel": str(covariate_panel),
        "covariate_panel_sha256": sha256_file(covariate_panel),
        "output_directory": str(output_dir),
        "qc_directory": str(qc_dir),
        "scientific_scope": (
            "NPR-selected commit-function change events for one frozen "
            "body-token specification"
        ),
        "ratio_interpretation": (
            "Conditional on at least one NPR-selected function-change event "
            "in the repository-month"
        ),
    }
    atomic_write_json(metadata, paths["metadata"])
    return summary


def run_self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="run-py-7b-npr-v1-") as tmp:
        root = Path(tmp)
        analysis_path = root / "analysis.csv"
        covariate_path = root / "covariates.csv"

        analysis = pd.DataFrame(
            [
                {
                    "dataset_source": "control",
                    "repo_name": "c/repo",
                    "time": "2024-01",
                    "time_to_event": -1,
                    "event": pd.NA,
                    "post_event": 0,
                    "npr_scored_function_change_events": 0,
                    "npr_agc_function_change_events": 0,
                    "npr_hwc_function_change_events": 0,
                    "has_npr_scored_function_change_event": 0,
                    "zero_npr_scored_function_event_month": 1,
                    "zero_all_function_event_month": 1,
                    "has_function_events_but_no_npr_selected_event": 0,
                    "log1p_npr_scored_function_change_events": 0.0,
                    "log1p_npr_agc_function_change_events": 0.0,
                    "log1p_npr_hwc_function_change_events": 0.0,
                    "npr_agc_function_change_event_ratio": np.nan,
                    "npr_detection_complete": True,
                    "npr_specification": "range100_200",
                    "npr_treatment_period": "control",
                    "has_parse_exclusion": 0,
                    "parse_exclusion_records": 0,
                    "treatment_group": "control",
                },
                {
                    "dataset_source": "control",
                    "repo_name": "c/repo",
                    "time": "2024-02",
                    "time_to_event": 0,
                    "event": pd.NA,
                    "post_event": 0,
                    "npr_scored_function_change_events": 2,
                    "npr_agc_function_change_events": 1,
                    "npr_hwc_function_change_events": 1,
                    "has_npr_scored_function_change_event": 1,
                    "zero_npr_scored_function_event_month": 0,
                    "zero_all_function_event_month": 0,
                    "has_function_events_but_no_npr_selected_event": 0,
                    "log1p_npr_scored_function_change_events": np.log1p(2),
                    "log1p_npr_agc_function_change_events": np.log1p(1),
                    "log1p_npr_hwc_function_change_events": np.log1p(1),
                    "npr_agc_function_change_event_ratio": 0.5,
                    "npr_detection_complete": True,
                    "npr_specification": "range100_200",
                    "npr_treatment_period": "control",
                    "has_parse_exclusion": 1,
                    "parse_exclusion_records": 2,
                    "treatment_group": "control",
                },
                {
                    "dataset_source": "treatment",
                    "repo_name": "t/repo",
                    "time": "2024-01",
                    "time_to_event": -1,
                    "event": "2024-02",
                    "post_event": 0,
                    "npr_scored_function_change_events": 0,
                    "npr_agc_function_change_events": 0,
                    "npr_hwc_function_change_events": 0,
                    "has_npr_scored_function_change_event": 0,
                    "zero_npr_scored_function_event_month": 1,
                    "zero_all_function_event_month": 0,
                    "has_function_events_but_no_npr_selected_event": 1,
                    "log1p_npr_scored_function_change_events": 0.0,
                    "log1p_npr_agc_function_change_events": 0.0,
                    "log1p_npr_hwc_function_change_events": 0.0,
                    "npr_agc_function_change_event_ratio": np.nan,
                    "npr_detection_complete": True,
                    "npr_specification": "range100_200",
                    "npr_treatment_period": "pre",
                    "has_parse_exclusion": 0,
                    "parse_exclusion_records": 0,
                    "treatment_group": "treatment",
                },
                {
                    "dataset_source": "treatment",
                    "repo_name": "t/repo",
                    "time": "2024-02",
                    "time_to_event": 0,
                    "event": "2024-02",
                    "post_event": 1,
                    "npr_scored_function_change_events": 3,
                    "npr_agc_function_change_events": 2,
                    "npr_hwc_function_change_events": 1,
                    "has_npr_scored_function_change_event": 1,
                    "zero_npr_scored_function_event_month": 0,
                    "zero_all_function_event_month": 0,
                    "has_function_events_but_no_npr_selected_event": 0,
                    "log1p_npr_scored_function_change_events": np.log1p(3),
                    "log1p_npr_agc_function_change_events": np.log1p(2),
                    "log1p_npr_hwc_function_change_events": np.log1p(1),
                    "npr_agc_function_change_event_ratio": 2 / 3,
                    "npr_detection_complete": True,
                    "npr_specification": "range100_200",
                    "npr_treatment_period": "event",
                    "has_parse_exclusion": 0,
                    "parse_exclusion_records": 0,
                    "treatment_group": "treatment",
                },
            ]
        )
        covariates = analysis[KEY_COLUMNS].copy()
        covariates["age"] = [1, 2, 1, 2]
        covariates["ncloc_paper"] = [100, 110, 120, 130]
        covariates["ncloc_python_snapshot"] = [90, 100, 110, 120]
        covariates["contributors"] = [1, 2, 1, 2]
        covariates["stars"] = [0, 1, 2, 3]
        covariates["issues"] = [0, 0, 1, 1]
        for column in LEAD_LAG_COLUMNS:
            covariates[column] = 0

        analysis.to_csv(analysis_path, index=False)
        covariates.to_csv(covariate_path, index=False)

        outputs = build_outputs(
            analysis_path,
            covariate_path,
            "range100_200",
            {
                "rows": 4,
                "positive_rows": 2,
                "zero_rows": 2,
                "function_no_selected_rows": 1,
                "control_rows": 2,
                "treatment_rows": 2,
                "parse_exclusion_months": 1,
            },
            {
                "age": 0,
                "contributors": 0,
                "stars": 0,
                "issues": 0,
                "ncloc_paper": 0,
            },
        )
        if not outputs["overall_pass"]:
            failed = outputs["checks"].loc[
                ~outputs["checks"]["passed"], ["check", "observed"]
            ]
            raise AssertionError(
                f"Self-test checks failed:\n{failed.to_string(index=False)}"
            )
        if len(outputs["ratio_panel"]) != 2:
            raise AssertionError("Self-test ratio panel row count is incorrect")
        if outputs["ratio_panel"][
            "npr_agc_function_change_event_ratio"
        ].isna().any():
            raise AssertionError("Self-test ratio panel contains a missing ratio")


def main() -> int:
    args = parse_args()

    if args.self_test:
        run_self_test()
        print("Self-test: PASS")
        if args.input_table is None:
            return 0

    input_table = require_file(args.input_table, "run-py-7a input table")
    covariate_panel = require_file(args.covariate_panel, "Covariate panel")
    if args.output_dir is None:
        raise ValueError("--output-dir is required for a production run")
    output_dir = args.output_dir
    qc_dir = args.qc_dir or output_dir / "qc"

    prepare_output_directory(output_dir, args.overwrite_output)
    qc_dir.mkdir(parents=True, exist_ok=True)

    outputs = build_outputs(
        input_table,
        covariate_panel,
        args.specification_name,
        {
            "rows": args.expected_rows,
            "positive_rows": args.expected_positive_event_rows,
            "zero_rows": args.expected_zero_event_rows,
            "function_no_selected_rows": (
                args.expected_function_event_no_selected_rows
            ),
            "control_rows": args.expected_control_rows,
            "treatment_rows": args.expected_treatment_rows,
            "parse_exclusion_months": args.expected_parse_exclusion_months,
        },
        {
            "age": args.known_age_missing,
            "contributors": args.known_contributors_missing,
            "stars": args.known_stars_missing,
            "issues": args.known_issues_missing,
            "ncloc_paper": args.known_paper_ncloc_missing,
        },
    )
    summary = write_outputs(
        outputs,
        input_table,
        covariate_panel,
        output_dir,
        qc_dir,
        args.specification_name,
    )

    print("=" * 78)
    print("run-py-7b: prepare NPR commit-function Borusyak DiD inputs")
    print("=" * 78)
    print(f"Status:                                  {summary['status']}")
    print(f"Specification:                           {summary['specification']}")
    print(f"Full panel rows:                         {summary['full_panel_rows']}")
    print(f"Conditional-ratio panel rows:            {summary['ratio_panel_rows']}")
    print(f"Zero NPR-selected rows:                  {summary['zero_npr_selected_rows']}")
    print(
        "Function-event rows with no selected NPR event: "
        f"{summary['function_event_positive_but_no_npr_selected_rows']}"
    )
    print(f"Control rows:                            {summary['control_rows']}")
    print(f"Treatment rows:                          {summary['treatment_rows']}")
    print(f"Parse-exclusion months:                  {summary['parse_exclusion_months']}")
    print(f"Parse-clean full rows:                   {summary['parse_clean_full_rows']}")
    print(f"Parse-clean ratio rows:                  {summary['parse_clean_ratio_rows']}")
    print(f"Failed checks:                           {summary['failed_checks']}")
    print(f"Output directory:                        {output_dir}")
    print(f"QC directory:                            {qc_dir}")
    print("=" * 78)

    return 0 if outputs["overall_pass"] else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise
